### ISSUE TITLE
Namensänderung

### ISSUE THREAD

**Issue by tyrant88** [FriendsOfREDAXO/consent_manager#100]
Hey Leute, bevor die Version 2 in final released wird, würde ich gerne mal über eine Namensänderung schnacken.
Denn das "iwcc" finde ich für ein FOR AddOn nicht so ganz passend.  "Cookie Gedöhns" ist natürlich genial und sollte auch der gesprochene Name bleiben. 
Als ersten Vorschlag würde ich "acct" = "A cookie consent tool" nennen. "REX_ACCT" sieht dann auch cool aus.
Oder deutsch? 
"ecew" ="Ein Cookie Einverständnis Werkzeug"?
"eceh" ="Eine Cookie Einverständnis Hilfe"?

Vielleicht fällt auch jemand was für "iwcc" ein :-) Dann wird es ganz einfach.

**Comment by schuer** [comment]
»[Cookies](https://github.com/FriendsOfREDAXO/iwcc/issues/42#issuecomment-608469798)« :)

**Comment by tyrant88** [comment]
@schuer Eben erst gesehen, dass das ein Link ist! :-)
Sorry, for not suching alte issues first.

"Cookies" ist natürlich auch eine Option. REX_COOKIES.

**Comment by olien** [comment]
kann geschlossen werden...

iwcc steh für **I** **w**ish **C**ookie **C**onsent

**Comment by tyrant88** [comment]
Not funny. Wäre schön wenn @IngoWinter sich mal äüßern würde.

**Comment by skerbis** [comment]
Also, wenn es jetzt umbenannt wird versperren wir allen Installationen den Weg zum Update über den Installer. 
Das finde ich nicht so gut.

**Comment by schuer** [comment]
> Also, wenn es jetzt umbenannt wird versperren wir allen Installationen den Weg zum Update über den Installer.

Das hatten wir schonmal bei den zahlreichen AddOns mit rex-Prefix, etwa `rex_markitup`. Kann man etwas abfedern, indem man ein letztes 1er-Release mit altem Namen veröffentlicht, das lediglich auf den neuen Namen hinweist und erklärt, das man sich das einmal manuell aus dem Installer fischen muss.

Weil es sowieso ein Release mit Breaking Changes ist, das man nicht einfach übernehmen kann ohne Anpassungen im Code, fände ich die zusätzliche Namensänderung an dieser Stelle nicht schwierig.

**Comment by tbaddade** [comment]
> Wäre schön wenn @IngoWinter sich mal äüßern würde.

https://github.com/FriendsOfREDAXO/iwcc/issues/42#issuecomment-608022448

**Comment by tyrant88** [comment]
Gut, hast Recht, ich formuliere um: Ich würde sehr gerne Ingos Meinung dazu hören, weil sie mir wichtig ist. Ich suche eine Möglichkeit, damit er diese Namensänderung unterstützt und mitträgt. Wenn es die nicht gibt, würde ich dass auch gerne wissen.
Das beantwortet sich für mich nicht durch ein "ist mir egal" vor 7 Monaten.

**Comment by IngoWinter** [comment]
Ist mir immer noch egal. Von mir aus könnte es auch `idgaf` oder `idc` heissen. Muss ja nur eindeutig sein...

**Comment by tyrant88** [comment]
Gut. Also d.h. du willst/wirst es nicht machen?

**Comment by IngoWinter** [comment]
Genau. Ich habe nix gegen eine Umbenennung, möchte aber auch nix damit zu tun haben.

**Comment by tyrant88** [comment]
Schade. Dann zurück auf Anfang.
Dirks "cookies" zu allgemein?
Doch "cookie_consent"?

**Comment by tbaddade** [comment]
- Cookie Consent Management 
- Consent Manager
- Cookie Consent Solution

**Comment by tyrant88** [comment]
und würdest du das auch wieder zusammenziehen wollen zu Akronymen wie "ccm" und "ccs"? 
"Consent Manager" hingegen könnte man komplett übernehmen als "consent_manager" ohne das es zuuu lang ist - Und es würde auch andeuten, dass man das Teil ja auch für andere vorgeschalteten Zustimmungen nutzen könnte....
...mir geht es schon um ein "find & replace" für den Code.

**Comment by skerbis** [comment]
privacy manager ... denn es geht nicht nur um cookies
