### ISSUE TITLE
Neues Recht für Nutzer: "nur Cookietexte ändern"

### ISSUE THREAD

**Issue by iceman-fx** [FriendsOfREDAXO/consent_manager#101]
Es wäre toll, wenn es ein neues Benutzerrecht geben würde, wo man dem Pflegenutzer die Änderung der Cookietexte (alle Sprachen) ermöglichen könnte.

Damit könnte der Nutzer diese selbst ändern, ohne dass er an wichtigen Einstellungen etwas verändern kann.

**Comment by aeberhard** [comment]
Neues Recht consent_manager[texteditonly] kommt ab Version 3.0.0.beta1
