### ISSUE TITLE
Cookie Gruppe "Marketing" immer vorausgewählt

### ISSUE THREAD

**Issue by despecial** [FriendsOfREDAXO/consent_manager#102]
Habe über den Demo-Import die ganzen Cookies und Gruppen angepasst.
Alles klappt auch soweit, nur wird beim Anzeigen immer "Notwendige" und "Marketing" vorausgewählt.
Eigentlich dürfen keine vorausgewählt werden (bzw nur notwendige/nicht deaktivierbare).

Woher kommt das bzw gibt es einen Hook das abzustellen?

Redaxo: 5.11.0
Script-Version: 2.0.0-beta8

**Comment by tyrant88** [comment]
kann ich nicht nachvollziehen.
