### ISSUE TITLE
Können Cookies auch geblockt werden?

### ISSUE THREAD

**Issue by VIEWSION** [FriendsOfREDAXO/consent_manager#103]
Hi,
ich suche nach einem möglichst einfach CC Tool... und da würde sich das natürlich anbieten. Bei den bekannten externen Anbietern werden Cookies meist rein über JS aktiv blockiert - das scheint hier nicht so zu sein, oder? Das hätte natürlich den Vorteil dass man die unterschiedlichst verteilten Tracking Skripte einfach so lassen könnte und quasi nur - falls gewünscht - das Setzen der Cookies verhindert würde.

**Comment by IngoWinter** [comment]
das ist hier nicht so
