### ISSUE TITLE
CSS und JavaScript usw. optimieren

### ISSUE THREAD

**Issue by aeberhard** [FriendsOfREDAXO/consent_manager#104]
Im Moment werden 3 CSS-Dateien und 3 JavaScript-Dateien benötigt.
Ich finde das sollte unbedingt optimiert werden!
@IngoWinter ich weiss Du bist ja gerade am überarbeiten :) TOP!

CSS
- Fontello - Warum? Ich habe ja z.B. eine Firmenwebseite mit eigener Hausschrift, dann möchte ich auch diese im Cookie-Consent
- Pretty Checkbox - Auch hier habe ich evtl. schon eigene Styles vorgegeben und muss die wieder umbiegen

JavaScript
- die 3 Scripte sollten in eines zusammengefasst werden
- Das Template sollte auch wenn möglich in eine Datei die eingebunden wird ausgelagert werden

Die CSS/Scripte werden IMMER eingebunden. Wenn ich Cookies akzeptiert habe dann brauche ich das ganze ja nicht mehr.
Vielleicht noch auf bestimmten Seiten wie Impressum oder Datenschutz, und eigentlich nur dann wenn ich einen "Bearbeiten"-Link drin habe.

Hier wäre m.M. nach eine Konfigurations-Möglichkeit sinnvoll bei der man auswählen kann auf welchen Seiten das "Gedöhns" immer ausgegeben wird damit der "Cookies-Bearbeiten-Link" funktioniert.
In 99,99 Prozent wird das "Gedöhns" sonst unnötig über die Leitung gejubelt :)

On Top wäre eine Auswahl des "Designs" (mittig, unten, oben, Hintergrundfarbe, Opacity ja/nein ... whatever) über die Einstellungen Klasse.

Sonstige Styles (Schrift, Linkfarben usw.) sollten von der Webseite übernommen werden.

Wer das ganze dann doch "überreiten" will kann ja zusätzliches CSS einbinden.

Beteilige mich auch gerne an der Umsetzung :)

**Comment by IngoWinter** [comment]
Der Nutzer muss jederzeit seine Datenschutzpräferenzen anpassen können. Idealerweise hast du also einen entsprechenden Link im Footer und musst dementsprechend auch auf jeder Seite die assets laden. Nach dem ersten Laden sind sie eh im Cache, wg. http2 sollte die Anzahl eigentlich egal sein.

Fontello ist für die Icons zuständig, Pretty Checkbox für die Checkboxen. Beides ist drin, damit man iwcc nutzen kann, ohne groß CSS zaubern zu müssen. Deswegen sind auch ein paar Farben vorgegeben. Was du machen könntest wäre Fontello und Pretty Checkbox durch SVGs zu ersetzen - dann sind 2 Abhängigkeiten weg.

**Comment by aeberhard** [comment]
Ich finde einfach dass das ganze Zeug's optional (als Default) mitkommen soll. 

Die Lösung mit den Cookies ist schon super!

Im Backend haben wir optimiert wg. Ladezeiten usw. (mform, mblock, Editoren, Codemirror usw.)
Und im Frontend werden hier http-Requests und Bytes ohne Rücksicht auf Verluste mitgeschleift.
Meine Meinung :)
Ich glaube auch nicht dass alle im Footer einen Link einbauen, sehe das eher auf der Datenschutzseite, und dann wird das ganze
unnötigerweise auf jeder Seite mit ausgegeben.

Browser-Cache schön und gut. Aber noch besser ist wenn der Browser gar nicht erst checken muss ob er 
die Datei schon heruntergeladen hat, ob sie auch noch im Cache vorhanden ist. Auch das lesen aus dem Cache kostet Zeit.

Und die meisten (Entwickler) werden sowieso optische Anpassungen und evtl. auch Anpassungen des Fragments machen.
"Anwender" können das ja dann per Default ohne Anpassungen verwenden :)

**Comment by IngoWinter** [comment]
Es ist aktuell genau so, wie du es gerne hättest. Du hast nach der Installation einen Default, den du jederzeit mit einem eigenen Fragment https://github.com/FriendsOfREDAXO/iwcc/blob/master/fragments/iwcc_box.php anpassen kannst. Schmeiss halt raus was du nicht brauchst. Und wenn du die Box nur auf bestimmten Seiten laden möchtest, bau halt eine Abfrage in dein Seitentemplate. iwcc kann nicht wissen, wo du es ausgeben möchtest :)

**Comment by aeberhard** [comment]
Ok, ich kann damit leben. Wenn keine Optimierung gewünscht wird :)
Ich würde das ganze halt über ein Script-Tag und ein CSS-Tag abfackeln.

**Comment by IngoWinter** [comment]
Dann musst du jedesmal, wenn sich irgendwas an einer der 6 CSS/JS Dateien ändert, die beiden "großen" Dateien neu erstellen. Ich habe da keinen Bock drauf. Du?

**Comment by aeberhard** [comment]
Alles durch PHP jagen, Template als JS-Variable ausgeben und gut ist.
Files bleiben als einzelne bestehen werden per PHP zusammengebastelt.
Und auch die Ausgabe könnte man anhand der Link-Klasse automatisieren und Scripte nur ausgeben
wenn auch ein Link mit der Klasse da ist.

Codemirror hat z.B. zig einzelne CSS-Files und JS-Files für die einzelnen Plugins
und wird nur eingebunden wenn auch Codemirror notwendig ist

```
index.php?codemirror_output=css&buster=1605738840&themes=
index.php?codemirror_output=javascript&buster=1605738840
```

**Comment by aeberhard** [comment]
Da haben @staabm und ich mal richtig Arbeit reingesteckt :)

**Comment by aeberhard** [comment]
Ich weiss, ist nicht eben mal so einfach umgesetzt. Aber würde mich ja dran beteiligen.
Im Moment sieht der HTML-Code einer Webseite auch fast aus wie der einer W#rDpr3ss-Seite :(

**Comment by IngoWinter** [comment]
Mach gerne einen PR.
Ich habe keine Motivation, dabei mitzuhelfen. Das ist ein Haufen Arbeit für einen - meiner Meinung nach - eher kosmetischen Effekt.

**Comment by aeberhard** [comment]
Wenn das für dich ok ist würde ich mich da mal dran machen.
Bist Du grade am iwcc dran? Hatte da letztens einen Screenshot im Slack gesehen!?

**Comment by IngoWinter** [comment]
Nee, hast freie Bahn. Wenn was ist mach ein Issue auf :)

**Comment by IngoWinter** [comment]
Wiedereröffnet, damit es besser gefunden wird.

**Comment by aeberhard** [comment]
![image](https://user-images.githubusercontent.com/330560/104071325-3ad2aa00-5209-11eb-8766-0155acce6232.png)


@IngoWinter Wäre das für dich so Ok (siehe Markierungen)!?

Habe als **ersten Schritt** das Fragment leicht angepasst. Fontello und Prettycheckbox entfernt und die 
Checkboxen und den Close-Button per CSS gestyled (in der consent_manager_frontend.css). 
Die Checkboxen liegen dann innerhalb des Labels.

Wenn Ok dann würde ich einen PR starten und natürlich auch die consent_manager_frontend.scss anpassen und
die Files für Fontello /Prettycheckbox entfernen.

**Comment by IngoWinter** [comment]
Ich habe noch engagierte Leuts zum drübergucken eingeladen. Von mir aus ist das ok, auch wenn ich kein großer Fan der Checkbox Optik bin. Wichtig wäre mir nur, dass das auch in allen aktuellen Browsern +ie11 funktioniert.

**Comment by aeberhard** [comment]
Die Checkbox ist ja bis auf das "Hakerl" identisch. Versuche auch noch das Hakerl hinzubekommen.

**Comment by polarpixel** [comment]
Danke an @aeberhard fürs @IngoWinter fürs Dazuholen und natürlich für das AddOn überhaupt!
Ich finde Andreas' Idee schon sehr gut, Abhängigkeiten zu reduzieren und die Flexibiltät zu erhöhen. Ich denke, die Optik der Checkboxen kommt in den meisten Fällen ja wirklich von der Website selbst.

**Comment by marcohanke** [comment]
Moin, ich bin auch bei @aeberhard und würde das gerne verschlanken. Wenn ich ganz ehrlich bin, würde ich am liebsten sogar komplett ohne CSS auskommen wollen oder die CSS als sample mitgeben. Dann kann sich den Kram jeder selber gestalten wie er will und alle die keine Ahnung/Muße dazu haben, kopieren sich den Kram aus der Sample in Ihr eigenes CSS.

**Comment by IngoWinter** [comment]
@aeberhard scheint keiner was zu mäkeln zu haben - dann man ab dafür wa :)

**Comment by aeberhard** [comment]
@polarpixel @skerbis @marcohanke @IngoWinter 
Klasse! Könnte die bisherige Änderung jemand gegentesten!?
Siehe PR https://github.com/FriendsOfREDAXO/consent_manager/pull/118

**Comment by aeberhard** [comment]
@marcohanke finde ich eine gute Idee. 
Nach Installation wird standardmäßig das bisherige CSS aktiviert und man muss aktiv
in den Einstellungen aktivieren dass man eigenes CSS liefert.

**Comment by aeberhard** [comment]
Servus zusammen,

ich habe jetzt auch umgesetzt dass man eigene Styles verwenden kann.
Die bisherige Standard-Ausgabe bleibt erhalten und man muss aktiv in den Addon-Einstellungen tätig werden.

Soll ich das in den PR mit dazu packen oder besser einen eigenen Branch erstellen!? @IngoWinter @skerbis @marcohanke

**Comment by IngoWinter** [comment]
Merge einfach rein das Dingen. Und wenn du durch bist machen wir ne beta 3 draus und packens in den Installer, dann wirds auch getestet :o)
