### ISSUE TITLE
Titelbild in README.md an neuen Namen anpassen

### ISSUE THREAD

**Issue by alxndr-w** [FriendsOfREDAXO/consent_manager#107]
siehe https://github.com/FriendsOfREDAXO/consent_manager/raw/assets/consent_manager-logo.jpg?raw=true

**Comment by tyrant88** [comment]
das "iwcc" hab ich einfach weggeschnitten...

**Comment by tyrant88** [comment]
die jpg wurde von skrebis gelöscht...
