### ISSUE TITLE
Redax-Installation im Unterverzeichnis

### ISSUE THREAD

**Issue by oioix** [FriendsOfREDAXO/consent_manager#108]
Redaxo liegt während der Entwicklungsphase gerne in einem geschützten Unterverzeichnis.
Damit der consent_manager auch aus dem Unterverzeichnis läuft, braucht er nur eine kleine Ergänzung:

In der Datei "fragments/consent_manager_box.php" die 6x Links zu CSS/JS (Zeile 9-14) wie folgt ergänzen:
`<?php echo rex_url::base(); ?>`

im linktext vor /assets/addons/consent_manager/...    setzen und den Slash vor "assets" weglassen, da er ansonsten im Link doppelt ausgegeben wird.

Also wie folgendes Beisiel:
`<script src="<?php echo rex_url::base(); ?>assets/addons/consent_manager/js.cookie-2.2.1.min.js"></script>`

Funktioniert dann wunderbar!

**Comment by IngoWinter** [comment]
@aeberhard macht da gerade was https://github.com/FriendsOfREDAXO/consent_manager/issues/104 - vielleicht baut er das ja direkt ein.

**Comment by oioix** [comment]
Wäre ruck zuck passiert und ich hab es natürlich getestet.

**Comment by IngoWinter** [comment]
Wenn du möchtest, mach einen PR. Kannst auch gerne direkt mergen, wenns gestestet ist.

**Comment by oioix** [comment]
Sorry, aber ich hab bisher auf github nie irgendetwas gemacht.  Entwickle nur auf meinen Servern. 
Bin hier neu und weiß daher leider nicht wie das geht. ;-)

**Comment by aeberhard** [comment]
Ich habe das genau so bei mir auf einer Testseite.
Ich werde das aber wie Ingo schon sagt generell überarbeiten. @IngoWinter @oioix

**Comment by oioix** [comment]
Alles klar. 

Übrigens ein tolles Addon ! :-)
