### ISSUE TITLE
ErrorException (E_NOTICE) Undefined offset: 1

### ISSUE THREAD

**Issue by alxndr-w** [FriendsOfREDAXO/consent_manager#109]
Nach hinzufügen einer Domain

**ErrorException:** Undefined offset: 1
**File:** redaxo/src/addons/consent_manager/lib/consent_manager_cache.php
**Line:** 85

<details>
<summary>Stacktrace</summary>

| Function                                     | File                                                            | Line     |
| -------------------------------------------- | --------------------------------------------------------------- | -------- |
| rex_error_handler::handleError               | redaxo/src/addons/consent_manager/lib/consent_manager_cache.php | 85       |
| consent_manager_cache->prepareData           | redaxo/src/addons/consent_manager/lib/consent_manager_cache.php | 34       |
| consent_manager_cache->writeCache            | redaxo/src/addons/consent_manager/lib/consent_manager_cache.php | 25       |
| consent_manager_cache::write                 | redaxo/src/core/lib/extension.php                               | 49       |
| rex_extension::{closure}                     | redaxo/src/core/lib/util/timer.php                              | 54       |
| rex_timer::measure                           | redaxo/src/core/lib/extension.php                               | 56       |
| rex_extension::registerPoint                 | redaxo/src/core/lib/form/form.php                               | 382      |
| rex_form->save                               | redaxo/src/core/lib/form/form_base.php                          | 1164     |
| rex_form_base->get                           | redaxo/src/addons/consent_manager/pages/domain.php              | 43       |
| include                                      | redaxo/src/core/lib/packages/package.php                        | 250      |
| rex_package->includeFile                     | redaxo/src/core/lib/be/controller.php                           | 476      |
| rex_be_controller::{closure}                 | redaxo/src/core/lib/util/timer.php                              | 54       |
| rex_timer::measure                           | redaxo/src/core/lib/be/controller.php                           | 477      |
| rex_be_controller::includePath               | redaxo/src/core/lib/be/controller.php                           | 432      |
| rex_be_controller::includeCurrentPageSubPath | redaxo/src/addons/consent_manager/pages/index.php               | 8        |
| include                                      | redaxo/src/core/lib/packages/package.php                        | 250      |
| rex_package->includeFile                     | redaxo/src/core/lib/be/controller.php                           | 476      |
| rex_be_controller::{closure}                 | redaxo/src/core/lib/util/timer.php                              | 54       |
| rex_timer::measure                           | redaxo/src/core/lib/be/controller.php                           | 477      |
| rex_be_controller::includePath               | redaxo/src/core/lib/be/controller.php                           | 415      |
| rex_be_controller::includeCurrentPage        | redaxo/src/core/backend.php                                     | 235      |
| require                                      | redaxo/src/core/boot.php                                        | 137      |
| require                                      | redaxo/index.php                                                | 9        |

</details>
<details>
<summary>System report (REDAXO 5.11.1, PHP 7.4.11, MariaDB 10.2.34)</summary>

| REDAXO        |            |
| ------------: | :--------- |
|       Version | 5.11.1     |

| PHP           |            |
| ------------: | :--------- |
|       Version | 7.4.11     |
|       OPcache | yes        |
|        Xdebug | no         |

| Database      |                 |
| ------------: | :-------------- |
|       Version | MariaDB 10.2.34 |
| Character set | utf8mb4         |

| Server        |            |
| ------------: | :--------- |
|            OS | Linux      |
|          SAPI | fpm-fcgi   |
|     Webserver | Apache     |

| Request       |                     |
| ------------: | :------------------ |
|       Browser | Chrome/87.0.4280.88 |
|      Protocol | HTTP/2.0            |
|         HTTPS | yes                 |

| Packages                |             |
| ----------------------: | :---------- |
|            accessdenied | 1.0.6       |
|                  across | 3.0.0-dev23 |
|          across/backend | 3.0.0       |
|                 adminer | 1.8.2       |
|                  backup | 2.6.2       |
|                be_style | 2.11.1      |
|     be_style/customizer | 2.11.0      |
|         be_style/redaxo | 2.11.1      |
|                 bloecks | 3.0.0       |
|        bloecks/cutncopy | 3.0.0       |
|          bloecks/status | 3.0.0       |
|                    cke5 | 4.2.1       |
|         consent_manager | 2.0.1       |
|                 cronjob | 2.7.1       |
|  cronjob/article_status | 2.7.1       |
| cronjob/optimize_tables | 2.7.1       |
|               developer | 3.9.0       |
|                  events | 2.0.0-dev   |
|                   feeds | 3.1         |
|                 install | 2.8.0       |
|             maintenance | 2.5.0       |
|                markitup | 3.6.0       |
|                  mblock | 3.1.0       |
|           media_manager | 2.10.1      |
|               mediapool | 2.9.0       |
|                metainfo | 2.7.2       |
|                   mform | 5.3.1       |
|              mform/docs | 1.0         |
|                  minify | 2.2         |
|               phpmailer | 2.9.1       |
|                 project | dev         |
|        quick_navigation | 3.9.5       |
|                   sprog | 1.2.0       |
|               structure | 2.11.1      |
|       structure/content | 2.11.1      |
|       structure/history | 2.11.0      |
|       structure/version | 2.11.0      |
|                   theme | 1.2.0       |
|                uploader | 2.2.0       |
|                     url | 2.0.0-beta3 |
|                   users | 2.7.1       |
|                  watson | 2.2.0       |
|                    ycom | 4.0.3       |
|               ycom/auth | 4.0.3       |
|               ycom/docs | 4.0.3       |
|              ycom/group | 4.0.3       |
|                   yform | 3.4.1       |
|             yform/email | 3.4.1       |
|           yform/manager | 3.4.1       |
|             yform/tools | 3.4.1       |
|           yform_geo_osm | 1.2.3       |
|   yform_spam_protection | 1.0.5       |
|         yform_usability | 1.4         |
|                yrewrite | 2.7         |
|             zip_install | 1.1         |

</details>

**Comment by aeberhard** [comment]
Closed mit PR #120
