### ISSUE TITLE
Einbindung von CSS und JS optional machen / Methoden schaffen

### ISSUE THREAD

**Issue by bitshiftersgmbh** [FriendsOfREDAXO/consent_manager#114]
Ich nutze bei den meisten Installationen das AddOn [massif_minify](https://github.com/ynamite/massif_minify). Damit wurschtel ich via Mittelsmann-Skript alles so zusammen, dass nur jeweils 1 minifiziertes CSS-Skript rauskommt und 1 minifiziertes JS-Skript, welche dann im <head> eingebunden werden. Freut den User wegen Lade-Speed und Google auch.

Nun lädt der Content Manager 3 CSS-Files und 3 JS-Files nach. Beim CSS ist auch Fontello dabei, was ich nicht möchte/nutze, weil sonst alles mit Font Awesome läuft.

Cool wäre, wenn man - als einfache, schnelle Lösung - zumindest in den Settings oder der package.yml einstellen könnte, ob man die Skripte laden möchte oder nicht. Passend dazu wären Methoden schön, die die Pfade zu den jeweiligen Skripten zurückgeben, z.B. `consent_manager_config::getJsUrls()` und `consent_manager_config::getCssUrls()` [Rückgabe wäre jeweils ein Array]. Damit könnte die consent_manager_box.php selbst umgestellt werden und die, die es anderweitig einbinden wollen, das auch easy tun.

**Comment by IngoWinter** [comment]
siehe https://github.com/FriendsOfREDAXO/consent_manager/issues/104
@aeberhard arbeitet gerade daran, du könntest dich mit ihm zusammentun
