### ISSUE TITLE
Checkboxen und Labels verknüpfen

### ISSUE THREAD

**Issue by bitshiftersgmbh** [FriendsOfREDAXO/consent_manager#115]
Standardmäßig sind ja "Notwendig" und "Statistik" als Cookie-Gruppen im Popup sichtbar. Wenn ich allerdings auf das Label zu "Statistik" klicke, ändert sich die Checkbox nicht (was ich aber erwarten würde). Das geht auch nicht, weil das `<label>` kein for-Attribut hat und die zugehörige Checkbox keine ID.

Datei: **consent_manager_box.php**

**Comment by IngoWinter** [comment]
siehe https://github.com/FriendsOfREDAXO/consent_manager/issues/104
@aeberhard arbeitet gerade daran, du könntest dich mit ihm zusammentun
