### ISSUE TITLE
Mehrsprachige Website: Übernahme des Cookie-Skripts

### ISSUE THREAD

**Issue by DanielWeitenauer** [FriendsOfREDAXO/consent_manager#116]
Ich habe auf einer mehrsprachigen Website das Skript eines Cookies in der Startsprache geändert. Diese Änderungen werden nicht in die zweite Sprache übernommen. 
Aktuell ist die Anpassung nur direkt in der DB möglich.

**Comment by IngoWinter** [comment]
https://github.com/FriendsOfREDAXO/consent_manager/issues/97

**Comment by DanielWeitenauer** [comment]
Alles klar, dann geht es dort weiter. Danke!
