### ISSUE TITLE
CSS- und JS-Dateien minimieren und bündeln?

### ISSUE THREAD

**Issue by mbodon** [FriendsOfREDAXO/consent_manager#117]
Hi, momentan werden 3 CSS und 3 JS-Dateien immer nachgeladen. 
Gibt es eine Möglichkeit daraus nur jeweils eine minimierte Datei zu machen? 
Vielleicht sogar in Verbindung mit dem Minify-AddOn?

Ich weiß das ich ja die PHP-Datei händisch ändern kann 
nur wird diese dann bei jedem Update überschrieben ... ;-(

Wäre nur nice to have - überhaupt nicht wichtig (ausser bei SEO-Optimierungen)

**Comment by IngoWinter** [comment]
siehe https://github.com/FriendsOfREDAXO/consent_manager/issues/104
@aeberhard arbeitet gerade daran, du könntest dich mit ihm zusammentun
