### ISSUE TITLE
Nach erneutem Aufrufen und Änderung an der Zustimmung gesetzte Cookies löschen

### ISSUE THREAD

**Issue by netzproductions** [FriendsOfREDAXO/consent_manager#119]
Fall: Zunächst werden alle Cookies zugelassen, z.B. auch Analytics. Dann erneutes Aufrufen der Consent Box und Abwahl der Statistikgruppe. In dem Fall bleiben die gesetzten Cookies von Analytics unberührt.
Aktuell frage ich das im Template ab und lösche bei nicht vorliegender Zustimmung die Cookies manuell, wäre toll, wenn das im AddOn integriert wäre.

**Comment by IngoWinter** [comment]
Das Löschen der Cookies ist überflüssig, da sie ohne dazugehöriges Tracking Skript vollkommen harmlos sind. 
Das Addon versucht bereits alle Cookies zu löschen, wenn der Consent zurückgenommen wird: https://github.com/FriendsOfREDAXO/consent_manager/blob/master/assets/consent_manager_frontend.js#L129-L139
Wenn du eine zuverlässigere Methode hast, mach gerne einen PR.
