### ISSUE TITLE
Lifetime Consent-Cookie einstellbar machen / bzw. löschen

### ISSUE THREAD

**Issue by aeberhard** [FriendsOfREDAXO/consent_manager#131]
Das Cookie ist default 1 Jahr gültig. 
Evtl. macht Sinn hier eine Vorgabe machen zu können z.B. 2 Wochen.

Auch ein löschen des Consent-Cookies sollte irgendwie möglich sein. Evtl. über die Consent-Box ...

**Comment by IngoWinter** [comment]
Warum? Dann poppt das nervige Dingen ja grundlos nach 2 Wochen wieder auf...

**Comment by aeberhard** [comment]
Hast Recht Ingo, ist wohl nur meine Manie gerne alles löschen oder einstellen zu können :)
