### ISSUE TITLE
Fehler ausgeben wenn keine Domain ausgewählt ist

### ISSUE THREAD

**Issue by aeberhard** [FriendsOfREDAXO/consent_manager#135]
Aktuell kommt da ein Fehler in der JavaScript-Konsole und es wird kein Consent-Popup angezeigt.

```
index.php?consent_manager_outputjs=1&v=1614069473:57 Uncaught TypeError: Failed to execute 'appendChild' on 'Node': parameter 1 is not of type 'Node'.
    at HTMLDocument.<anonymous> (index.php?consent_manager_outputjs=1&v=1614069473:57)
```

Ausgabe einer aussagefähigen Fehlermeldung im REDAXO-Log!? Dann kann man auf das Log verweisen.

Möglich wäre auch evtl. die Ausgabe eines JavaScript-Dialogs "Achtung Config unvollständig" wenn man im Backend angemeldet ist.

**Comment by aeberhard** [comment]
@IngoWinter ich frage mich gerade ob man in dem Fall im Frontend nicht ein JavaScript-Alert ausgeben soll.
Das kommt ja im Normalfall nur direkt nach der Einrichtung vor ... wenn man nicht alles korrekt vorgegeben hat.

**Comment by IngoWinter** [comment]
Ich würde es in der Konsole ausgeben lassen. Gibt genug Leute, die sowas direkt auf ner Live Website machen - da möchtest du keine Alerts :)

**Comment by aeberhard** [comment]
Ah ja auch gut und in der REDAXO-Console!
Kam ja schon öfter sowas https://friendsofredaxo.slack.com/archives/C1BAXLN2F/p1614599569214000

**Comment by IngoWinter** [comment]
Ja, das Addon ist relativ supportintensiv
