### ISSUE TITLE
Beta5 ignoriert fragt laufend neu an

### ISSUE THREAD

**Issue by TobiasKrais** [FriendsOfREDAXO/consent_manager#143]
Nach dem Upgrade auf Beta 5 kommt der Cookie Dialog laufend neu, obwohl eine Auswahl getroffen wurde. Beta 4 ist noch alles OK.

**Comment by aeberhard** [comment]
Kann ich nicht nachvollziehen @TobiasKrais . Kann man das online sehen?

**Comment by TobiasKrais** [comment]
Ja. Hier: https://ingtec.ch/de/

**Comment by aeberhard** [comment]
Hm. sieht so aus als ob der Button-Klick sofort weiterleitet und daher das Cookie nicht gesetzt werden kann.
Nimm doch mal zum test den bearbeiten-Link raus.

**Comment by TobiasKrais** [comment]
Ja. Wenn der Bearbeiten Link raus ist, dann klappt das.

**Comment by aeberhard** [comment]
Ok, ich schau mir das mal an. So sollte es ja nicht sein. Der Reload soll nur passieren wenn auch der Bearbeiten-Link geklickt wurde.

**Comment by TobiasKrais** [comment]
Danke!

**Comment by TobiasKrais** [comment]
Danke für die beta6 die den Fehler behebt.
