### ISSUE TITLE
CSS/JS inline ausgeben

### ISSUE THREAD

**Issue by alxndr-w** [FriendsOfREDAXO/consent_manager#144]
Der CSS/JS wird nur benötigt, wenn er tatsächlich dargestellt wird. Wenn nicht, braucht es ihn auch nicht. Wenn man ihn braucht, dann sofort.

Entspr. Google PageSpeed Insights würde ich empfehlen, den Code inline auszugeben:

![image](https://user-images.githubusercontent.com/3855487/109643255-3e711600-7b54-11eb-88ea-f45e9390bc1f.png)

**Comment by aeberhard** [comment]
@alxndr-w mit der neuen Version ist schon viel optimiert worden. Fontello ist raus, CSS und JS wurde auf jeweils eine (1) Datei eingedampft.

Die Standard-CSS kann man ja in den Einstellungen ausschalten und dann z.B. das CSS inline ins Template schreiben.
Die JS-Datei bastelt mehrere JS-Dateien und das Box-Template zusammen und wird auch gecached.

Kannst ja gerne einen PR beisteuern. Aber dann bitte auf jeden Fall optional als zusätzliche Einstellung in den Addon-Optionen ;-)

Ich bin ja nicht unbedingt ein Freund davon alles in den HTML-Code einzubauen. Google hin oder her.
Siehe auch CSP ... disable inline Scripte ...

**Comment by IngoWinter** [comment]
https://github.com/FriendsOfREDAXO/consent_manager/compare/async
Das wäre mein Vorschlag zu der Sache - da hat Google auch kein Problem mit. Das `REX_CONSENT_MANAGER[]` kommt dabei einfach vor das schliessende body Element.

**Comment by aeberhard** [comment]
@IngoWinter gerade ausprobiert. Sieht gut aus und funktioniert alles!

**Comment by IngoWinter** [comment]
Den Schluck CSS könnte man inline laden wie @alxndr-w schreibt. Dafür müsste man hier: https://github.com/FriendsOfREDAXO/consent_manager/blob/master/fragments/consent_manager_box_cssjs.php#L24 nur ein file_get_contents auf die CSS Datei machen. Damit sparen wir uns zukünftige Page Speed Anfragen - und die werden/würden 100%ig kommen.
Wenns keine Einwände gibt mach ich das gerne.

**Comment by aeberhard** [comment]
Ja mach mal Ingo :)

**Comment by IngoWinter** [comment]
@alxndr-w magst du mal testen?

**Comment by aeberhard** [comment]
Getestet. Top. 👍
