### ISSUE TITLE
Cookie Tabelle nicht sichtbar

### ISSUE THREAD

**Issue by polarpixel** [FriendsOfREDAXO/consent_manager#146]
In der Version 3.0.0beta6 ist die Tabelle der Cookies nicht sichtbar. Das führt dazu, dass auch kein neuer Cookie-Eintrag angelegt werden kann.
<img width="764" alt="2021-03-11_18-28-56" src="https://user-images.githubusercontent.com/330160/110828986-eba40680-8297-11eb-82b4-a1c1cb117676.png">

Das liegt anscheinend daran, dass die Tabelle per JS ausgeblendet wird.

<img width="996" alt="2021-03-11_18-30-05" src="https://user-images.githubusercontent.com/330160/110829246-30c83880-8298-11eb-8e00-e70ccb292107.png">

**Comment by aeberhard** [comment]
@polarpixel ich kann das nicht nachvollziehen und find auch nirgends wo das ausgeblendet wird!
Kann es sein dass da ein anderes CSS dazwischenfunkt!?

**Comment by IngoWinter** [comment]
@polarpixel ist das vielleicht dein neuer Cookiebanner Blocker?

**Comment by polarpixel** [comment]
Hahaha! Guter Tipp, @IngoWinter!
Das war in der Tat der Grund.
@aeberhard, ich hatte heute in der Tat eine Browser-AddOn zum Ausblenden von Cookie Bannern aktiviert.
Sorry für den Fehlalarm!
