### ISSUE TITLE
CSS + JavaScript im Frontend nur bei Bedarf ausgeben

### ISSUE THREAD

**Issue by IngoWinter** [FriendsOfREDAXO/consent_manager#149]
Wenn der Haken gesetzt ist, werden keine Skripte mehr geladen, die bei den Cookies hinterlegt sind.

**Comment by aeberhard** [comment]
Ich denke den Haken werde ich erstmal rausnehmen (auskommentieren).
Optimiert ist ja jetzt schon eine ganze Menge. 
Da die Ausgabe der Scripte im JS verankert ist muss das auch ausgegeben werden.
Wäre zu überlegen die Scripte losgelöst von der Box auszugeben. Aber das kann ja dann auch
später nochmal angegangen werden. 
@IngoWinter  Ok so?

**Comment by IngoWinter** [comment]
Klar.

**Comment by alxndr-w** [comment]
#175 passt vlt. ganz gut dazu.

**Comment by aeberhard** [comment]
Einstellung vorerst ausgeblendet, evtl. gibt es hier ja noch eine "schöne" Lösung
