### ISSUE TITLE
Notice direkt nach Installation

### ISSUE THREAD

**Issue by alexwenz** [FriendsOfREDAXO/consent_manager#151]
`Notice: Undefined index: consent_manager in redaxo/src/addons/consent_manager/boot.php on line 75`

Erscheint direkt nach der Installation via Installer. Allerdings nur beim REDAXO-Admin. Führt aber dazu, dass für diesen - im eingeloggten Zustand - dann das Frontend nicht mehr aufgerufen werden kann. (`Warning: Cannot modify header information - headers already sent by`)

**Comment by aeberhard** [comment]
Hi Alex @alexwenz , ich kann das leider nicht nachvollziehen. 
Welche REDAXO-Version? Welche Version vom consent_manager-Addon?

**Comment by alexwenz** [comment]
Entschuldigung, da habe ich die wichtigsten Angaben vergessen:

REDAXO 5.12.0
ConsentManager  3.0.0beta6

**Comment by IngoWinter** [comment]
In Zeile 75 wird auf `$_SESSION['consent_manager']` zugegriffen (ohne per isset() vorher zu checken, obs existiert). Der Sessionwert wird im Fragment für die Box gesetzt. Ich nehme also an, dass @alexwenz nicht `REX_CONSENT_MANAGER[]` ins Template eingesetzt hat.

**Comment by aeberhard** [comment]
Ja, komisch. Habe genau dieses probiert und bekomme keinen Fehler.
Ich bau da dann noch einen isset() rein.

**Comment by IngoWinter** [comment]
Du, die Anwender kriegen alles kaputt...

**Comment by Sysix** [comment]
Hatte den gleichen Fehler nach Update.  
Hab den `redaxo/cache/addon` und `redaxo/cache/core` Ordner gelöscht, danach ging alles.

**Comment by aeberhard** [comment]
Closed mit Beta7

**Comment by Sysix** [comment]
Ich hab von  der neusten Redaxo Version und Consent Manager aktualisiert. Das Problem ist noch nicht behoben!

**Comment by aeberhard** [comment]
Es gibt ja die Beta7 noch nicht im Installer.
Wenn Du die git-Version installiert hast dann Poste hier mal die Fehlermeldung.

**Comment by IngoWinter** [comment]
Die Beta 7 ist doch noch gar nicht im Installer.
