### ISSUE TITLE
Upgrade auf beta dupliziert Cookie Gruppen und Texte in nicht Startsprachen

### ISSUE THREAD

**Issue by TobiasKrais** [FriendsOfREDAXO/consent_manager#153]
Nach dem Upgrade von Version 2.x auf beta6 waren die Cookies, Cookie Gruppen und Cookie Texte dupliziert. Allerdings nicht in der Startsprache, sondern nur in den anderen Sprachen. Hier ein Screenshot:

![Bildschirmfoto von 2021-04-13 10-01-23](https://user-images.githubusercontent.com/4131072/114518366-91ec7e80-9c3f-11eb-9f61-5538903dd775.png)

**Comment by TobiasKrais** [comment]
Nebenbei: wehe dem, der dann einen doppelten Eintrag im Frontend löscht: schwups sind beide Einträge gelöscht!

**Comment by aeberhard** [comment]
Das ist in der Tag so. Beim installieren werden die Daten von iwcc übernommen.
Danach aber die Tabellen noch einmal beim 1. Aufruf in die weiteren Sprachen synchronisiert.

@IngoWinter die Funktionalität mit dem config-Eintrag 'justInstalled' kann m.M. nach entfallen. Oder was meinst Du Ingo!?

Das mit dem löschen ist denke ich mal so gewollt. Wenn z.B. Cookie 'youtube' gelöscht werden soll dann in allen Sprachen.

**Comment by aeberhard** [comment]
@IngoWinter ist das evtl. noch eine "Altlast"!? Da ja normalerweise bei der Installation keine Daten vorhanden sind.
die kommen ja erst durch das Setup rein.

**Comment by IngoWinter** [comment]
Ich meine das ist dafür da um einmalig nach der Installation alle bereits im System vorhanden Sprachen anzulegen.

**Comment by IngoWinter** [comment]
Hier wird extra auf `-1` geprüft: https://github.com/FriendsOfREDAXO/consent_manager/blob/master/install.php#L103
Das kann also eigentlich nur passieren, wenn in der rex_config noch kein Eintrag justInstalled drin ist.

**Comment by aeberhard** [comment]
In der boot.php ist auch noch eine Abfrage drin. Die gehört dann wohl raus.

**Comment by IngoWinter** [comment]
Diese Funktion https://github.com/FriendsOfREDAXO/consent_manager/blob/master/lib/consent_manager_clang.php#L176 ergänzt die DB Einträge für zusätzliche Sprachen. Bislang wird die Funktion in der boot.php und in der setup.php aufgerufen. 
Wenn du den Aufruf in der boot.php rausnimmst, funktioniert das Addon bei einer Neuinstallation auf einer mehrsprachigen Seite nicht mehr ohne den Setup Import (bisher geht's auch ohne). Von mir aus ist das ok.

**Comment by aeberhard** [comment]
Hmmm. Stimmt. Man müsste unterbinden dass bei einem Update von iwcc die Sprachen dupliziert werden.

**Comment by TobiasKrais** [comment]
Ein herzliches Danke euch beiden!
