### ISSUE TITLE
Vimeo Set aufnehmen?

### ISSUE THREAD

**Issue by tbaddade** [FriendsOfREDAXO/consent_manager#154]

**Comment by tbaddade** [comment]
Leider nicht. Ich brauchte das heute für Vimeo und @skerbis hatte dann etwas bei einem Dritten gefunden. Jedoch nichts offizielles.

**Comment by IngoWinter** [comment]
Wenn du was hast dann immer her damit - was "offizielleres" als deins wirds nirgendwo geben...

**Comment by IngoWinter** [comment]
Dankschön. Aber ich denke dann warten wir, bis irgendwer das mal auf deutsch fertig gemacht hat. Vielleicht kann derjenige dann direkt einen PR für die setup.sql beisteuern.
