### ISSUE TITLE
X-Button ausblenden oder optional

### ISSUE THREAD

**Issue by aeberhard** [FriendsOfREDAXO/consent_manager#157]
Sehe immer öfter Consent-Popups bei denen man **keinen** X-Button (Close) hat.
Man muss dann eine der vorgeschlagenen Auswahlen akzeptieren sonst geht es nicht weiter.

**Comment by IngoWinter** [comment]
Es kann ja schon jeder der möchte den x Button per CSS ausblenden. Das ist nichts, was ich jetzt in Code giessen würde - da gibts dringendere Baustellen ;)
