### ISSUE TITLE
PHP  Warnings

### ISSUE THREAD

**Issue by TobiasKrais** [FriendsOfREDAXO/consent_manager#159]
- Trying to access array offset on value of type null | redaxo/src/addons/consent_manager/lib/consent_manager_frontend.php | 109
- Undefined array key "consent_manager" | redaxo/src/addons/consent_manager/lib/consent_manager_frontend.php | 109
- Trying to access array offset on value of type null | redaxo/src/addons/consent_manager/lib/consent_manager_frontend.php | 77
- Undefined array key "consent_manager" | redaxo/src/addons/consent_manager/lib/consent_manager_frontend.php | 77
- Trying to access array offset on value of type null | redaxo/src/addons/consent_manager/lib/consent_manager_frontend.php | 63
- Undefined array key "" | redaxo/src/addons/consent_manager/lib/consent_manager_frontend.php | 63
- Undefined array key "consent_manager" | redaxo/src/addons/consent_manager/lib/consent_manager_frontend.php | 63
- Trying to access array offset on value of type null | redaxo/src/addons/consent_manager/lib/consent_manager_frontend.php | 51
- Undefined array key "consent_manager" | redaxo/src/addons/consent_manager/lib/consent_manager_frontend.php | 51

**Comment by IngoWinter** [comment]
@TobiasKrais bist du sicher, dass das an PHP 8 liegt? Das liest sich für mich nicht so. $irgendwas['consent_manager'] abfragen wenn $irgendwas null ist hat auch schon unter PHP < 8 nicht gut funktioniert :)

**Comment by TobiasKrais** [comment]
So du so fragst: stimmt. Ich hatte meinen Server auf PHP 8 umgestellt und gar nicht drauf geachtet, ob es nur an Version 8 liegt. Danke für den Hinweis. Titel ist korrigiert.

**Comment by aeberhard** [comment]
@TobiasKrais kannst Du mal versuchen in der Datei fragments/consent_manager_box_cssjs.php
folgendes zu ändern, also die Abfrage mit dem session_start():

```
<?php
$addon = rex_addon::get('consent_manager');
$debug = $this->getVar('debug');
$forceCache = $this->getVar('forceCache');

if (!isset($_SESSION)) {
    session_start();
}

$_SESSION['consent_manager']['article'] = rex_article::getCurrentId();
$_SESSION['consent_manager']['debug'] = $debug;
$_SESSION['consent_manager']['outputcss'] = '';
$_SESSION['consent_manager']['outputjs'] = '';
$_SESSION['consent_manager']['clang'] = rex_clang::getCurrentId();

```

**Comment by TobiasKrais** [comment]
OK. Ist probiert Leider immernoch die gleichen Meldungen im Log.

**Comment by aeberhard** [comment]
@TobiasKrais bitte noch einen Versuch :)

in der boot.php ab Zeile 60 nach session_start() die Werte setzen

```
if (rex::isFrontend()) {
    if (!isset($_SESSION)) {
        session_start();
        $_SESSION['consent_manager']['article'] = rex_article::getCurrentId();
        $_SESSION['consent_manager']['outputcss'] = '';
        $_SESSION['consent_manager']['outputjs'] = '';
        $_SESSION['consent_manager']['clang'] = rex_clang::getCurrentId();
    }
}
```

**Comment by TobiasKrais** [comment]
Das sieht gut aus! Jetzt kommt nur noch diese Meldung:

Undefined array key "debug" | redaxo/src/addons/consent_manager/lib/consent_manager_frontend.php | 96

**Comment by TobiasKrais** [comment]
Danke für die Codeänderungen (https://github.com/FriendsOfREDAXO/consent_manager/commit/d288ad96679ae7afe625d98ba1533cb200806648 und https://github.com/FriendsOfREDAXO/consent_manager/commit/9411e97557cdf9e8573a9408b195994538b9d415). Jetzt sind die Warnings weg :-)
