### ISSUE TITLE
Script Code wird nur in der ersten Sprache gelanden - alle anderen nicht

### ISSUE THREAD

**Issue by TobiasKrais** [FriendsOfREDAXO/consent_manager#162]
Der in den Cookies hinterlegte Script Code wird nur in der ersten Sprache einer Seite geladen, in allen anderen Sprachen nicht.

**Comment by IngoWinter** [comment]
Ist das vielleicht die Geschichte hier: https://github.com/FriendsOfREDAXO/consent_manager/issues/149?

**Comment by TobiasKrais** [comment]
Eventuell. Bei mir sind keine Haken gesetzt.

**Comment by IngoWinter** [comment]
Wenn ich auf https://www.gietart.com/ die Cookies akzeptiere, will er ein Google Tag Manager Script laden. Bei kaltenbach was von "leadlab"

**Comment by TobiasKrais** [comment]
Kannst du kaltenbach.com gerade nochmals versuchen. Ich war am basteln.
Bei Gietart will er bei mir nichts nachladen?!

**Comment by IngoWinter** [comment]
bei kaltenbach.com wird jetzt nichts mehr geladen

**Comment by TobiasKrais** [comment]
![Bildschirmfoto von 2021-05-06 17-53-38](https://user-images.githubusercontent.com/4131072/117328631-1a9fb880-ae94-11eb-9719-b12530538217.png)
Dann muss das am JS Code liegen. Hier der Code als Screenshot.

**Comment by IngoWinter** [comment]
probier <script src="https://c.leadlab.click/schwarzerbalken.js"></script>

**Comment by TobiasKrais** [comment]
Ändert nichts. Es wird nicht mal die `div` mit dem JS Code ausgegeben

**Comment by IngoWinter** [comment]
Es wird im Box Template ausgegeben:
`PHNjcmlwdCBzcmM9Imh0dHBzOi8vYy5sZWFkbGFiLmNsaWNrL2ZkMjg5NTMwMWM5NzY2NzEuanMiPjwvc2NyaXB0Pg==`
Du müsstest dann mal hier und da ein console.log einbauen und gucken, wo er aussteigt. Ich würde hier anfangen: https://github.com/FriendsOfREDAXO/consent_manager/blob/master/assets/consent_manager_frontend.js#L152

**Comment by TobiasKrais** [comment]
Das wird auf der Gietart Seite ausgegeben. Aber auf der Kaltenbach Seite ist nicht mal das der Fall. Der Fehler muss schon vorher sein.

**Comment by IngoWinter** [comment]
Es steht doch base64 codiert im Box Template drin. Viel weiter vorher kann der Fehler nicht sein...

**Comment by TobiasKrais** [comment]
Ich komm der Sache näher. Auf der englischen Seite geht es. Der Fehler muss in dieser Zeile liegen: https://github.com/FriendsOfREDAXO/consent_manager/blob/961eeefb8edbde19ab68a7ef5726b2fa7e4e2e77/lib/consent_manager_frontend.php#L70

**Comment by TobiasKrais** [comment]
Die Ursache ist, dass das Script nur in der Startsprache gespeichert ist, aber aus jeder Sprahe einzeln geladen wird. Damit kann das Script in allen anderen Sprachen außer der Startsprache nicht geladen werden. Der Fix behebt das.

**Comment by TobiasKrais** [comment]
Bin nicht so glücklich mit der Idee den selben Script Code in mehrere Sprache zu kopieren. @aeberhard Darf ich noch nach einer Drittmeinung fragen?

**Comment by IngoWinter** [comment]
@TobiasKrais was wäre denn eine robuste Alternative? Durch das Kopieren (für @aeberhard zur Orientierung [hier](https://github.com/FriendsOfREDAXO/consent_manager/issues/165#issuecomment-834285382) vorgeschlagen) erschlagen wir verlässlich dieses Issue, #97 und #165. 
Mir fällt keine Lösung ein, die nicht wesentlich aufwendiger wäre...

**Comment by TobiasKrais** [comment]
Hmm... Ja, da hast du schon recht. Mir fällt da auch nichts besseres ein.

**Comment by IngoWinter** [comment]
Weiter gehts in #165
