### ISSUE TITLE
Löschen / Ändern der Startsprache löscht alle Cookie Skripte

### ISSUE THREAD

**Issue by TobiasKrais** [FriendsOfREDAXO/consent_manager#165]
Beim Ändern der Startsprache können die Cookie Skripte nicht mehr editiert werden, da das entsprechende Feld in "nicht Startsprachen" deaktiviert ist. Außerdem werden die Scripte nicht mehr ausgelesen, da sie in der Startsprache erwartet werden.

Beim Löschen der ehemaligen Redaxo Startsprache werden die Cookie Scripte sogar gelöscht.

**Comment by IngoWinter** [comment]
Auch wenn die Antwort offensichtlich `Tobias Krais` ist - aber wer macht denn sowas 😆

**Comment by TobiasKrais** [comment]
Ingo, da könntest du sogar recht haben. Die "löschen" Option ist für die Startsprache deaktiviert.

Aber: spinnen wir das Weiter. Es braucht einen Zwischenschritt zum Löschen der Startsprache: wenn man unter System die Prio der Sprachen ändert, wird dadurch die Startsprache geändert. Dann haben wir das Problem, dass die Scripte nicht mehr gefunden werden, weil sie nicht mehr in der Startsprache gespeichert sind. Der Fall dürfe nicht allzu oft vorkommen, ein Bug ist es allemal.

**Comment by IngoWinter** [comment]
Vielleicht an den EP REX_FORM_SAVED hängen und bei jedem Speichern eines Cookies in der Startsprache die Skripte in den anderen Sprachen aktualisieren? Damit wäre dann auch dieses Problem https://github.com/FriendsOfREDAXO/consent_manager/pull/164 gelöst.

**Comment by IngoWinter** [comment]
@TobiasKrais magst du das eben machen? Du bist gerade so schön im Thema drin :)

**Comment by aeberhard** [comment]
Also ich denke auch das es am besten/sichersten ist die Scripte bei Update in alle Sprachen zu kopieren.

**Comment by aeberhard** [comment]
Änderung der Scripte würde ich aber weiterhin nur in der Startsprache ermöglichen.

**Comment by TobiasKrais** [comment]
OK. Ich schau mal, dass ich das programmiere.
