### ISSUE TITLE
Falsche Anzahl Cookies wird angezeigt

### ISSUE THREAD

**Issue by TobiasKrais** [FriendsOfREDAXO/consent_manager#166]
![Bildschirmfoto von 2021-05-07 10-54-32](https://user-images.githubusercontent.com/4131072/117424993-a52ef900-af22-11eb-9d3a-a0406c475235.png)
In bestimmten Fällen wird die falsche Anzahl Cookies angezeigt. Beispielseite: www.kaltenbach.com.

In dieser Zeile werden alle Cookiegruppen UIDs gezählt und ausgegeben. Es wird nicht geprüft, ob es den Cookie auch wirklich gibt:
https://github.com/FriendsOfREDAXO/consent_manager/blob/961eeefb8edbde19ab68a7ef5726b2fa7e4e2e77/fragments/consent_manager_box.php#L40

Bei der Ausgabe der Cookies wird aber vorab geprüft, ob es überhaupt ein Cookie mit der UID gibt: https://github.com/FriendsOfREDAXO/consent_manager/blob/961eeefb8edbde19ab68a7ef5726b2fa7e4e2e77/fragments/consent_manager_box.php#L47
Gibt es ihn nicht, wird er auch nicht ausgegeben. Daher der Unterschied in der Anzahl Cookies.

**Comment by IngoWinter** [comment]
Ich nehme an, du löscht einen Cookie der in einer Cookiegruppe hinterlegt ist. Durch das Löschen wird der Cache nicht neu geschrieben. Probiere mal hier: https://github.com/FriendsOfREDAXO/consent_manager/blob/master/pages/cookie.php#L11 nach dem Löschen des Cookies `consent_manager_cache::write()` aufzurufen

**Comment by TobiasKrais** [comment]
Das Problem ist dadurch leider noch nicht behoben. Die beiden Cookie UIDs der oben genannten Seite sind "consent-manager" und "consent_manager". Korrekt ist die Variante "consent-manager". Die Variante mit dem "_" war der alte Name des Cookies, bevor ich ihn umbenannt hatte. Aber wo der ausgelesen wird ist mir rätselhaft, denn weder in der cookie noch der cookiegroup Tabelle der Datenbank ist diese UID vorhanden.

**Comment by IngoWinter** [comment]
![cm](https://user-images.githubusercontent.com/7223820/117464234-bf7fcb80-af50-11eb-9116-a92e6dd6108a.png)

**Comment by TobiasKrais** [comment]
Nun, den Cookie gibt es bei mir nicht. Er nennt sich consent-manager. Ich kann auch keinen erstellen der consent_manager heißt, da das gegen die Namensconvention verstößt (ein "_" ist im Cookienamen nicht erlaubt).

**Comment by TobiasKrais** [comment]
Aber einmal in der Datenbank alles ändern und dank deines Patches einmal speichern und die Welt ist wieder gut. Danke für den Tipp!

**Comment by TobiasKrais** [comment]
Danke!
