### ISSUE TITLE
Beim Upgrade default Cookie umbenennen

### ISSUE THREAD

**Issue by TobiasKrais** [FriendsOfREDAXO/consent_manager#171]
Beim Upgrade von Version 2 sollte der Standardcookie von iwcc auf consent_manager umbenannt werden.

**Comment by aeberhard** [comment]
Das umbenennen alleine reicht hier nicht. Es muss auch der Name in der Beschreibung angepasst werden.

**Comment by TobiasKrais** [comment]
Gut. Danke für die Info. Habe einen PR erstellt. Falls der OK ist, denkst du es würde sich eine neue beta Version lohnen?

**Comment by aeberhard** [comment]
Ja @TobiasKrais machen wir dann gleich eine beta8.
Danke für dein Testing und deine Korrekturen!

**Comment by aeberhard** [comment]
@TobiasKrais beta8 ist jetzt auch im Installer vorhanden. Kannst gerne testen und Feedback. Dann machen wir eine finale 3.0.0

**Comment by IngoWinter** [comment]
@aeberhard ehe du die finale 3.0.0 machst - was ist denn hiermit: https://github.com/FriendsOfREDAXO/consent_manager/issues/149
