### ISSUE TITLE
Notice: Undefined index: outputcss in redaxo/src/addons/consent_manager/boot.php on line 80

### ISSUE THREAD

**Issue by alexwenz** [FriendsOfREDAXO/consent_manager#172]
Schon wieder ich. Tut mir leid ...

Nach Upgrade von  3.0.0beta6 auf  3.0.0beta7 kommt obige Notice, die dazu führt, dass nix mehr geht. Auch den Cookie löschen, neue Session starten (anderer Browser) bringt keine Änderung.

Redaxo 5.12.0
PHP 7.3.13 
Einstellungen: "Eigenes CSS verwenden" ist aktiv

**Comment by aeberhard** [comment]
@alexwenz kannst Du mal die Git-Version testen. Da sollte das gefixt sein!

**Comment by alexwenz** [comment]
@aeberhard: gerade gemacht. 

Folgender Fehler danach: 

`..../redaxo/src/core/lib/fragment.php

                $this->vars[$name] = $value;
            }
     
            return $this;
        }
     
        /**
         * Parses the variables of the fragment into the file $filename.
         *
         * @param string $filename the filename of the fragment to parse
         *
         * @throws InvalidArgumentException
         * @throws rex_exception
         *
         * @return string
         */
        public function parse($filename)
        {
            if (!is_string($filename)) {
                throw new InvalidArgumentException(sprintf('Expecting $filename to be a string, %s given!', gettype($filename)));
            }
     
            $this->filename = $filename;
     
            foreach (self::$fragmentDirs as $fragDir) {
                $fragment = $fragDir . $filename;
                if (is_readable($fragment)) {
                    $content = rex_timer::measure('Fragment: '.$filename, function () use ($fragment) {
                        ob_start();
                        require $fragment;
                        $output = ob_get_clean();
                        assert(false !== $output);
     
                        return $output;
                    });
     
                    if ($this->decorator) {
                        $this->decorator->setVar('rexDecoratedContent', $content, false);
                        $content = $this->decorator->parse($this->decorator->filename);
                    }

Arguments

    "Expecting $filename to be a string, integer given!"

`

**Comment by aeberhard** [comment]
@alexwenz hast Du auch mal versucht den Cache zu löschen. Bei mir hat das funktioniert.

**Comment by aeberhard** [comment]
@IngoWinter @staabm @gharlan 
Wenn sich Klassen verändern sind die nach einem Update/Installation scheinbar noch alten Klassen im Cache.
Sollte hier ein leeren des Caches durchgeführt werden? Wie ist hier die "übliche" Vorgehensweise?

**Comment by gharlan** [comment]
Bei einem Addon-Update wird bereits der Opcache gelöscht, und das ist ja der Cache, der alten PHP-Code enthalten könnte.

> Wie ist hier die "übliche" Vorgehensweise?

Üblich ist eigentlich, dass man nix machen muss und die Updates korrekt funktionieren, auch bei Änderungen in den Klassen.

Ist denn geklärt, ob Cache löschen bei @alexwenz wirklich hilft (geholfen hat)?

**Comment by aeberhard** [comment]
Ich denke mal dass es daran liegt dass nicht über den Installer upgedated wurde.

**Comment by aeberhard** [comment]
@alexwenz kannst Du mal ein Update mit der Beta8 aus dem Installer probieren!?
@TobiasKrais gerne auch testen :)

**Comment by TobiasKrais** [comment]
Bei Upgrade auf beta8 bekomme ich immernoch den Fehler:
**InvalidArgumentException:** Expecting $filename to be a string, integer given!
**File:** redaxo/src/core/lib/fragment.php
**Line:** 111

<details>
<summary>Stacktrace</summary>

| Function                                     | File                                                                     | Line     |
| -------------------------------------------- | ------------------------------------------------------------------------ | -------- |
| rex_fragment->parse                          | redaxo/src/addons/consent_manager/lib/consent_manager_frontend.php       | 35       |
| consent_manager_frontend::getFragment        | redaxo/cache/addons/templates/4.template                                 | 152      |
| include                                      | rex:///template/2                                                        | 5        |
| require                                      | redaxo/src/addons/structure/plugins/content/lib/article_content_base.php | 405      |
| rex_article_content_base->{closure}          | redaxo/src/core/lib/util/timer.php                                       | 57       |
| rex_timer::measure                           | redaxo/src/addons/structure/plugins/content/lib/article_content_base.php | 406      |
| rex_article_content_base->getArticleTemplate | redaxo/src/addons/structure/plugins/content/boot.php                     | 56       |
| rex_package::{closure}                       | redaxo/src/core/lib/extension.php                                        | 51       |
| rex_extension::{closure}                     | redaxo/src/core/lib/util/timer.php                                       | 57       |
| rex_timer::measure                           | redaxo/src/core/lib/extension.php                                        | 62       |
| rex_extension::registerPoint                 | redaxo/src/core/frontend.php                                             | 26       |
| require                                      | redaxo/src/core/boot.php                                                 | 141      |
| require                                      | index.php                                                                | 9        |

</details>
<details>
<summary>System report (REDAXO 5.12.0, PHP 7.4.19, MySQL 5.7.34)</summary>

| REDAXO        |            |
| ------------: | :--------- |
|       Version | 5.12.0     |


| PHP           |            |
| ------------: | :--------- |
|       Version | 7.4.19     |
|       OPcache | no         |
|        Xdebug | no         |


| Database      |              |
| ------------: | :----------- |
|       Version | MySQL 5.7.34 |
| Character set | utf8         |


| Server        |            |
| ------------: | :--------- |
|            OS | Linux      |
|          SAPI | fpm-fcgi   |
|     Webserver | Apache     |


| Request       |              |
| ------------: | :----------- |
|       Browser | Firefox/88.0 |
|      Protocol | HTTP/2.0     |
|         HTTPS | yes          |


| Packages                                         |             |
| -----------------------------------------------: | :---------- |
|                                     accessdenied | 1.0.6       |
|                                         be_style | 2.12.0      |
|                              be_style/customizer | 2.12.0      |
|                                  be_style/redaxo | 2.12.0      |
|                                  consent_manager | 3.0.0beta8  |
|                                          cronjob | 2.8.0       |
|                                      d2u_address | 1.1.3       |
|                                       d2u_helper | 1.8.4       |
|                    d2u_helper/translation_helper | 1.8.4       |
|                                      d2u_history | 1.0.1       |
|                                         d2u_jobs | 1.2.0       |
|                           d2u_jobs/hr4you_import | 1.2.0       |
|                                      d2u_linkbox | 1.2.4       |
|                                    d2u_machinery | 1.3.5       |
|                   d2u_machinery/industry_sectors | 1.3.5       |
|         d2u_machinery/machine_features_extension | 1.3.5       |
| d2u_machinery/machine_steel_processing_extension | 1.3.5       |
|                      d2u_machinery/used_machines | 1.3.5       |
|                                         d2u_news | 1.1.4       |
|                                   d2u_news/fairs | 1.1.4       |
|                                      d2u_partner | 1.0         |
|                                   d2u_references | 1.0.8       |
|                                        d2u_staff | 1.0.3       |
|                                       d2u_videos | 1.1.0       |
|                                          install | 2.9.0       |
|                                    media_manager | 2.11.0      |
|                        media_manager_autorewrite | 2.0.1       |
|                                        mediapool | 2.10.0      |
|                                         metainfo | 2.8.0       |
|                                  multinewsletter | 3.2.7       |
|                                         osmproxy | 1.5.0       |
|                                        phpmailer | 2.10.1      |
|                                        search_it | 6.7.3       |
|                           search_it/autocomplete | 6.7.3       |
|                          search_it/documentation | 6.7.3       |
|                              search_it/plaintext | 6.7.3       |
|                                  search_it/stats | 6.7.3       |
|                                            sprog | 1.2.0       |
|                                        structure | 2.12.0      |
|                                structure/content | 2.12.0      |
|                                         tinymce4 | 1.2.1       |
|                                         uploader | 2.2.2       |
|                                              url | 2.0.0-beta3 |
|                                            users | 2.8.0       |
|                                             ycom | 4.0.3       |
|                                        ycom/auth | 4.0.3       |
|                                        ycom/docs | 4.0.3       |
|                                       ycom/group | 4.0.3       |
|                                  ycom/media_auth | 4.0.3       |
|                                            yform | 3.4.1       |
|                                       yform/docs | 3.3.1       |
|                                      yform/email | 3.4.1       |
|                                    yform/manager | 3.4.1       |
|                            yform_spam_protection | 1.1.0       |
|                                         yrewrite | 2.7         |
|                                  yrewrite_scheme | 3.4.0       |

</details>

**Comment by staabm** [comment]
@TobiasKrais vermutung: in redaxo/cache/addons/templates/4.template übergibst du einen falschen parameter an consent_manager_frontend::getFragment

**Comment by TobiasKrais** [comment]
Ja, nach dem löschen des Caches ist auch alles wieder gut. Sollten wir in der Update PHP den Cache einmalig löschen, also z.B. bei einem Upgrade von <3 auf 3?

**Comment by staabm** [comment]
Wird beim update von <3 auf 3 irgendwo programatisch ein template verändert?

**Comment by aeberhard** [comment]
Nein beim Update wird kein Template geändert.
Ich habe aber im Fragment einen Parameter rausgenommen.
https://github.com/FriendsOfREDAXO/consent_manager/commit/9411e97557cdf9e8573a9408b195994538b9d415

@TobiasKrais wie sieht denn deine Einbindung im Template aus?

**Comment by aeberhard** [comment]
Ich denke daran liegt es.

lib/consent_manager_frontend.php

`public static function getFragment($debug, $forceCache, $fragmentFilename)  `

wurde geändert in

`public static function getFragment($forceCache, $fragmentFilename)`

**Comment by TobiasKrais** [comment]
Die Einbinung ins Template sieht so aus:
```
if(rex_addon::get('consent_manager')->isAvailable()) {
 	print 'REX_CONSENT_MANAGER[]';
}
```
Siehe https://github.com/TobiasKrais/d2u_helper/blob/e7ab175ad13b5c1ac9d8a79bccd824e0cecaf2d2/templates/04-1/template.php#L136-L138

**Comment by staabm** [comment]
Ahh das erklärt es. Wenn sich die methoden signatur verändert hat und noch alte aufrufe im template cache sind, müsste das addon den cache löschen im migrations-pfad

**Comment by aeberhard** [comment]
@staabm 
meinst Du hier den kompletten Cache löschen? Oder gibt es da eine andere Funktion dazu?

**Comment by staabm** [comment]
@aeberhard da du vermutlich nicht wissen kannst ob der addon verwender die rex var in template oder modul einsetzt würde ich alle csches löschen (ausgenommen medienpool)

**Comment by aeberhard** [comment]
@staabm In der Readme ist beschrieben die REX-Var im Template einzubauen. Das wird auch die überwiegende Verwendung sein denke ich. 

rex_delete_cache() löscht auch den Cache des Medienpools., gibt es eine function nur den Template/PHP-Cache zu löschen?

**Comment by IngoWinter** [comment]
```
<?php
foreach(glob(rex_path::cache().'addons/*') as $path) {
    if (substr($path, -10) == '/mediapool') continue;
    rex_dir::delete($path);
}
?>
```
So in etwa schätze ich.

**Comment by TobiasKrais** [comment]
Aufbauend auf der Idee von Ingo: reicht das hier auch?
```
<?php
if(rex_version::compare(\rex_addon::get('consent_mnager')->getVersion(), '3', '<')) {
    // Delete template cache
    rex_dir::delete(rex_path::cache('addons/templates'));
    // Delete module cache
    rex_addon::get('structure')->clearCache();
}
?>
```

**Comment by alexwenz** [comment]
> @alexwenz kannst Du mal ein Update mit der Beta8 aus dem Installer probieren!?

@aeberhard Entschuldige bitte, war ein paar Tage afk... Wenn ich wieder testen soll, bitte ich um Info

**Comment by aeberhard** [comment]
@alexwenz @TobiasKrais die neue Beta9 ist jetzt im Installer verfügbar.
Jetzt wird der Template+Module-Cache gelöscht. Danke an @TobiasKrais

**Comment by TobiasKrais** [comment]
Beta9 ist getestet. Funktioniert bei mir auf allen Installationen wunderbar! Danke @aeberhard !

**Comment by alexwenz** [comment]
Habe nach Update keine Fehlermeldungen mehr. Vielen Dank!

Auch wenn ich mich jetzt extrem unbeliebt mache: nach dem Update erscheint das Consent Popup aber auch nicht mehr. (Auch im Inkognito-Modus eines bisher nicht verwendeten Browser.)

Sofort nach Rückkehr zur beta6 funktioniert es wieder...

**Comment by TobiasKrais** [comment]
@alexwenz den Fehler kann ich nicht bestätigen. Hier eine funktionierende Beispielseite: https://ingtec.ch/de/

**Comment by aeberhard** [comment]
@alexwenz kann man das mal online sehen?

**Comment by IngoWinter** [comment]
Hier passiert wohl nix mehr.

**Comment by alexwenz** [comment]
Entschuldigt bitte die späte Rückmeldung. Ist viel los gerade. Konnte das Problem lokalisieren: saß vor dem Rechner.

Ich habe auf die neueste Version aktualisiert, meine benutzerdefinierten Fragmentdateien aber scheinbar nicht vollständig korrekt auf den neuen Stand gebracht.

Sorry für die Verwirrung und Danke!!

**Comment by TobiasKrais** [comment]
Steht dann dem finalen Release der Version 3 noch was im Weg?

**Comment by aeberhard** [comment]
Version 3.0 ist jetzt im Installer @TobiasKrais 
Und Danke für deine Unterstützung!

**Comment by TobiasKrais** [comment]
Danke dir für die viele Arbeit in Version 3!
