### ISSUE TITLE
Cookie-Consent-Fenster umgehen per Token

### ISSUE THREAD

**Issue by alxndr-w** [FriendsOfREDAXO/consent_manager#175]
![image](https://user-images.githubusercontent.com/3855487/119261881-99595d00-bbd9-11eb-9cec-3f6c2f949d13.png)

Ich möchte über eine API ein Screenshot der Website anfertigen, leider funkt der Consent-Manager dazwischen. Wäre es möglich, im Consent-Manager einen Token als Get-Paramter übergeben zu können, der den Consent-Manager aushebelt? Dann würde ich mir überlegen, einen PR beizusteuern.

Es gäbe dann 2 Möglichkeiten zur Umsetzung:

1. Es wird kein JS geladen, als wäre der Consent-Manager komplett deaktiviert
2. Der Consent-Manager gibt das JS aus, als wäre bereits eingewilligt.

**Comment by aeberhard** [comment]
@alxndr-w ich würde mich an folgender Stelle reinhängen
https://github.com/FriendsOfREDAXO/consent_manager/blob/b975a37c2b3ff4f0e656dd1b0ee8a15afa2b650b/fragments/consent_manager_box_cssjs.php#L13

Durch setzen von
`$initially_hidden = 'true';`
wird keine Consent-Box ausgegeben

**Comment by aeberhard** [comment]
Da dann z.B. einen Get-Parameter abfragen und $initially_hidden auf TRUE setzen

**Comment by aeberhard** [comment]
@alxndr-w 
Vielleicht sollte man hier ein zusätzliches Einstellungsfeld in der config.php anlegen (Textfeld, "Consent-API-Key")
Und diesen Wert als GetParameter übergeben. Dann könnte nicht jeder über einen festen Parameter die Box umgehen.

z.B.
In den Einstellungen im Textfeld **blafasel99** eingeben
Webseite ohne Box dann z.B.
`domain.de/?consentapi=blafasel99`

Vielleicht ist das aber auch Overkill.

**Comment by alxndr-w** [comment]
Ne, durchaus genau so hätte ich das umgesetzt. Ich werde einen PR beisteuern.

**Comment by aeberhard** [comment]
@alxndr-w Top 👍
