### ISSUE TITLE
In der Hilfe: googlemaps -> google-maps

### ISSUE THREAD

**Issue by ritzfritz** [FriendsOfREDAXO/consent_manager#177]
In der Hilfe steht das Standardbeispiel bei "Scripte mit PHP Laden" mit if ($check['googlemaps']) 

Besser wäre if ($check['google-maps']) (mit Bindestrich)

**Comment by IngoWinter** [comment]
Was spricht gegen einen PR mit einer nachvollziehbaren Begründung für die Änderung?

**Comment by alxndr-w** [comment]
@ritzfritz ich weiß nicht mehr, wie fit du schon mit der GitHub-Weboberfläche bist, aber hier die Reihenfolge, wie du die Datei direkt hier bearbeiten kannst und daraus einen PR machen kannst.

![image](https://user-images.githubusercontent.com/3855487/125106516-066c7780-e0e0-11eb-8c2d-13b1c9658215.png)

**Comment by ritzfritz** [comment]
Grüß Dich Andreas,

klar weißt Du, wie fit ich bei GitHub bin: Ich habe keine Ahnung.

Zumindest bis vor 5 Minuten.

Mit Deiner genialen Anleitung, die ich mir gleich gespeichert habe, habe ich hoffentlich einen richtigen PullRequest gestartet.

Danke Dir wieder mal recht sakrisch!!!

Ich wünsch Dir ein schönes Wochenende!

Grussitos

ritzfritz

Von: Alexander Walther ***@***.***>
Gesendet: Freitag, 9. Juli 2021 18:04
An: FriendsOfREDAXO/consent_manager ***@***.***>
Cc: Fritz Ritzinger ***@***.***>; Mention ***@***.***>
Betreff: Re: [FriendsOfREDAXO/consent_manager] In der Hilfe: googlemaps -> google-maps (#177)


@ritzfritz<https://github.com/ritzfritz> ich weiß nicht mehr, wie fit du schon mit der GitHub-Weboberfläche bist, aber hier die Reihenfolge, wie du die Datei direkt hier bearbeiten kannst und daraus einen PR machen kannst.

[image]<https://user-images.githubusercontent.com/3855487/125106516-066c7780-e0e0-11eb-8c2d-13b1c9658215.png>

**Comment by ritzfritz** [comment]
Grüß Dich Ingo,

Andreas Walther hat mir noch mal eine geniale Anleitung geschickt, wie ich das mache.
Hoffentlich passt das so.

So kann ich da hoffentlich öfter mal mithelfen, was schon lang mein Wunsch ist.

BTW: Bitte entferne doch den Slack-Channel „fürfritz“. Der macht die Sache unübersichtlich.

Danke Dir auf alle Fälle für den Hinweis.

Ich wünsche Dir ein schönes Wochenende!

Grussitos

ritzfritz

Von: Ingo Winter ***@***.***>
Gesendet: Freitag, 9. Juli 2021 15:05
An: FriendsOfREDAXO/consent_manager ***@***.***>
Cc: Fritz Ritzinger ***@***.***>; Author ***@***.***>
Betreff: Re: [FriendsOfREDAXO/consent_manager] In der Hilfe: googlemaps -> google-maps (#177)


Was spricht gegen einen PR mit einer nachvollziehbaren Begründung für die Änderung?

**Comment by IngoWinter** [comment]
Astrein Franz 👍 
https://github.com/FriendsOfREDAXO/consent_manager/pull/178
