### ISSUE TITLE
Root-Domain mit Pfad > Domain-Eingabe nicht möglich

### ISSUE THREAD

**Issue by bitshiftersgmbh** [FriendsOfREDAXO/consent_manager#180]
Moin.

Wir haben hier ein Projekt, bei dem einzelne Marken als Directory an die Domain angehängt werden (www.xyz.de/brand1). Das ist definitiv nicht änderbar - soviel vorweg. Die Domains sind im YRewrite alle angelegt und nach einigen anderen Umbauten läuft das alles auch sauber.

Nun wäre der CM einzustellen. Das Eingeben einer Domain mit Pfad wird allerdings verweigert (`Domain bitte im Format **meinedomain.de** eingeben`). Wäre das leicht zu ändern oder zieht das Kreise?

**Comment by alxndr-w** [comment]
Schon probiert, es über die db zu ändern und zu schauen, was passiert?

**Comment by bitshiftersgmbh** [comment]
> Schon probiert, es über die db zu ändern und zu schauen, was passiert?

Bin heut zu durch. Wird morgen früh versucht. Danke für den Tipp!

**Comment by bitshiftersgmbh** [comment]
Man muss noch diverse Fragmente anpassen, die mit Domains jonglieren und `$_SERVER['HTTP_HOST']` dafür nutzen. Wenn man das macht plus die DB-Anpassung der Domain läuft es aber.

**Comment by alxndr-w** [comment]
PR?

**Comment by bitshiftersgmbh** [comment]
Geht nicht. Hab es für meine konkreten Bedürfnisse jetzt auf YRewrite umgeschrieben. Das müsste man ja optional einbauen und einen Fallback liefern, falls einer eben kein YRewrite hat/nutzt oder dort keine (passenden) Entries angelegt hat. Das ist nicht irre viel Aufwand, aber mir fehlt aktuell die Zeit selbst für so kleine Dinge (Baby, Projekte, dies das).
