### ISSUE TITLE
Bug: Sprog auf "isActivated" testen anstatt "isInstalled"

### ISSUE THREAD

**Issue by iceman-fx** [FriendsOfREDAXO/consent_manager#182]
Wenn man Sprog zwar installiert aber deaktiviert hat, kommt es zu einem PHP-Fehler und das CM-Fenster wird nicht angezeigt.

Grund:
Zeile 101 in consent_manager_frontend.php

`if (rex_addon::get('sprog')->isInstalled()) {`

Hier wäre es besser auf Aktiv zu prüfen anstatt auf Installiert.

**Comment by ynamite** [comment]
@alxndr-w öhm ... was hab ich nochmal mit diesem Issue zu tun? 😅

**Comment by alxndr-w** [comment]
Sorry, falsch verlinkt. Heute ist mein Kopf falsch verdrahtet.
