### ISSUE TITLE
Session Start vermeiden, wenn aktuell nicht benötigt

### ISSUE THREAD

**Issue by skerbis** [FriendsOfREDAXO/consent_manager#188]
Das AddOn startet eine PHP Session auch auf Seiten wo kein Consent benötigt wird. 
(z.B. eine weitere Domain) 

https://github.com/FriendsOfREDAXO/consent_manager/blob/6bb22942e0029f8b56fd73b9b3b7e2f9da3e2e17/boot.php#L60-L68

**Comment by aeberhard** [comment]
@skerbis 
Das kann man doch über das Template entsprechend so gestalten dass der Consent nur auf den "gewünschten" Seiten eingebunden wird.
Sehe ich nicht als Bug :)

**Comment by IngoWinter** [comment]
Man müsste an der Stelle prüfen, ob die aktuelle Domain eine der im Consent Manager angelegten ist

**Comment by aeberhard** [comment]
@alxndr-w da hast Du völlig Recht!
Kann mal jemand den PR gegenchecken? Bei mir hat es im Test funktioniert. REX_CONSENT_MANAGER[] zb. nur bei bestimmter Kategorie im Template ausgeben.
