### ISSUE TITLE
Buttonfarbe nicht unterschiedlich lt. aktuellen Vorgaben/-empfehlungen von Datenschützern

### ISSUE THREAD

**Issue by iceman-fx** [FriendsOfREDAXO/consent_manager#194]
Beide Buttons (Auswahl bestätigen + Alles auswählen) sollten die gleiche Farbgebung haben.
Kein Button darf besonders hervorstechen.

**Comment by IngoWinter** [comment]
Mach gerne einen PR

**Comment by iceman-fx** [comment]
Macht Ihr mal als Projektlead.
Das geht bei Euch schneller, eh ich mich hier in das Thema PR eingearbeitet habe.

**Comment by alxndr-w** [comment]
@iceman-fx „Macht Ihr Mal“ – ehrlich? Ist die Zeit der Projekt-Leads weniger wert als deine?

**Comment by alxndr-w** [comment]
Extra für dich in 3 Klicks rausgesucht: https://github.com/FriendsOfREDAXO/consent_manager/edit/master/assets/consent_manager_frontend.css

**Comment by iceman-fx** [comment]
@alxndr-w deine Sprüche kannste dir sparen.
Ich muss hier auch keine Vorschläge mehr machen.

Wenn die es mit 3 Klicks so schnell rausgesucht hast, dann hättest du es ja auch selber machen können.
