### ISSUE TITLE
Interesse an anderen Styles?

### ISSUE THREAD

**Issue by tbaddade** [FriendsOfREDAXO/consent_manager#195]
Besteht für das AddOn Interesse andere Styles mitzuliefern? 

Ich hatte vor kurzem das hier umgesetzt: 

- Checkbox als Switch
- Markup ist gleich geblieben

### Ohne Details
<img width="1081" alt="Bildschirmfoto 2021-11-10 um 15 59 42" src="https://user-images.githubusercontent.com/338267/141137738-cfee86bc-4239-4dec-851c-c69a4ced2aa2.png">

### Mit Details
<img width="1080" alt="Bildschirmfoto 2021-11-10 um 16 04 50" src="https://user-images.githubusercontent.com/338267/141137852-dbb95179-6d71-4508-8f93-70da6e2aff32.png">

**Comment by olien** [comment]
Immer!

**Comment by aeberhard** [comment]
Klar! Evtl. kann man das dann sogar Auswählbar machen.
Popup unten, unten rechts usw. wäre noch interessant.

**Comment by olien** [comment]
Oh Mann. Das hier hatte ich total vergessen. Hätte mir die Arbeit sparen können... ;-(

**Comment by aeberhard** [comment]
@tbaddade kannst dein SCSS gerne hier einstellen oder mir schicken.
Bastle gerade daran Themes für das Popup einzubauen

**Comment by aeberhard** [comment]
Closed mit #262
