### ISSUE TITLE
REX_CONSENT_MANAGER[] bindet CSS/JS nicht mehr ein

### ISSUE THREAD

**Issue by TobiasKrais** [FriendsOfREDAXO/consent_manager#197]
... sondern schreibt es lediglich in die Session.

**Comment by aeberhard** [comment]
Hi Tobias, Du hattest das doch getestet!? @TobiasKrais

**Comment by TobiasKrais** [comment]
Ja, ist mir nicht aufgefallen. Problematisch ist meiner Ansicht nach, dass die boot.php vor dem Ersetzen der Variable aufgerufen wird. Wenn die Sessionvariablen vorhanden sind läuft - soweit ich das bis jetzt analysiert habe - alles wie gewünscht. So war das bei meinem Test. Aber wenn die Sessionvariablen noch nicht gefüllt sind, gibt es Probleme.

**Comment by aeberhard** [comment]
@TobiasKrais an welcher Position im Template hast du denn den ConsentManager drin?
Eher oben im Head oder weiter unten?
Irgendwie werden die Sessions unterschiedlich behandelt abhängig von PHP-Version/Server.

**Comment by TobiasKrais** [comment]
Am Ende des head Tags. Hier der Code: https://github.com/TobiasKrais/d2u_helper/blob/bf457e6ab35d610aca2eb67a69b2916d8b236f11/templates/04-1/template.php#L136-L138

**Comment by IngoWinter** [comment]
Wenn `REX_CONSENT_MANAGER[]` funktioniert wie REX_ARTICLE oder REX_VALUE, dann kann dein Code nicht funktionieren oder? Die Dinger werden doch ersetzt, bevor PHP ausgeführt wird.

**Comment by IngoWinter** [comment]
Es kann ja eigentlich nur das hier sein: https://github.com/FriendsOfREDAXO/consent_manager/commit/a5fddc9149ae560e0433ee930c82665aae5f6ef1

**Comment by TobiasKrais** [comment]
@IngoWinter: Die Ersetzung erfolgt immer korrekt. Der Code nach der Ersetzung ist dieser:
`/* REX_CONSENT_MANAGER[] */ consent_manager_frontend::getFragment(0, 'consent_manager_box_cssjs.php');`
In dem aufgerufenen Fragment erfolgt aber keine Ausgabe mehr. Hier wird der Text für CSS und JS nur in die Session geschrieben. Diese Daten sollten dann in der boot.php ausgelesen und ausgegeben werden. Das Problem ist aber, dass die boot.php die Ausgabe regelt bevor die Session Parameter über die Ersetzung gefüllt werden.

**Comment by TobiasKrais** [comment]
Ich merke gerade: die Ersetzung kann ja auch nicht wirklich erfolgreich sein. Folgender Text soll ersetzt werden:
`$_search = '<!--REX_CONSENT_MANAGER_OUTPUT[]-->';`
(siehe https://github.com/FriendsOfREDAXO/consent_manager/blob/20ff63c13e2e51228207b6b6456b9a5429e9f8ad/boot.php#L64). Diesen Text gibt es aber nicht.

**Comment by TobiasKrais** [comment]
Dieser HTML Kommentar sollte eigentlich am Ende des Fragmentes ausgegeben werden:
https://github.com/FriendsOfREDAXO/consent_manager/blob/20ff63c13e2e51228207b6b6456b9a5429e9f8ad/fragments/consent_manager_box_cssjs.php#L48
Aber in meinem Quelltext der Seite ist er nicht vorhanden und kann auch nicht ersetzt werden.

**Comment by aeberhard** [comment]
@TobiasKrais doch der Text wird ausgegeben. Dass er nicht mehr in deinem Quelltext zu sehen ist liegt daran dass er durch '' ersetzt wurde.

Das mit den Sessions ist scheinbar von Server/PHP-Version abhängig da bei mir (auf Windows mit Xampp immer alles klappt, auch bei meinen Seiten bei Hetzner)

Es liegt an der boot.php und der Reihenfolge der EP's. Bin hier noch am versuchen!

**Comment by TobiasKrais** [comment]
Warum lassen wir die Ausgabe eigentlich nicht im Fragment?

**Comment by aeberhard** [comment]
@ynamite @TobiasKrais @marcohanke 
Evtl. schaffe ich es heute spät abends eine überarbeitete Version bereitzustellen

**Comment by TobiasKrais** [comment]
Danke für deine Mühe! Werde gerne testen.

**Comment by aeberhard** [comment]
@ynamite @TobiasKrais @marcohanke
Wäre super wenn Ihr mal testen könnt. :)
https://github.com/aeberhard/consent_manager

@marcohanke Fix für das Script-Eingabefeld ist auch dabei.

Danke euch!

**Comment by marcohanke** [comment]
@aeberhard Kann ich nicht bestätigen. Ich hab consent_manager mit deinen Daten überschrieben und reinstalliert. Anzeige passt trotzdem nicht.

**Comment by TobiasKrais** [comment]
Auf einer Installation in der Version 3.0.2 NICHT funktioniert hatte, läuft mit deiner Entwicklerversion alles perfekt. Dateien hochgeladen, reinstalliert und gut.

Auf einer zweiten Installation, in der die Version 3.0.2 tadellos lief, bekomme ich mit der Entwicklerversion von dir in der Browserconsole den Fehler, dass das Skript nicht geladen werden kann:
![Bildschirmfoto von 2021-11-19 10-07-45](https://user-images.githubusercontent.com/4131072/142596097-8f303e7c-6405-42d9-a328-e405dd71cdef.png)
Aber: rufe ich die URL des Skripts im Browser auf, wird es korrekt geladen?!

**Comment by DagmarU** [comment]
Hallo,
ich habe auch das Problem, dass das Banner nicht mehr erscheint (3.0.1 und 3.0.2). Provider: all-inkl. Im Vivaldi wird mir folgende Fehlermeldung angezeigt:

Uncaught SyntaxError: Unexpected token ','
index.php?consent_manager_outputjs=1&clang=1&v=16370618291:2 

Es bezieht sich auf diese Zeile:
/* --- Parameters --- */
var consent_manager_parameters = {initially_hidden: , domain: "xxx", consentid: "xxx", cachelogid: 

Das Banner erscheint lange Zeit gar nicht und dann, wenn man mehrere Seiten aufgerufen hat, ganz unvermittelt.
Ich hoffe, das hilft euch weiter.

**Comment by marcohanke** [comment]
Skerbes hatte das auch. Das problem ist aus meiner Sicht dass `initially_hidden` leer ist.
Mal so ne Frage, habt ihr vielleicht alle kein jquery laufen?

**Comment by DagmarU** [comment]
jQuery 3.6.0. 
Die vorherigen Consent-Versionen liefen problemos. Ich habe allerdings die Datei consent_manager_box.php modifiziert, um die Optik zu beeinflussen. Dort habe ich zwei Container auskommentiert. Das kann doch keinen Einfluss haben.

**Comment by IngoWinter** [comment]
Der Consent Manager läuft ohne jQuery. Die zwei Aufrufe haben sich aus Versehen eingeschlichen und sind mit https://github.com/FriendsOfREDAXO/consent_manager/pull/202 wieder raus.

**Comment by marcohanke** [comment]
Danke Ingo, hatte ich gesehen, wusste aber nicht wann es sich eingeschlichen hat und da der PR noch nicht gemerged ist dachte ich vielleicht hängts da.

**Comment by marcohanke** [comment]
@DagmarU Dann schmeiß doch dein Fragment noch mal raus und test es um es auszuschließen

**Comment by DagmarU** [comment]
Ich habe den fragments-Ordner gelöscht. Das hatte keinen Effekt. Dann habe ich das Addon gelöscht und die Version 3.0.2 über den Installer neu hochgeladen und installiert. Auch jetzt kommt das Cookie-Banner nicht und Vivaldi zeigt immer noch den Fehler Uncaught SyntaxError: Unexpected token ',' ...
Ein Update bei Hetzner funktionierte problemlos.

**Comment by aeberhard** [comment]
@DagmarU @TobiasKrais @ynamite @marcohanke @skerbis 

Wäre super wenn Ihr mal die überarbeitete Version testen könnt wenn ihr Zeit habt. ;-)
Besonderer Dank an @TobiasKrais und @skerbis !

**https://github.com/aeberhard/consent_manager**

@marcohanke schau noch mal wegen dem Eingabefeld für die Scripte bei den Cookies.

Danke euch!

**Comment by marcohanke** [comment]
Kurz getestet, das mit den Eingabefeldern passt jetzt. Danke dir!

**Comment by skerbis** [comment]
Getestet LGTM 👍🏻

**Comment by TobiasKrais** [comment]
Auch von mir getestet und grünes Licht für die Änderungen. Danke @aeberhard

**Comment by ynamite** [comment]
Samesame, getestet und funzt, sogar mit Subdomain :)

**Comment by aeberhard** [comment]
Super Danke euch! Werde dann heute eine neue Version in den Installer laden.

**Comment by DagmarU** [comment]
Es funktioniert wieder. 
Ganz herzlichen Dank für deine Arbeit!

**Comment by aeberhard** [comment]
Behoben mit 8e3d17167ce41e3221c4299efe12d3c0dd032f0e
