### ISSUE TITLE
Nach Update auf 3.0.2 Fehler 500

### ISSUE THREAD

**Issue by olien** [FriendsOfREDAXO/consent_manager#198]
![image](https://user-images.githubusercontent.com/330516/142183968-db8f69a7-13f2-4fad-bcb3-0e4d81211e04.png)

Alles andere ist auch aktuell (REDAXO 5.13 aber es geht auch nicht mit REDAXO 5.12.x)

**Comment by olien** [comment]
Muss etwas geändert werden nach dem Update?

**Comment by IngoWinter** [comment]
Ich denke mal, ist das gleiche Problem wie hier https://github.com/FriendsOfREDAXO/consent_manager/issues/197
Falls doch nicht gerne wieder aufmachen.
