### ISSUE TITLE
3.0.2 funktioniert mit Beispiel-Config nicht, Version 3.0.0 auch nicht

### ISSUE THREAD

**Issue by ynamite** [FriendsOfREDAXO/consent_manager#199]
hatte Version 3.0.2 installiert, Beispiel-Config importiert, Code in Template eingefügt (PHP-Variante) UND ... nichts.
Ausser einem JS Fehler in der Konsole geschieht nix.  
`Uncaught SyntaxError: expected expression, got ','`

Mit cookie_consent Version 3.0.0 erhalte ich hingegen folgende Meldung in der Konsole:
`Addon consent_manager: Keine Cookie-Gruppen / Cookies ausgewählt bzw. keine Domain zugewiesen!`
Domain ist eingefügt und bei den Cookies ausgewählt ...

Was verpasse ich?

**Comment by ynamite** [comment]
Ich hatte statt Subdoman nur Domain angegeben. 

Nun erscheint zwar der Dialog, aber die Auswahl wird nicht gespeichert und bei jedem Seitenaufruf erneut angezeigt.

**Comment by aeberhard** [comment]
@ynamite steht was im REDAXO-Logfile? Bei einem SQL-Fehler beim speichern müsste da eigentlich was erscheinen.
Bin gerade dran an #197 mit vieel Debug-Ausgabe im Log und habe das Problem lokalisiert denke ich.

@ynamite @marcohanke @TobiasKrais Wenn Ihr Verbesserungsvorschläge für die Hilfe habt dann nur her damit oder einfach rein damit :)
Evtl. kann man auch einige "Misskonfigurationen" abhandeln und evtl. eine Meldung im Consent-Manager ausgeben.

**Comment by ynamite** [comment]
@aeberhard speichert das Addon die Auswahl der Cookies, die man im Frontend akzeptiert, in die DB? Im Backend werden die Einstellungen schon gespeichert, nur für den Fall das wir uns missverstehen. Ich schau sonst morgen mal ins Log. 

Tobias meinte, dass er das so noch nie gehabt hätte. Gut möglich, dass es an meiner Konfiguration liegt.

**Comment by aeberhard** [comment]
Jo, die werden in der Tabelle `rex_consent_manager_consent_log` gespeichert.
Und das Cookie 'consent_manager' wird im Browser für 1 Jahr angelegt.
Die consentid aus dem Cookie muss auch in der Tabelle stehen.

**Comment by ynamite** [comment]
@aeberhard hab nun ins Log gekuckt und die DB-Tabelle gecheckt. Log bleibt leer, keine Fehler und in der DB ist der Eintrag vorhanden und zwar wie folgt:
```
INSERT INTO `rex_consent_manager_consent_log` (`id`, `domain`, `consentid`, `consents`, `cachelogid`, `ip`, `createdate`) VALUES
(7,	'dev.domain.com',	'619619fa924d22.91406135',	'[\"phpsessid\",\"consent_manager\"]',	'',	'83.150.XXX.XXX',	'2021-11-18 10:16:46');
```
Scheint also korrekt zu sein, trotzdem wird der Dialog nach jedem Reload angezeigt ... komisch.

**Comment by ynamite** [comment]
Konnte das Problem soeben lösen, kann aber nicht genau sagen wieso.
Was ich gemacht habe:

hatte Debug-Modus aktiv

1. Debug-Modus deaktiviert
2. Cache gelöscht
3. voilà
4. dann Debug-Modus wieder aktiv -> geht immer noch

Also keine Ahnung. Irgendetwas mit Cache/Debug-Modus scheinbar.

**Comment by aeberhard** [comment]
und dev.domain.com ist beim Consent-Manager eingetragen?

**Comment by aeberhard** [comment]
Ah. Der insert in die Datenbank wird per Ajax ausgelöst. evtl. hakt es da irgendwie im Debug-Modus

**Comment by ynamite** [comment]
@aeberhard dev. Domain ist eingetragen ja und der DB Insert scheint auch im Debug-Modus zu gehen, nur wird das Cookie bei mir im Debug-Modus nicht dauerhaft gesetzt bzw. ist beim nächsten Reload wieder weg.

**Comment by ynamite** [comment]
Sobald der Debug-Modus inaktiv ist, klappt es.
