### ISSUE TITLE
Doku in Redaxo 5.13.0 Fehlerhaft

### ISSUE THREAD

**Issue by marcohanke** [FriendsOfREDAXO/consent_manager#201]
In der aktuellen Redaxo Version  sieht der Beispielcode für die PHP Einwilligung so aus:
![Bildschirmfoto 2021-11-17 um 21 43 43](https://user-images.githubusercontent.com/2425981/142279366-1277f0a2-23cd-4348-837a-ebf18e086e3a.png)

**Comment by aeberhard** [comment]
Du meinst die README im Dark-Mode in der 5.13? 
Ist ja eine .md-Datei, evtl. ist das auch bei anderen Addons so?
Sind die anderen Code-Beispiele korrekt?

**Comment by marcohanke** [comment]
Moin,
ich habs gerade noch mal getestet und es ist strange.
Auch in einer frischen Installation das gleiche verhalten. Egal ob theme:null,dark oder light.
Code der bei dir in der Readme mit 3Backticks+php eingebunden ist wird so angezeigt wie oben.
Ich hab z.B. mal bei Globale Einstellungen geschaut. Dort wird in der Readme auch Code mit 3Backtiks+PHP eingebunden und dort passt es.

**Comment by gharlan** [comment]
Neu ist in R5.13 das Highlighting von PHP-Code in den Readmes. Schon möglich, dass es da noch Bugs drin gibt.

**Comment by marcohanke** [comment]
Komisch nur dass consentManager readme.php Zeile 101 falsch angezeigt wird, GlobalSettings Readme Zeile 32 aber funktioniert.

**Comment by aeberhard** [comment]
Kannst Du da evtl. über den Inspector Unterschiede feststellen?
**3Backticks+php != 3Backtiks+PHP ?**
GrossKleinschreibung?

**Comment by marcohanke** [comment]
Das war ein Tipfehler von mir.
conseontmanager.
```php

globalsettings
```php

**Comment by gharlan** [comment]
Das ist ein Problem in der AntiXSS-Lib, die wir verwenden: https://github.com/voku/anti-xss/issues/85
(Wobei das Problem erst im Zusammenhang mit dem PHP-Highlighting auftritt, deswegen erst seit 5.13.)

**Comment by gharlan** [comment]
Ich habe eine provisorischen Workaround erstellt: https://github.com/redaxo/redaxo/pull/4935

**Comment by aeberhard** [comment]
@marcohanke klappt das mit Gregors Workaround?

**Comment by gharlan** [comment]
Der Workaround ist doch nicht nötig, da es einen allgemeinen Fix in der AntiXSS-Lib gab. Ist in 5.13.1 enthalten.

**Comment by marcohanke** [comment]
@aeberhard Gregor war schneller. Es läuft alles ohne zutun.
