### ISSUE TITLE
Beispiel "Skripte mit PHP laden"

### ISSUE THREAD

**Issue by MC-PMOE** [FriendsOfREDAXO/consent_manager#203]
Im Moment sieht das Beispiel folgendermaßen aus:
```
$arr = json_decode($_COOKIE['consent_manager'], true);
$check = [];
if ($arr)
{
$check = array_flip($arr['consents']);
}
#dump($arr);
if ($check['google-maps']) {
  // Code Ausgabe bei akzeptierter CookieGruppe
  // GoogleMaps-Code
} else {
  // Code Ausgabe bei abgelehnter CookieGruppe
  // Warnhinweis + <a class="consent_manager-show-box-reload">Cookie Einstellungen bearbeiten</a>
}
```

Wäre es nicht einfacher und übersichtlicher mit in_array() zu prüfen?

```
$arr = json_decode($_COOKIE['consent_manager'], true);
if ( in_array('google-maps', $arr['consents']) ) {
  // Code Ausgabe bei akzeptierter CookieGruppe
  // GoogleMaps-Code
} else {
  // Code Ausgabe bei abgelehnter CookieGruppe
  // Warnhinweis + <a class="consent_manager-show-box-reload">Cookie Einstellungen bearbeiten</a>
}
```
Außerdem scheint das Beispiel in manchen Situationen Probleme zu machen, hatte testweise den Google Map Cookie von "externe Medien" in "Notwendige" geschoben.
mit array_flip bekam ich dann 'google-maps' => 0 was bei der Prüfung if ($check['google-maps']) natürlich fehlschlug.

**Comment by IngoWinter** [comment]
Wenn du es vernünftig machen möchtest, könntest du die Klasse consent_manager_frontend um eine Methode `isConsented($key)` oder was in der Richtung ergänzen. Habe ich schon länger auf dem Zettel https://github.com/FriendsOfREDAXO/consent_manager/issues/99, bin aber irgendwie nie dazu gekommen :)

**Comment by MC-PMOE** [comment]
Fände ich auch gut, eine Objektklasse die Information zum aktuellen "consent" der Domain hält und entweder direkt oder über API zur Laufzeit abgerufen werden kann. Meinst du das so in der Art?
Man  könnte die rex_api_consent_manager dazu erweitern, dass ein Parameter function_type oderso übergeben werden kann, der dann entsprechend die gewünschte Funktion auslöst.
Um keine breaking changes zu verursachen könnte auch bei fehlen des Parameters dieser per default "log" sein um die bisherige Logfunktion auszulösen.

**Comment by IngoWinter** [comment]
Ich meine sowas wie
```
if (consent_manager_frontend::isConsented('google-maps')) {
  // Code Ausgabe bei akzeptierter CookieGruppe
  // GoogleMaps-Code
} else {
  // Code Ausgabe bei abgelehnter CookieGruppe
  // Warnhinweis + <a class="consent_manager-show-box-reload">Cookie Einstellungen bearbeiten</a>
}
```
Sprich dieses ganze json_decode/flip/in_array Geraffel in eine Funktion packen, die true/false zurückgibt. Ob die Frontend Klasse dafür der passende Ort ist oder man lieber eine neue Klasse dafür macht oder eine Funktion oder ein REX_VAR Dingens weiss ich nicht. Vielleicht haben @aeberhard oder @TobiasKrais da noch ne Meinung zu. Von @skerbis weiss ich, dass er heiss auf REX_VAR ist :)

**Comment by aeberhard** [comment]
Eine function die true/false liefert wäre super. Denke am besten wäre da eine eigene Klasse in der man dann diverse
verschiedene functions ablegen kann.

z.B.
`consent_manager_util::isConsent('google-maps')`

@MC-PMOE Phillip gerne einen PR dazu :)

**Comment by aeberhard** [comment]
@MC-PMOE https://github.com/FriendsOfREDAXO/consent_manager/blob/1b27ee2e948fa454d1ea57438507b0934b1d7d91/lib/consent_manager_util.php#L3

**Comment by aeberhard** [comment]
Ich mache dann hier mal zu
