### ISSUE TITLE
Skripte, die nach Ablehnung geladen werden

### ISSUE THREAD

**Issue by MC-PMOE** [FriendsOfREDAXO/consent_manager#204]
Es wäre cool wenn es neben den Skripten die nach Einverständnis geladen werden auch die Möglichkeit gäbe Skripte nach Ablehnung zu laden (als clean up z.B.).
Beispiel wäre bei mir aktuell, dass ich Mapbox erst nach Zustimmung laden lasse. Wenn zugestimmt wird packt Mapbox 2 Einträge in den localStorage. Wird jetzt im nachhinein die Cookie Präferenz geändert und externe Medien ausgeschaltet, würde ich gerne via localStorage.removeItem diese Einträge wieder entfernen.

**Comment by IngoWinter** [comment]
Das Löschen von Cookies oder Webstorage Einträgen ist nicht notwendig (und bringt auch keinem was). Jede zusätzliche Zeile Code macht das Addon komplexer, fehleranfälliger und pflegeintensiver. Deswegen bin ich gegen eine solche Erweiterung.

**Comment by MC-PMOE** [comment]
> Das Löschen von Cookies oder Webstorage Einträgen ist nicht notwendig (und bringt auch keinem was)

War mir so nicht bewusst, dachte es könnte Probleme geben wenn trotz Ablehnung derartiges zurückbleibt

> Jede zusätzliche Zeile Code macht das Addon komplexer, fehleranfälliger und pflegeintensiver

Das stimmt wohl, könnte dann natürlich um Komplexität zu vermeiden auch hiermit gelöst werden #156 falls sich andere spezielle Anwendungsfälle ergeben und ist vermutlich auch besser als den auszuführenden Code mit in die Cookie Definition zu packen.
