### ISSUE TITLE
Anzahl der Cookies

### ISSUE THREAD

**Issue by marcohanke** [FriendsOfREDAXO/consent_manager#207]
Ich habe eine Cookie angelegt und in der yaml folgendes:
-
 name: _ga
 time: "2 Jahre"
 desc: "Speichert für jeden Besucher der Website eine anonyme ID. Anhand der ID können Seitenaufrufe einem Besucher zugeordnet werden."
-
 name: _gat
 time: "1 Tag"
 desc: "Verhindert, dass in zu schneller Folge Daten an den Analytics Server übertragen werden."
-
 name: _gid
 time: "1 Tag"
 desc: "Speichert für jeden Besucher der Website eine anonyme ID. Anhand der ID können Seitenaufrufe einem Besucher zugeordnet werden."

Der Counter in der Cookiehistory bleibt trotzdem auf 1 weil nur 1 Cookie angelegt ist.
Wie ist hier denn BestPractice? 3 einezlne Cookies anlegen? Wo pack ich dann den TagManagerCode rein einfach in eines davon? Irgendwie komisch oder? Könnte man nicht die Sektionen in der Yaml zählen?

**Comment by aeberhard** [comment]
Ich verstehe die Frage nicht :)

**Comment by marcohanke** [comment]
Ich hab von IWCC aktualisiert. Dort hatte ich 1 Cookie angelegt mit dem GoogleGedöns. Hier werden aber 3 Cookies angelegt. Am Ende sieht das aktuell so aus:
![Bildschirmfoto 2021-12-13 um 21 04 21](https://user-images.githubusercontent.com/2425981/145880552-e6e6fd28-36be-4ef4-868e-743629d6bdde.png)

Ich müsste also 3 3 Einträge aus der  yaml auszählen.

Ich habe ja nur einen Code vom Google Tag Manager. Da ist es doch auch quatsch 3 Cookies anzulegen. Jetzt besser?

**Comment by aeberhard** [comment]
Ah jetzt verstehen :) Du meinst Statistik **(1)** <=

Hier wird gezählt wie viele Cookies der Gruppe zugeordnet sind.

Und ja, eigentlich sollte dann für jedes Cookie ein eigener Eintrag angelegt werden.

**Comment by marcohanke** [comment]
Versteh' ich theoretisch und wie mache ich das praktisch wenn ich nur einen Code für den TagManager habe? 3 Cookies anlegen, 2 ohne Script und eins mit? Ist doch auch komisch oder?

**Comment by IngoWinter** [comment]
Die Zahl in Klammern zeigt die Anzahl der "Dienste" an, denen zugestimmt wird. Wenn du unter "Statistik" also Google Analytics und Matomo drin hast, würde da eine 2 stehen. In der Beschreibung zu "Statistik" könntest du diese 2 nennen und erläutern. Die per yaml angelegten Cookie Definitionen zu zählen, halte ich für nicht sinnvoll.
Google Tag Manager ist ein Dienst mit x Cookiedefinitionen.

**Comment by IngoWinter** [comment]
Vielleicht sollte man die Reiter im Backend mal umbenennen:

Cookie Gruppen -> Gruppen
Cookies -> Dienste
Cookie Texte -> Texte

Dann wäre man von dieser Cookie Schiene mal runter. Dann könnte man auch die Mustertexte beim Setup umschreiben, so dass nciht mehr von Cookies sondern von Consent die Rede ist.

**Comment by marcohanke** [comment]
@IngoWinter Das finde ich spontan eine gute Idee! Es geht ja nicht nur um Cookies sondern um Consents im allgemeinen. Wenn das gewünscht ist, könnte ich das übernehmen.

**Comment by IngoWinter** [comment]
Von mir aus ist das gewünscht :)
