### ISSUE TITLE
Hinweis ausgeben wenn 404-Page und Startseite identisch sind

### ISSUE THREAD

**Issue by aeberhard** [FriendsOfREDAXO/consent_manager#208]
Sind 404-Page und Startseite identisch dann wird kein Popup ausgegeben.

Sollte hier im Backend eine Warnung ausgegeben werden wie folgt: ??

![image](https://user-images.githubusercontent.com/330560/144486903-5fb48e45-6e7d-4f71-9b96-dbb7a9a8578e.png)

**Comment by aeberhard** [comment]
Siehe #206

**Comment by IngoWinter** [comment]
Von mir aus reicht der Hinweis in der Readme dicke. Man braucht nicht jeden schrägen Anwenderfehler per Code abfangen :)

**Comment by IngoWinter** [comment]
Warum passen wir hier nicht die Abfrage dahingehen an, dass auf der Startseite **immer** die Box angezeigt wird?
https://github.com/FriendsOfREDAXO/consent_manager/blob/master/boot.php#L76

**Comment by IngoWinter** [comment]
Mir sagt ja nie einer was :grin:
https://github.com/FriendsOfREDAXO/consent_manager/pull/212

**Comment by aeberhard** [comment]
https://github.com/FriendsOfREDAXO/consent_manager/commit/3a38571aa3b78f98b93ba13a29bd6634075767b1 sollte das Problem fixen.
Daher hier close
