### ISSUE TITLE
Nach Update auf 3.0.3 wird Cookiebanner nicht mehr angezeigt

### ISSUE THREAD

**Issue by iceman-fx** [FriendsOfREDAXO/consent_manager#209]
Habe soeben bei zwei Webseiten den CM auf 3.0.3  angehoben.
Mit der 3.0.2 wurde das Banner noch angezeigt aber mit der 3.0.3 nun nicht mehr.

An den Einstellungen/Einbindungen wurde nichts geändert.
Cache wurde testweise auch mal geleert - ohne Erfolg.

**Comment by alxndr-w** [comment]
Wird das Addon noch aktiv supportet?

**Comment by IngoWinter** [comment]
@alxndr-w haste heute morgen nen Troll gefrühstückt oder was?

**Comment by aeberhard** [comment]
@iceman-fx Nur auf der Startseite? Dann setze mal eine 404 unterschiedlich zur Startseite.

**Comment by iceman-fx** [comment]
@aeberhard Mit unterschiedlicher 404-Seite ging es.

**Comment by IngoWinter** [comment]
Wer hätte gedacht, dass der Consent Manager die Leuts dazu bringt, ihre Seite vernünftig einzurichten. Jeden Tag eine gute Tat :)

**Comment by iceman-fx** [comment]
Und wieder ein vollig sinnfreier und unnötiger Beitrag vom Webseiten Gott @IngoWinter

**Comment by IngoWinter** [comment]
Warum antwortest du auf sinnfreie und unnötige Beiträge ;)
