### ISSUE TITLE
Die Kennung der Skript-Container ist nicht eindeutig.

### ISSUE THREAD

**Issue by DanielWeitenauer** [FriendsOfREDAXO/consent_manager#210]
Da `data-uid` sowohl für die Kennung der Checkboxen im Popup, als auch der Skript-Container verwendet wird, werden Skripte nicht korrekt initialisiert, wenn ein Cookie die gleich ID verwendet wie eine Cookiegruppe. In diesem Fall wird versucht, die Daten aus dem entsprechenden Input-Element und nicht aus dem passenden DIV zu lesen.
Ich hatte z.B. Gruppe und Cookie mit dem Schlüssel `google-tag-manager` versehen.

Die Elemente sollten hier über eindeutigere Attribute ausgelesen werden:
https://github.com/FriendsOfREDAXO/consent_manager/blob/fa48c3b0df32724e711346210941a6547eb3105c/assets/consent_manager_frontend.js#L115

**Comment by aeberhard** [comment]
Ich mache hier mal zu @DanielWeitenauer
