### ISSUE TITLE
Google Tag Assistant Legacy; Optimierung

### ISSUE THREAD

**Issue by shauste** [FriendsOfREDAXO/consent_manager#211]
Google Tag Assistant Legacy moniert folgendes:
`<script» tag must not be included in a <div>` und `GTM JavaScript code not found as a direct child of the <head> tag`.
<img width="422" alt="gtal" src="https://user-images.githubusercontent.com/4592113/145421121-5894682e-212d-4c4a-a245-7d68083b4ddd.png">

**Comment by IngoWinter** [comment]
Welche Konsequenzen hat dieses monieren? Und was ist deine Frage?

**Comment by shauste** [comment]
Die Konsequenzen scheinen nur kosmetischer Natur und beeinflussen nach meinen Tests nicht die Funktionsweise. Mir geht es um eine valide Einbindung, daher nur als „Question“.

**Comment by IngoWinter** [comment]
Afaik kann das script Element überall eingesetzt werden, sprich valide im Sinne von W3C ist es. Siehe auch https://developer.mozilla.org/en-US/docs/Web/HTML/Element/script

Wenn du Google glücklich machen möchtest, kannst du den Consent per PHP abfragen und die GTM Skripte an der gewünschten Stelle im Template ausgeben.

**Comment by aeberhard** [comment]
Ich mache hier mal zu :)
