### ISSUE TITLE
CookieHistory lädt nicht neu beim Sprachwechsel

### ISSUE THREAD

**Issue by marcohanke** [FriendsOfREDAXO/consent_manager#213]
Ruft man die Seite Cookiehistory auf und wechselt danach die Sprachversion der Website bleibt der Ursprungstext erhalten. Erst nach einem Reload der Seite wird der Cookietext auf die neue sprache aktualisiert.
Wenn man sich durch mehrere Sprachen klickt hängt dadurch der Text immer eine Sprache hinterher.

**Comment by aeberhard** [comment]
@marcohanke kannst Du mal die aktuelle Github-Version testen!?

**Comment by marcohanke** [comment]
@aeberhard Github Version reingepackt, reinstalliert, cache gelöscht. Gleiches Problem.

**Comment by aeberhard** [comment]
@marcohanke magst Du die 'aktuelle' 3.0.4 direkt aus git nochmal probieren!?
Das Problem sollte eigentlich behoben sein, bei mir funktioniert das ganze.

**Comment by aeberhard** [comment]
@marcohanke bitte noch mal die aktuelle direkt aus git versuchen!
@TobiasKrais @skerbis Gerne auch testen :)
Danke euch!
Die Session ist jetzt aus dem consent_manager entfernt. Der Script-Aufruf hat sich geändert, wieder über index.php. 
Cache löschen!

**Comment by TobiasKrais** [comment]
Getestet. Die gewohnte Funktionalität ist gewährleistet.

Von der Cookiehistorie hab ich keine Ahnung. Wie komm ich an die ran?

**Comment by aeberhard** [comment]
@TobiasKrais da kommst Du über den Adminer drauf!

**Comment by TobiasKrais** [comment]
OK. Ich muss also im adminer die Tabelle rex_consent_manager_consent_log öffnen und in einem anderen Tab des Browsers das Frontend der Webseite. Wenn ich dann die Sprache wechsle war der Cookiedialog in der falschen Sprache. So wie ich das sehe ist er jetzt in der richtigen Sprache. :-)

**Comment by marcohanke** [comment]
@aeberhard Ich hab mit der aktuellen Githubversion - reinstalliert, cache gelöscht - nach wie vor das gleiche Problem. Die Sprache hängt eins hinterher.

**Comment by aeberhard** [comment]
@marcohanke hast Du das schon mit drin!? https://github.com/FriendsOfREDAXO/consent_manager/commit/a0ac9212ca9f6c341c01bb43cc64a92b8f2f6b9b

Die anderen Sprachen sind auch gepflegt/vorhanden?

**Comment by marcohanke** [comment]
@aeberhard Ja, sind beide drin und ja, sprachen sind definitiv angelegt (haben vorher auch funktioniert). Sowohl cach als auch texts haben die deutschen Texte drin.
Ich hab jetzt mal einen Text bearbeitet und gespeichert, damit gehts. Sollte man beim Install den entsprechenden Cache löschen?

**Comment by marcohanke** [comment]
Problem erkannt gefahr gebannt. Ich hab die Github Version reingezogen und reinstalliert. Dabei wird der Cache nicht gelöscht. Bei der Installation über den Installer läuft alles.
