### ISSUE TITLE
consent manager ändert andere Session-Einträge

### ISSUE THREAD

**Issue by oioix** [FriendsOfREDAXO/consent_manager#215]
Ich bin auf ein ziemlich schrägen Bug in Version 3.0.3 gestoßen.

Für eine Website mit Login-Bereich und einer "ReturnTo"-Funktion wird auf manchen besuchten Artikeln die aktuell besuchte Url in einer Session-Variable innerhalb der REX-FE-Sessions zwischengespeichert, damit geeignete Artikel bei einem Re-Login wieder direkt ohne Umwege gehen zu müssen besucht werden. 
Beispiel: 
Variablen-Name (Beispiel): save_as_return_topath
Gespeicherter Wert (Beispiel): **de/mypage/thissubpage/**

Diese Session-Variable "save_as_return_topath", welche überhaupt nichts mit dem consent manager zu tun hat und den Pfad einer besuchten Seite beinhaltet, wird durch den Abschnitt ab Zeile 66 in der boot.php des consent_manager-Addons einfach abgeändert. Und zwar hängt der consent_manager an den vorgenannten gespeicherten Beispiel-Pfad des "returnto"-Session-Eintrages **de/mypage/thissubpage/** drei Parameter an, so dass dann fälschlicherweise z.B. folgendes gespeichert ist:
**de/mypage/thissubpage/?consent_manager_outputjs=1&amp;amp;clang=1&amp;amp;v=1639444247**

Wie die fremde Session heißt spielt bei dem Bug keine Rolle. Ich habe diverse Namen ausprobiert. Immer der gleiche Effekt.
Offenbar wird durch das searchreplace im EP der boot.php jeder aktuelle in einer Session gespeicherte Pfad erkannt und einfach mit den consent_manager-Parametern als Anhängsel zwangsbeglückt.

NACHTRAG:
Wie ich gerade feststelle überschreibt der consent_manager hier insbesondere auch an die Url angehängte GET-Variablen. 

UND NOCH EINEN NACHTRAG:
Bin gerade wieder zu der zuletzt installierten Version 3.0.1 zurückgekehrt. Da ist alles bestens. Der Bug muss also auf einer Änderung der boot.php in Version 3.0.2 oder in 3.0.3 beruhen.

**Comment by aeberhard** [comment]
@oioix Hallo Chris, die aktuelle github-Version sollte das Problem nicht mehr haben.
Kannst Du das evtl. bestätigen!? Danke!

**Comment by oioix** [comment]
Hi, 
danke, dass du dich dem Problem annimmst.

Leider besteht das Problem weiterhin. 
Es gab ja vorher auch diverse Sessioneinträge, welche eindeutig zum [consent_manager] gehörten. Die sind jetzt zwar verschwunden, aber das Problem, dass fremde Session-Einträge verändert werden, bleibt nach wie vor.

Ich hänge mal zwei aktuelle Screenshots an, die das Problem zeigen (mit der github-Version es Addons).

![Screenshot 2022-01-03 | 16 57 15](https://user-images.githubusercontent.com/75900789/147956679-c7c0c445-0f55-4aed-b4d4-3c8f4ff6799c.jpg)

![Screenshot 2022-01-03 | 16 57 45](https://user-images.githubusercontent.com/75900789/147956524-2f185cd7-3e91-407f-af38-f407cdff661f.jpg)

Der erste zeigt die Situation, dass der Sessioneintrag gerade frisch gespeichert, also "clean" ist.
Nach einem Wechsel auf eine Seite, die selbst keine Session schreibt, also nichts daran ändert, kann man sehen, dass consent_manager in zwei fremde(!) Sessioneinträge geschrieben hat (hier in den Eintrag [x_return_to][url] und [x_return_to][art_params]).

Offenbar läuft da eine Art Filter über die Sessions und erkennt, dass da eine Url ist und hängt sich einfach dran. Anders kann ich mir das nicht erklären. 
Das erklärt allerdings nicht warum auch [x_return_to][art_params] => 
geändert wurde.

Jedenfalls ist es so, dass man - wenn das "return to" dann beim login abgefragt wird, ungewollt das JavaScript anstelle einer html-Seite angezeigt bekommt.







Zum Vergleich mit der alten Version 3.0.1, die das Problem ja noch nicht hatte, hänge ich auch hier noch einen 3. Screenshot an. Habe ich im Anschluss an den Test gemacht, nachdem ich 3.0.1 wieder reaktiviert hatte:

![Screenshot 2022-01-03 | 17 23 48](https://user-images.githubusercontent.com/75900789/147956569-15da097a-38b9-4446-bcb1-b4bf1408c036.jpg)

**Comment by aeberhard** [comment]
Hallo Chris,
ja der consent_manager schreibt jetzt keine Session mehr. Irgendwie gibt es da einen Zusammenhang zwischen ycom und dem OUTPUT_FILTER. Im consent_manager gibt es jetzt auch den Replace nicht mehr.

[x_return_to][art_params] enthält die Parameter aus [url] (ab dem Fragezeichen)

Kannst Du mal folgendes in der boot.php ganz unten 

`rex_extension::register('OUTPUT_FILTER'`

ändern in
`rex_extension::register('FE_OUTPUT'`

also nur `OUTPUT_FILTER` durch `FE_OUTPUT` ersetzen und testen

**Comment by oioix** [comment]
Hi,
an den Output filter hatte ich auch gedacht, aber schade, dieser Versuch hat es leider nicht gebracht.

Ich habe ein php-Script geschrieben, um das Problem zu untersuchen und hatte mich auch an einem Workaround versucht. Ich poste es hier.

Damit kannst du es selbst austesten. Kopiere einfach das Script so wie es ist in die boot.php des project addons. Wenn "debug" an ist, und du im BE eingeloggt bist, sollten über dem HTML-Inhalt der besuchten Seite zwei Dump-Fenster, die die "return to" Session einmal vor und einmal nach dem Schreiben eines neuen "return to"-Eintrags anzeigen. Außerdem wird zur Orientierung worum es gerade geht noch etwas helfender Hinweistext ausgegeben.

Der Fehler wird erst erkennbar, wenn man auf eine Seite geht, die selbst keinen neuen "return to"-Eintrag schreibt, also ausgeschlossen ist. Daher sollten im Aussschluss-Array zwei, drei Artikel-IDs festgelegt werden, die dann nicht für ein "return to" gespeichert werden. Das könnte z.B. die Login-Seite sein (genau da wird bei mir dann dummerweise die JavaScript vom Consent-Manager im Browser ausgegeben).

Mit "reset" kannst du die "return to" Sessions des Tests wieder löschen und von vorne anfangen ohen andere Session-Einträge zurücksetzten zu müssen.

Für die "return to"-Funktion braucht es eigentlich nur einen Session-Eintrag. 
Ich hatte versucht, ob ich das Problem umgehen kann, indem ich die eventuellen GET-Variablen einer besuchten Seite bei Seitenaufruf auslese, in einen eigenen Session-Eintrag zwischenspeichere und dann, wenn ich das "return to" wieder brauche, die ursprüngliche Url wieder zusammensetzte. Aber wie man hier bei tests sehen kann, gelingt auch das nicht, da diese GET-Parameter vom Consent manager überschrieben werden. Diesen Workaround-Versuch habe ich im Script gelassen. Ich hoffe das verwirrt nicht. Er kann Ein/Aus-geschaltet werden. Wenn er an ist, werden statt nur einer Session Variable, welche die gesamte Url enthält eben 4 aufsplittende Variablen zur Zwischenspeicherung geschrieben.

Die "return-to"-Funktion mit einer Session-Variable (also ohne workaround) funktioniert mit dem consent manager <= 3.0.1 einwandfrei.

Irgendetwas muss danach geändert worden sein, was zu diesem seltsamen Effekt führt.
Meine Installation läuft übrigens auf REX 5.13.1.


`
class bugCheck {

		public static function checkSession () {
		
		
		// AN | AUS
		$debug 	= 1;
		
		// reset löscht die Sessions wieder!
		// WENN, DANN Nur einmal anschalten, die Seiten aufrufen und dann wieder ausschalten
		$reset = 0;

		
		// Artikel (IDs), die keinen "return to"-Session-Eintrag schreiben (also wenn dann nur lesen)
		// Wird so ein Artikel dann besucht, muss hier in der Session ein sauberer "return to"-Session-Eintrag 
		// einer zuvor besuchten Seite mitsamt deren eventuellen GET-Parameter stehen für die das letzte "return to" 
		// gespeichert werden sollte
		$excludeArtIDsAry = array('1','2');
		
		
		/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
		
		$printOut = '';
		// Wie ist die Aktuelle Article ID
		$curArticleID 	= rex_article::getCurrentId();
		
		$rexInstNameFE = rex::getProperty('instname');
		
		

		/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
		/// START TRY WORKAROUND - BUG consent manager 3.0.3 =>  ////////////////////////////////////////////////////////////
		
		/* 	TRY WORKAROUND FOR CONSENT-MANAGER 3.0.3 
			Der Constent-Manager 3.0.3 (evtl. auch 3.0.2) greift über einen Extension-Point auf die Session-Einträge zu und 
			überschreibt Return-To-Pfade und auch GET-Variablen, die an eine URL angehängt sind.
			Dieser Workaround könnte die Consent-Manager-Variable herausfiltern, aber nicht verhindern, dass consent manager
			hier auch GET-Variablen von Urls überschreibt.
			
			Da es Fälle gibt, wo die URL aus SEO-Gründen künstlich erzeugt wird, also nicht immer mit einer echten Article-ID 
			hinterlegt sind, kann nicht auf die Article ID als return-to-Wert zurückgegriffen werden. Wir müssen also die Url 
			auswerten können!
			
			Zur alten CM-Version 3.0.1 zurückgekehrt! 
			Vorsorglich diesen Workaround-Test aber behalten. Vielleicht brauchen wir ihn noch einmal.
		*/
		
		// ANS / AUS (AUS = normaler "return-to" Modus)
		$useWorkaround 	= 0;
		
		
		$curUrl = rex_escape(strip_tags($_SERVER['REQUEST_URI']));
		
		// has the current url any params attached? if so extract them
		$urlEpxAry =  explode('?',$curUrl);
		$urlAttachedParams = $urlEpxAry[1];
		
		$consentVarA = rex_escape(strip_tags($_GET['consent_manager_outputjs']));
		$consentVarB = rex_escape(strip_tags($_GET['clang']));
		$consentVarC = rex_escape(strip_tags($_GET['v']));
		
		// the idea
		// we clean the attached parameters and later reatach those that ehem
		if($useWorkaround) {
			$search = 'consent_manager_outputjs='.$consentVarA.'&amp;clang='.$consentVarB.'&amp;v='.$consentVarC;
			$replace = 'consent_stripped_for_returnto=1';
		
			$curUrl = str_replace($search , $replace , $curUrl);
		
			$replace = '';
			$urlAttachedParams = str_replace($search , $replace , $urlAttachedParams);
		}
		/// END TRY WORKAROUND BUG consent manager 3.0.3 => TRY WORKAROUND //////////////////////////////////////////////////
		/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
		if(rex::isFrontend()) {
			// Wenn Artikel "return-to"-excluded ...
			// DEBUG ONLY
			if($debug == 1 && in_array($curArticleID, $excludeArtIDsAry)) {
			
				echo 'DIESER ARTIKEL IST IN DER "RETURN TO"-AUSSCHLUSSLISTE. DIESER ARTIKEL SCHREIBT KEINEN NEUEN "RETURN TO"-EINTRAG ! <br>
					  D.h. es sollte jetzt im ersten DUMP-Feld die korrekte Url der zuletzt eingetragenen "return to"-Seite aus der Session stehen.<br><br>';
			
			}
		
			// Wenn Artikel "return-to"-excluded ...
			// DEBUG ONLY
			if($debug == 1) {
			
				echo 'DUMP => Das wurde bei Aufruf des Artikels gerade aus der Session ausgelesen. Es wurde noch kein neues "return-to" in die Session geschrieben.<br>';
				dump($_SESSION[$rexInstNameFE]['test_return_to']);
			
			}
		
			// Wenn nicht "return-to"-excluded ...
			// die aktuelle Seite in eine Session-Variable schreiben, damit diese nach einem (erneuten) Login mitsamt GET-VAriablen
			// und auch ei einer künstlich erzeugen Url ausgelesen werden kann
			if(!in_array($curArticleID, $excludeArtIDsAry) && rex::isFrontend()) {
			
				if($debug == 1)  echo 'DIESER ARTIKEL SCHREIBT JETZT IN DIE "RETURN TO"-SESSION ! <br>';
			
				// STANDARD
				$_SESSION[$rexInstNameFE]['test_return_to']['url'] 			= $curUrl;						// full url
			
			
				// NEU START SESSION ENTRIES OR TRY WORKAROUND ONLY ! -----------------------------------------------------------
				if($useWorkaround) {
					$_SESSION[$rexInstNameFE]['test_return_to']['art_id'] 		= $curArticleID;				// article id 	(for debug purposes only)
					$_SESSION[$rexInstNameFE]['test_return_to']['art_params'] 	= $urlAttachedParams;			// url GET-vars (for debug purposes only)
					$_SESSION[$rexInstNameFE]['test_return_to']['clang_id'] 	= rex_clang::getCurrentId();	// clang id  	(for debug purposes only)
				}
				// END NEU WORKAROUND -------------------------------------------------------------------------------------------
			}
		
			if($debug == 1) {
				// DEBUG ONLY
				echo 'DUMP => Das wurde geschrieben.';
				dump($_SESSION[$rexInstNameFE]['test_return_to']);
			}
		
			// RESET 
			if($reset) {
				unset($_SESSION[$rexInstNameFE]['test_return_to']);
			}
		}
	}
}
		
		
/// FUNKTION EINBINDEN (WEGEN AKTUELLER ART-ID) /////////////////////////////////////////////////////////////////////////////
rex_extension::register('PACKAGES_INCLUDED', static function (rex_extension_point $ep) {

	// returnTo => kontinuierlich die Url der jeweils aktuell besuchte Seite merken
	(new bugCheck)->checkSession();
	
},rex_extension::LATE);`

**Comment by oioix** [comment]
Sorry, das php Script hatte ich vor dem Post hier leicht angepasst und dabei wohl irgendwo einen Fehler eingebaut.

Bitte die folgende Version nehmen. Die funktioniert mit 3.0.1. wunderbar. 
Die Ausschluss-Artikel-IDs bitte anpassen.


`class bugCheck {

	public static function checkSession () {
		
		
		// AN | AUS
		$debug 	= 1;
		
		// reset löscht die Sessions wieder!
		// WENN, DANN Nur einmal anschalten, die Seiten aufrufen und dann wieder ausschalten
		$reset = 0;

		
		// Artikel (IDs), die keinen "return to"-Session-Eintrag schreiben (also wenn dann nur lesen)
		// Wird so ein Artikel dann besucht, muss hier in der Session ein sauberer "return to"-Session-Eintrag 
		// einer zuvor besuchten Seite mitsamt deren eventuellen GET-Parameter stehen für die das letzte "return to" 
		// gespeichert werden sollte
		
		$excludeArtIDs 		= '1,74,75,80,81,84,80,81,14,82,85,86,87,88,89,3,108';
		
		$excludeArtIDsAry = explode(',',$excludeArtIDs); // Komma-separierte Liste => Array konvertieren
		
		/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
		
		$printOut = '';
		// Wie ist die Aktuelle Article ID
		//$curArticleID 	= rex_article::getCurrentId();
		$curArticleID 	= rex_article::getCurrent()->getId();
		
		$rexInstNameFE = rex::getProperty('instname');
		
		$curUrl = rex_escape(strip_tags($_SERVER['REQUEST_URI']));
		
		
		// Wenn Artikel "return-to"-excluded ...
		if(rex::isFrontend()) {
			// DEBUG ONLY
			if($debug == 1 && in_array($curArticleID, $excludeArtIDsAry)) {
				echo 'DIESER ARTIKEL IST IN DER "RETURN TO"-AUSSCHLUSSLISTE. DIESER ARTIKEL SCHREIBT KEINEN NEUEN "RETURN TO"-EINTRAG !<br>
					  D.h. es sollte jetzt im ersten DUMP-Feld die korrekte Url der zuletzt eingetragenen "return to"-Seite aus der Session stehen.<br>';
			}
		
			// DEBUG ONLY
			if($debug == 1) {
				echo 'DUMP => Das wurde bei Aufruf des Artikels gerade aus der Session ausgelesen. Es wurde noch kein neues "return-to" in die Session geschrieben.';
				dump($_SESSION[$rexInstNameFE]['test_return_to']);
			}
		}

		/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
		/// START TRY WORKAROUND - BUG consent manager 3.0.3 =>  ////////////////////////////////////////////////////////////
		
		/* 	TRY WORKAROUND FOR CONSENT-MANAGER 3.0.3 
			Der Constent-Manager 3.0.3 (evtl. auch 3.0.2) greift über einen Extension-Point auf die Session-Einträge zu und 
			überschreibt Return-To-Pfade und auch GET-Variablen, die an eine URL angehängt sind.
			Dieser Workaround könnte die Consent-Manager-Variable herausfiltern, aber nicht verhindern, dass consent manager
			hier auch GET-Variablen von Urls überschreibt.
			
			Da es Fälle gibt, wo die URL aus SEO-Gründen künstlich erzeugt wird, also nicht immer mit einer echten Article-ID 
			hinterlegt sind, kann nicht auf die Article ID als return-to-Wert zurückgegriffen werden. Wir müssen also die Url 
			auswerten können!
			
			Zur alten CM-Version 3.0.1 zurückgekehrt! 
			Vorsorglich diesen Workaround-Test aber behalten. Vielleicht brauchen wir ihn noch einmal.
		*/
		
		// ANS / AUS (AUS = normaler "return-to" Modus)
		$useWorkaround 	= 0;
		
		
		// has the current url any params attached? if so extract them
		$urlEpxAry =  explode('?',$curUrl);
		$urlAttachedParams = $urlEpxAry[1];
		
		$consentVarA = rex_escape(strip_tags($_GET['consent_manager_outputjs']));
		$consentVarB = rex_escape(strip_tags($_GET['clang']));
		$consentVarC = rex_escape(strip_tags($_GET['v']));
		
		// the idea
		// we clean the attached parameters and later reatach those that ehem
		if($useWorkaround) {
			$search = 'consent_manager_outputjs='.$consentVarA.'&amp;clang='.$consentVarB.'&amp;v='.$consentVarC;
			$replace = 'consent_stripped_for_returnto=1';
		
			$curUrl = str_replace($search , $replace , $curUrl);
		
			$replace = '';
			$urlAttachedParams = str_replace($search , $replace , $urlAttachedParams);
		}
		/// END TRY WORKAROUND BUG consent manager 3.0.3 => TRY WORKAROUND //////////////////////////////////////////////////
		/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
		

		if(rex::isFrontend()) {
			// Wenn nicht excluded ...
			// die Aktuelle Seite in eine Session-Variable schreiben, damit diese nach einem (erneuten)Login ausgelesen werden kann
			if(!in_array($curArticleID, $excludeArtIDsAry)) {
			
				if($debug == 1) 
				echo 'JETZT SCHREIBT DIESER ARTIKEL  ['.$curArticleID.'] IN DIE SESSION ! <br>';
			
				$rexInstNameFE = rex::getProperty('instname');
			
				// ALT
				$_SESSION[$rexInstNameFE]['test_return_to'] = [];
			
				// NEU
				$_SESSION[$rexInstNameFE]['test_return_to']['url'] 		= $curUrl;						// full url 	(we use this only at login)
				$_SESSION[$rexInstNameFE]['test_return_to']['art_id'] 	= $curArticleID;				// article id 	(for debug purposes only)
				$_SESSION[$rexInstNameFE]['test_return_to']['art_params'] = $urlAttachedParams;			// url GET-vars (for debug purposes only)
				$_SESSION[$rexInstNameFE]['test_return_to']['clang_id'] 	= rex_clang::getCurrentId();// clang id  	(for debug purposes only)
			
			}
			else {
				if($debug == 1)
				echo 'DIESER ARTIKEL ['.$curArticleID.'] DARF KEINE SESSION SCHREIBEN ! <br>';
			
			}
		
			if($debug == 1) {
				// DEBUG ONLY
				echo 'Das steht jetzt in der Session.';
				dump($_SESSION[$rexInstNameFE]['test_return_to']);
			}
		}
	}
}
		
		
/// FUNKTION EINBINDEN (WEGEN AKTUELLER ART-ID) /////////////////////////////////////////////////////////////////////////////
rex_extension::register('PACKAGES_INCLUDED', static function (rex_extension_point $ep) {

	// returnTo => kontinuierlich die Url der jeweils aktuell besuchte Seite merken
	(new bugCheck)->checkSession();
	
},rex_extension::LATE);`

**Comment by aeberhard** [comment]
Hallo Chris,
das bringt nix da ich das alles nicht nachvollziehen kann.
Woher kommt die Session mit dem return_to ... ??

**Comment by aeberhard** [comment]
Der consent_manager ändert übrigens nicht die anderen Session-Einträge.
Session ist jetzt komplett entfernt. Man müsste an der Stelle schauen wo die Session erstellt wird.

**Comment by oioix** [comment]
Das Script bildet eine Login-Prozedur mit einer "return-to"-Erinnerungsfunktion nach.

Hintergrund:
Du surfst auf einer Seite umher oder bekommst einen Link mit einer Url zugeschickt, die GET-Parameter beinhaltet.
Um geschützten Inhalt sehen zu können, musst du dich aber in manchen fällen erst einmal einloggen. Also gehts du bzw. landest du auf die/auf der Seite Login. 
Nach dem Login wirst du automatisch an die zuletzt besuchte Seite geleitet. Damit das funktioniert, wird das in einer Session-Variablen gespeichert.
Gleiches gilt, wenn du bereits eingeloggt warst, aber ausgeloggt wirst. Du loggst die wieder ein und landest wieder dort, wo du zuletzt warst.

Das Script schreibt die aktuell besuchte Url mitsamt GET-Parameter in eine Session-Variable. Auf jeder Seite wird die Variable neu beschrieben, außer auf Artikeln, die davon vom Programmierer ausgenommen wurden (dump 2 im Script).
Wird nun die Login-Seite besucht, liest diese die zuletzt gespeicherte Seite ausgelesen und nach dem Login geladen (dump 1 im Script).

Das Problem ist, dass dump 1 durch den consent manager ab 3.0.2 zerstört wird.

Ich verstehe ohnehin nicht, warum der consent manager überhaut GET parameter an eine URL hängt, die dann ein Javascript im Klartext auf den Bildschirm lädt, anstatt die html-Seite. Wozu muss denn jemals ein JS auf dem Screen dargestellt werden?

**Comment by aeberhard** [comment]
Schau mal in den Quellcode deiner Seite

```
<style>.consent_manager-background{position:fixed ...</style>
<script src="?consent_manager_outputjs=1&clang=1&a=1&i=false&h=false&cid=34&v=3&t=1639424921" id="consent_manager_script" defer></script>
```

Das ist in REDAXO üblich Assets wie CSS oder JavaScript auch über die index.php auszuliefern. Auch im Backend z.B..

Wenn das ganze "return_to-Gedöns" über ein eigenes Script von Dir abgehandelt wird, dann musst Du da mal nachschauen :)

Das Script wird nicht im "Screen" geladen.

Verwendest Du einen Extension-Point um die Session-Werte zu speichern?

Der wird evtl. öfter aufgerufen.

1. beim Aufruf deiner Seite
2. beim Aufruf des consent-manager-Scriptes

**Comment by aeberhard** [comment]
Du überschreibst beim 2. Aufruf selbst deine Session-Werte!

**Comment by oioix** [comment]
Ja, Funktion, welches die Session schreibt, wird in meinem Addon in der boot.php aufgerufen.
Nein es ist in der Produktionsumgebung nicht das gleiche Script, sondern ein eigenes Login Script, welches dann die Session bei Bedarf wieder ausliest.

Nein es wird auch in dem Test Script nichts doppelt geschrieben, was man mit Consent-Manager 3..0.1 auch sehr gut sehen und auch prüfen kann.
Besuchst du mit 3.0.1 eine schreibende Seite, wird zuerst der alten gespeicherten Wert vor Aufruf der Url in dump 1 ausgelesen und anzeigt, dann wird 1x geschrieben und dann hier im dump 2 zu prüfzwecke das gerade geschriebene in dump 2 nochmal ausgelesen und  angezeigt. Also 3 Schritte: LESEN (alter Zustand) - SCHREIBEN - NOCHMAL LESEN (neuer Zustand). 
Erst bei einem Reload der gleichen Seite sind dump 1 und dump 2 logischerweise gleich. Es wird im Testscript nur einmal geschrieben, aber zweimal ausgelesen (vor und nach dem schreiben).

Wie gesagt, das Problem besteht erst seit Consent Manager 3.0.2.
Die Return To Funktion gibt es schon seit über einem Jahr und sie funktionierte bis einschliesslich 3.0.1 immer super zuverlässig.

**Comment by oioix** [comment]
Hab den Quellcode geprüft:
Einzig Consent manager fängt mit  "/index.php?..." an.
`    <script src="/index.php?consent_manager_outputjs=1&amp;clang=1&amp;v=16399377081" id="consent_manager_script" defer></script>`

Alle anderen fangen so an:
`<script src="/assets/bootstrap-4.5.0/js/....`

Das JS vom consent manager wird über die index.php ausgeliefert. Da ist wohl irgendwo und irgendwie der Haken.
Warum eigentlich? das JS liegt doch eigentlich auch in assets/addons/constent_manager/

**Comment by oioix** [comment]
Hi Andreas,

wie es aussieht, hast du die Fehlerstelle aufgedeckt.

Du hast gestern geschrieben, dass die JS in Redaxo üblicherweise so eingebunden wird:
`<script src="?consent_manager_outputjs=1&clang=1&a=1&i=false&h=false&cid=34&v=3&t=1639424921" id="consent_manager_script" defer></script>`

Ich hab darauf geantwortet, dass ich den Quelltext geprüft habe und dass es bei mir so aussieht:
`<script src="/index.php?consent_manager_outputjs=1&amp;clang=1&amp;v=16399377081" id="consent_manager_script" defer></script>`

Heute  Morgen wache ich auf und das Erste, was mir in den Sinn kommt, ist, dass es da einen kleinen Unterschied gibt.
Ich hatte gestern nämlich die alte Version 3.0.1 installiert, als ich in den Quellcode schaute.
Und nun in der neueren Version fehlt beim Aufruf der JS offenbar das "**/index.php**" vor dem Fragezeichen, was in 3.0.1 noch da war.
Das ist auch eine Erklärung, warum das JS als GET-Parameter an alle besuchten URLs angehängt wird und andere GET-Parameter die ein Url eventuell hat überschrieben werden.

Also habe ich in der github Testversion 3.0.4 gerade eben die Stelle gesucht, wo der Link geschrieben wird und habe in der Datei consent_manager_box_cssjs.php in Zeile 45 das "**/index.php**" vor dem Fragezeichen hinzugefügt. 
Und siehe da, der Spuk scheint tatsächlich weg zu sein.

Zeile 45 sieht jetzt also so aus:
`$consentparams['outputjs'] .= '    <script src="/index.php?consent_manager_outputjs=1&clang=' . $consentparams['clang'] . '&a=' . $consentparams['article'] . '&i=' . $consentparams['initially_hidden'] . '&h=' . $consentparams['hidescrollbar'] . '&cid=' . $consentparams['cachelogid'] . '&v=' . $consentparams['version'] . '&t=' . filemtime($addon->getAssetsPath('consent_manager_frontend.js')) . '" id="consent_manager_script" defer></script>' . PHP_EOL;`

Ich lass jetzt mal auf der Entwicklungsumgebung 3.0.4 installiert und warte mal ab, ob das Problem damit wirklich weg ist.

**Comment by aeberhard** [comment]
Das hatten wir absichtlich so geändert. Scheinbar gibt es aber andere Nebeneffekte mit yrewrite oder ycom.
Ich ändere das wieder auf index.php und Parameter lang=x statt clang=x ab da jetzt auch die Session im consent_manager entfernt ist.
Danke Chris! @oioix

**Comment by aeberhard** [comment]
@oioix Chris ich habe nochmal was geändert. Kannst Du das bei Gelegenheit mit der aktuellen github-Version testen!?
Danke Dir!

**Comment by oioix** [comment]
Hi Andreas, sorry für die späte Antwort. War Land unter.

Ich habe ebenfalls zu danken! 

Gerade hab ich die aktuelle GitHub-Version getestet. Es scheint alles gut zu sein. 
Es sind keine Probleme erkennbar.

**Comment by aeberhard** [comment]
Hi Chris, super und Danke für deine Rückmeldung!
