### ISSUE TITLE
consent_manager-show-box-reload funktioniert in der aktuellen Version nicht mehr.

### ISSUE THREAD

**Issue by olien** [FriendsOfREDAXO/consent_manager#218]
Hab dann wieder 3.0.0 installiert. da geht es.

**Comment by olien** [comment]
das in der .htaceess hat geholfen... (ob klug oder nicht)

`    Header set Access-Control-Allow-Origin "*"`

**Comment by aeberhard** [comment]
Unterschiedliche Url http / https? Wäre interessant zu sehen. Evtl. vorher schon Security Headers gesetzt?

**Comment by olien** [comment]
1. Nein. 2. Keine Ahnung 
2. 3. Fasse ich das alles nicht an sofern es nicht sein muß. Der Kunde ist da nicht sehr entspannt :-)

Sobald ich das nochmal habe melde ich mich wieder!
