### ISSUE TITLE
$clang in outputJavascript nicht bekannt... 

### ISSUE THREAD

**Issue by olien** [FriendsOfREDAXO/consent_manager#219]
![image](https://user-images.githubusercontent.com/330516/147651648-69846eed-4b26-487c-9b93-9d89479464be.png)

![image](https://user-images.githubusercontent.com/330516/147651603-08db9a37-6ad7-43bf-8ed5-34e915bfc8e0.png)

**Comment by aeberhard** [comment]
@olien hast Du die aktuelle github-Version getestest ?
Wie sieht denn der Aufruf im HTML aus ?

sollte so aussehen 

`<script src="?consent_manager_outputjs=1&clang=1&a=5&i=false&h=false&cid=32&v=3&t=1640642931" id="consent_manager_script" defer></script>`

**Comment by olien** [comment]
Ja. Github Version. Link sieht ok aus: 

`<script src="?consent_manager_outputjs=1&clang=1&a=1&i=false&h=false&cid=5&v=3&t=1640620110" id="consent_manager_script" defer></script>`

und trotzdem ist $clang in der Datei constent_manager_frontend.php in Zeile 103 nicht bekannt...
