### ISSUE TITLE
Nach Anlegen einer neuen Sprache müsste der Cache neu aufgebaut werden

### ISSUE THREAD

**Issue by tbaddade** [FriendsOfREDAXO/consent_manager#221]
Version 3.0.0

Ansonsten erscheint im Frontend eine Notice im Artikel der neuangelegten Sprache

Eventuell ist das auch schon behoben. Kann ich nur nicht testen, da ein Update auf 3.0.4 derzeit nicht möglich ist.

**Comment by aeberhard** [comment]
@tbaddade das könntest Du bei deiner 3.0.0 mal einbauen! 
https://github.com/FriendsOfREDAXO/consent_manager/commit/a0ac9212ca9f6c341c01bb43cc64a92b8f2f6b9b
