### ISSUE TITLE
Checkbox ergänzen um Consentbox auch auf der Impressum / Datenschutz Seite anzuzeigen

### ISSUE THREAD

**Issue by godsdog** [FriendsOfREDAXO/consent_manager#224]
Fände es super, wenn diese Option verfügbar wäre. PR folgt...

**Comment by tyrant88** [comment]
Warum wird sie denn eigentlich nicht angezeigt?

**Comment by aeberhard** [comment]
Die werden da ja absichtlich nicht angezeigt. Warum sollten die da angezeigt werden?

**Comment by IngoWinter** [comment]
Das Cookie Banner darf nicht die Links zu Datenschutzerklärung und Impressum verdecken, weil diese Informationen jederzeit und ohne Umwege/Behinderung durch den Nutzer der Website einsehbar sein müssen.  Deswegen möchte ich den Inhalt der beiden Seiten ebenfalls nicht mit einem Cookie Banner verdecken. 

Selbst wenn es rechtlich ok ist, auf Datenschutzerklärung und Impressum ein Cookie Banner zu zeigen  - es gibt schlicht keinen Grund dafür. Zumindest fällt mir keiner ein :)

**Comment by tyrant88** [comment]
Ich dachte fälschlicherweise, es könnte etwas ausgeführt werden was consent benötigt, wenn die box nicht angezeigt wird.
Aber wenn man in Template und Modulen sauber abfragt, ob consent vorhanden ist, kann ja nichts schief gehen.
