### ISSUE TITLE
Dienst consent_manager muss auf jeden Fall in die Tabelle eingefügt werden, auch ohne Beispielimport

### ISSUE THREAD

**Issue by aeberhard** [FriendsOfREDAXO/consent_manager#225]
Ohne Beispiel-Import fehlt der Dienst 'consent_manager' in der Tabelle

**Comment by aeberhard** [comment]
Siehe #223

**Comment by tbaddade** [comment]
Es wäre dann sinnvoller, den Key gleich auf `consent-manager` anzupassen oder das die Validierung auch `_` erlaubt.

**Comment by aeberhard** [comment]
Einfacher ist natürlich bei der Validierung `_` zu erlauben. 
Gespeicherte Cookies sind ja schon mit 'consent_manager' gespeichert.

@IngoWinter spricht da was dagegen, bzw. hat das einen besonderen Grund dass 'consent_manager' für den Dienst gewählt wurde?

**Comment by IngoWinter** [comment]
@aeberhard mit der umbenennung zu consent_manager hatte ich nix zu tun - ursprünglich hatte dieser cookie den namen iwcc :)

ob es irgendein problem gibt, wenn der unterstrich erlaubt ist kann ich gerade nicht sagen. wahrscheinlich nicht - zumindest habe ich gerade auf die schnelle keine vorkommen von strpos, explode, split oder indexOf gefunden, die einen unterstrich erwarten.

**Comment by tyrant88** [comment]
Den Titel dess issues finde ich gerade falsch. Denn ein Dienst namens 'consent_manger' muss nicht existieren.
Als Bug würde ich aber tatsächlich ansehen, dass ein Dienst mit diesem Namen im Code besonders behandelt wird, man aber keinen solchen Anlegen kann.
PR dazu habe icih gemacht.
Generell würde ich diese Sonderrolle im Code lieber beseitigen und durch ein "Häkchen" an einem der "Dienste" beliebigen Namens ermöglichen.

**Comment by tyrant88** [comment]
Dabei ist wichtig zu wissen, dass der Name des realen Cookies NICHTS mit diesem Eintrag in der Cookie-Tabelle zu tun hat.

**Comment by IngoWinter** [comment]
Die Absicht war, dass keiner aus Versehen oder Unwissenheit den Cookie löscht, ohne den das Addon nicht funktioniert :)

**Comment by tyrant88** [comment]
Ich glaube funktionieren tut es auch ohne.

**Comment by IngoWinter** [comment]
Es geht doch um den Keks, in dem der Consent Manager alles speichert. Der muss doch vorhanden sein?

**Comment by tyrant88** [comment]
> Dabei ist wichtig zu wissen, dass der Name des realen Cookies NICHTS mit diesem Eintrag in der Cookie-Tabelle zu tun hat.
Wozu tippe ich eigentlich...
Genau darum geht es doch! :-)

**Comment by IngoWinter** [comment]
Jetzt habe ich verstanden was du meinst. Du möchtest statt des fixen Keys für diesen Dienst den Nutzer einen Dienst erstellen lassen, den er dann manuell dem Consent Manager Cookie zuordnen muss.

Wenn es dich in den Fingern juckt das zu ändern - ich habe keine Einwände :)

**Comment by tyrant88** [comment]
Ich wollte, dass mal jemand, der den Code besser kennt mit überlegt, ob und warum überhaupt "ein Dienst dem Cookie zu geordnet werden muss".

**Comment by IngoWinter** [comment]
Natürlich funktioniert der consent_manager Cookie auch ohne dass dafür ein Dienst erstellt wird. Allerdings bildest du aus den Diensten die zu akzeptierenden Gruppen - gibt es keinen Dienst für das consent_manager Cookie, wird der Nutzer im Banner nicht darüber informiert.

**Comment by tyrant88** [comment]
In sofern unterscheidet sich der consent_manager Dienst also nicht von den anderen Diensten. 
Und der reale Cookie ist ja ein technisch notwendiger Cookie, d.h. er muss gar nicht erwähnt werden.
Daraus leitete ich nur ab, dass aus diesen Gründen kein "consent_manager" Dienst angelegt werden MUSS oder auch existieren MUSS.
Bleibt die Frage WAS erforderlich macht, dass im Code `if (... == 'consent_manager')` steht.

**Comment by IngoWinter** [comment]
Ich schätze nix. Nimms raus und guck obs dann noch läuft :)

**Comment by aeberhard** [comment]
Ich mache hier mal zu. Bei Bedarf kann ja wieder geöffnet werden :)
