### ISSUE TITLE
Scripte werden nicht nachgeladen in Version 3.0.4

### ISSUE THREAD

**Issue by ebro** [FriendsOfREDAXO/consent_manager#234]
Mir ist aufgefallen, wenn man bisher die Cookies akzeptiert hat, die Script gleich nachgeladen werden.
Jedoch scheint da nicht mehr der Fall zu sein bei Version 3.0.4

Die Trackingscript werden erst nach einem Relaod geladen und nicht direkt wenn man z.Bsp. Alle Akzeptieren auswählt.

**Comment by IngoWinter** [comment]
Ein Link zur betreffenden Seite wäre hilfreich.

**Comment by ebro** [comment]
Aktuell hab ich das auf folgender Seite in Version 3.0.4, wo die Scripte nicht nachgeladen werden:
https://geschaeftsbericht2020.minergie.ch

Ich hatte das gleiche Problem auf https://www.minergie.ch, jedoch hab ich hier nun die Version 3.0.3 installiert und hier funktioniert es nun. 

Ich hab gerade gesehen, dass auch eine neue Version 3.0.5 veröffentlich worden ist. Diese hab ich bisher nicht getestet. Alle Versionen vor 3.0.4 haben einwandfrei funktioniert.

**Comment by IngoWinter** [comment]
Probier mal die 3.0.5. Da ist dieser Bugfix https://github.com/FriendsOfREDAXO/consent_manager/commit/6950e82bda9b4e6561cf9f2934ab1e0b23cb12c8 drin, sollte dein Problem lösen.

**Comment by ebro** [comment]
Super! Ja ich hab gerade mal 3.0.5 installiert und getestet. Hier funktioniert es nun wieder wie zuvor.
