### ISSUE TITLE
Whoops unter PHP 8.1

### ISSUE THREAD

**Issue by tbaddade** [FriendsOfREDAXO/consent_manager#235]
```
ErrorException thrown with message "str_replace(): Passing null to parameter #3 ($subject) of type array|string is deprecated"

Stacktrace:
#7 ErrorException in /src/addons/consent_manager/lib/consent_manager_clang.php:57
#6 str_replace in /src/addons/consent_manager/lib/consent_manager_clang.php:57
#5 consent_manager_clang:addLangNav in /src/core/lib/extension.php:52
#4 rex_extension:{closure} in /src/core/lib/util/timer.php:63
#3 rex_timer:measure in /src/core/lib/extension.php:63
#2 rex_extension:registerPoint in /src/core/backend.php:207
#1 require in /src/core/boot.php:143
#0 require in /public/redaxo/index.php:12
```

**ErrorException:** str_replace(): Passing null to parameter #3 ($subject) of type array|string is deprecated
**File:** src/addons/consent_manager/lib/consent_manager_clang.php
**Line:** 57

<details>
<summary>Stacktrace</summary>

| Function                          | File                                                     | Line     |
| --------------------------------- | -------------------------------------------------------- | -------- |
| rex_error_handler::handleError    |                                                          |          |
| str_replace                       | src/addons/consent_manager/lib/consent_manager_clang.php | 57       |
| consent_manager_clang::addLangNav | src/core/lib/extension.php                               | 52       |
| rex_extension::{closure}          | src/core/lib/util/timer.php                              | 63       |
| rex_timer::measure                | src/core/lib/extension.php                               | 63       |
| rex_extension::registerPoint      | src/core/backend.php                                     | 207      |
| require                           | src/core/boot.php                                        | 143      |
| require                           | public/redaxo/index.php                                  | 12       |

</details>
<details>
<summary>System report (REDAXO 5.13.2, PHP 8.1.5, MariaDB 10.6.4)</summary>

| REDAXO        |            |
| ------------: | :--------- |
|       Version | 5.13.2     |

| PHP           |            |
| ------------: | :--------- |
|       Version | 8.1.5      |
|       OPcache | no         |
|        Xdebug | no         |

| Database      |                |
| ------------: | :------------- |
|       Version | MariaDB 10.6.4 |
| Character set | utf8mb4        |

| Server        |                |
| ------------: | :------------- |
|            OS | Darwin         |
|          SAPI | apache2handler |
|     Webserver | Apache/2.4.51  |

</details>

**Comment by IngoWinter** [comment]
https://github.com/FriendsOfREDAXO/consent_manager/blob/master/lib/consent_manager_clang.php#L52
Da müsste man die mit der Zeit hinzugekommenen Pages (config, log, setup) ergänzen.

**Comment by olien** [comment]
Also ich hab auch nen Woops (beim Import der Beispieldateien) wenn ich die PHP Version runtersetze. Habe dann mal Version 3.0.0 installiert, die Beispieldateien Importiert und dann das AddOn aktualisiert. Das ging. (Hoffe das passt hier hin und ist nix eigenes.)
