### ISSUE TITLE
Google Ads als Standard-Texte mit aufnehmen

### ISSUE THREAD

**Issue by alxndr-w** [FriendsOfREDAXO/consent_manager#236]

**Comment by tyrant88** [comment]
Das hängt aber von der Implementierung ab, welche Cookies verwendet werden...
https://traffic3.net/wissen/datenschutz/google-cookies#s43

**Comment by alxndr-w** [comment]
Dann eben Text**e**

**Comment by aeberhard** [comment]
Gerne als PR !
