### ISSUE TITLE
Warning 'Undefined array key 1' bei Installation des Addons

### ISSUE THREAD

**Issue by TobiasKrais** [FriendsOfREDAXO/consent_manager#239]
Der Fehler kommt hier: https://github.com/FriendsOfREDAXO/consent_manager/blob/8b576eb94723e76f74f3c2d95de5975d0516f83f/lib/consent_manager_cache.php#L137 Fehler ist "Undefined array key 1"

**Comment by tyrant88** [comment]
Wäre schöner zu beschreiben, wie man das reproduzieren kann.

**Comment by TobiasKrais** [comment]
@olien kannst du hier mehr Infos geben?

**Comment by alxndr-w** [comment]
@olien warum kannst du nicht einfach den Stacktrace reinkopieren?

**Comment by olien** [comment]
Das kommt bei der Installation:

![image](https://user-images.githubusercontent.com/330516/168479863-a070bc77-3562-43e9-abe5-3b9689a18d96.png)


`ErrorException thrown with message "Undefined offset: 1"

Stacktrace:
#14 ErrorException in /home/users/website/redaxo/src/addons/consent_manager/lib/consent_manager_cache.php:137
#13 rex_error_handler:handleError in /home/users/website/redaxo/src/addons/consent_manager/lib/consent_manager_cache.php:137
#12 consent_manager_cache:setConfig in /home/users/website/redaxo/src/addons/consent_manager/lib/consent_manager_cache.php:36
#11 consent_manager_cache:writeCache in /home/users/website/redaxo/src/addons/consent_manager/lib/consent_manager_cache.php:144
#10 consent_manager_cache:forceWrite in /home/users/website/redaxo/src/addons/consent_manager/install.php:111
#9 require in /home/users/website/redaxo/src/core/lib/packages/package.php:280
#8 rex_package:includeFile in /home/users/website/redaxo/src/core/lib/packages/manager.php:143
#7 rex_package_manager:install in /home/users/website/redaxo/src/core/lib/packages/addons/manager.php:27
#6 rex_addon_manager:install in /home/users/website/redaxo/src/core/lib/packages/api_package.php:34
#5 rex_api_package:execute in /home/users/website/redaxo/src/core/lib/api_function.php:180
#4 rex_api_function:handleCall in /home/users/website/redaxo/src/addons/debug/lib/extensions/api_function_debug.php:17
#3 rex_api_function_debug:handleCall in /home/users/website/redaxo/src/core/lib/api_function.php:150
#2 rex_api_function:handleCall in /home/users/website/redaxo/src/core/backend.php:234
#1 require in /home/users/website/redaxo/src/core/boot.php:143
#0 require in /home/users/website/redaxo/index.php:9
`

**Comment by alxndr-w** [comment]
@olien Danke. Als Tipp für die Zukunft: Du kannst bei einem Whoops auf "Copy Markdown" klicken bie der Fehlermeldung, dann kann man das hier sehr einfach einfügen und auch lesbar.

**Comment by tyrant88** [comment]
Ich brauchte keinen stacktrace, sondern ne Beschreibung wie ich das reproduzieren kann. "Bei der Installation" hatte ich nicht ernst genommen, weil ich es ja installieren konnte. Aber das lag ja an "throw_always_exception" - Im Log war natürlich dieselbe Meldung.
