### ISSUE TITLE
Lighthouse: Links are not crawlable

### ISSUE THREAD

**Issue by anveno** [FriendsOfREDAXO/consent_manager#243]
Google Lighthouse Test beschwert sich das die "Links are not crawlable" sind.

> Search engines may use `href` attributes on links to crawl websites. Ensure that the `href` attribute of anchor elements links to an appropriate destination, so more pages of the site can be discovered.
> 
> Uncrawlable Link
> a.consent_manager-save-selection.consent_manager-close
> a.consent_manager-accept-all.consent_manager-close

Ist das etwas das grunsätzlich in consent_manager_box.php angepasst werden sollte?
Also `<a>` durch z.B. `<span>` ersetzen oder sollte man das wenn gewünscht über ein eigenes Fragment lösen?

**Comment by aeberhard** [comment]
In der nächsten Version werde ich die Links als Buttons im Fragment ändern.

**Comment by aeberhard** [comment]
Die Links sind in der nächsten Version Buttons.
Wer was anderes will kann ein eigenes Fragment verwenden.
Daher hier close

**Comment by anveno** [comment]
Stimmt; Button ist besser und semantisch korrekter als ein Span-Element,
Allerdings gibt es noch den "consent_manager-toggle-details" als a-Link. Das müsste dann eigentlich auch ein Button sein oder?

**Comment by aeberhard** [comment]
Stefan, den Link kannst Du ja gerne in einem eigenen Fragment ändern.
Diese Meldung von lighthouse ist ja auch nur ein Hinweis.
