### ISSUE TITLE
Cache Problem bei Installation

### ISSUE THREAD

**Issue by georgkaser** [FriendsOfREDAXO/consent_manager#244]
Ich hab ein Problem bei der Installation des Addons: Lokal gehts, am Server leider nicht (hab auch schon die Rechte auf 775 geändert - hat nix gebracht). 

Folgende Fehlermeldung bei der Installation des Addons: [translate:cache_not_writable]

Alle anderen Addons kann ich problemlos installieren und deinstallieren.

Ich verwende die aktuellste REDAXO Version. Server Anbieter ist hostpoint.ch

Woran kann das liegen?

**Comment by aeberhard** [comment]
@georgkaser hat sich hier noch was neues ergeben?

**Comment by georgkaser** [comment]
Nein, ich konnte das nicht mehr testen. Der Kunde setzt das Addon nicht mehr ein.

**Comment by aeberhard** [comment]
Ok Danke Dir, ich mache hier dann zu :)
