### ISSUE TITLE
Google Tag Manager-Skript darf nicht innerhalb anderer Tags stehen

### ISSUE THREAD

**Issue by DanielWeitenauer** [FriendsOfREDAXO/consent_manager#245]
Die aktivierten Skripte des Consent Managers werden immer in ein `div` gesetzt. Leider funktioniert der Google Tag Manager nicht korrekt, wenn das Skript nicht als direktes Kind vom `body `eingebunden wird: https://support.google.com/tagassistant/answer/3207128?ref_topic=2947092#script_flow

**Comment by aeberhard** [comment]
Dann musst Du die Scripte selbst entsprechend im Body einbinden und den Consent abfragen.
