### ISSUE TITLE
Aktivierte Skripte stehen am Fuß der Seite

### ISSUE THREAD

**Issue by DanielWeitenauer** [FriendsOfREDAXO/consent_manager#246]
Die meisten SEO-Tools sollten jedoch möglichst weit oben im HTML eingebunden werden, um möglichst früh aktiviert zu werden. Gibt es eine Möglichkeit die Einbindungsposition zu bestimmen?

**Comment by skerbis** [comment]
> Die meisten SEO-Tools sollten jedoch möglichst weit oben im HTML eingebunden werden
wer sagt denn sowas? 
So lange es noch keine Zustimmung dazu gibt, werden die eh erst nach dem OK geladen.
Erfolgte eine Zustimmung. So kannst du es ja abfragen und ggf. direkt laden 👍🏻

**Comment by DanielWeitenauer** [comment]
> wer sagt denn sowas?
- Die Anleitungen für den Einbau von Analytics Tags https://support.google.com/tagmanager/answer/6103696?hl=de#zippy=%2Cwebseiten https://support.google.com/analytics/answer/1008080#zippy=%2Cthemen-in-diesem-artikel https://www.facebook.com/business/help/952192354843755?id=1205376682832142
- Die Ausführungsreihenfolge von JavaScript https://molily.de/js/einbindung.html
- und die Fachleute https://www.analyticsmania.com/post/google-tag-manager-head-or-body/

Je später die Skripte geladen und ausgeführt werden, um so länger können Nutzende auf der Seite herumklicken, ohne dass es gemessen wird.

> So lange es noch keine Zustimmung dazu gibt, werden die eh erst nach dem OK geladen.
Das gilt nur beim ersten Seitenaufruf. Bei jedem weiteren nicht.

**Comment by IngoWinter** [comment]
Das ist in der Theorie korrekt. Wenn deine Website allerdings so dreckslahm ist, dass Besucher herumklicken können bevor die Skripte geladen sind, hast du andere Probleme :)

Du musst die Skripte nicht im Backend hinterlegen. Du kannst auch per PHP möglichst weit oben im HTML die Einwilligung des Nutzers abfragen und dort das Geraffel laden:
https://github.com/FriendsOfREDAXO/consent_manager/blob/master/lib/consent_manager_util.php

Beim ersten Seitenaufruf oder wenn der Nutzer manuell die Einstellungen anpasst würdest du  entweder die Seite neu laden (damit deine PHP Abfrage greifen kann) oder per JS das Geraffel laden:
https://github.com/FriendsOfREDAXO/consent_manager/blob/master/assets/consent_manager_frontend.js#L133-L138

**Comment by aeberhard** [comment]
Was Ingo sagt!

Du musst ja nicht die "Standard-Einbindung" verwenden sondern kannst, wie bei REDAXO auch, flexibel deinen gewünschten Code da einbinden wo Du ihn haben willst.

Für 99% wird das so wie es ist passen, und die paar wilden "Rumklicker" haben sich eh verlaufen und kein echtes Interesse an der Seite.

**Comment by aeberhard** [comment]
Ich mach hier dann mal zu
