### ISSUE TITLE
Base table or view already exists: 1050 Table 'rex_consent_manager_cookie' 

### ISSUE THREAD

**Issue by alxndr-w** [FriendsOfREDAXO/consent_manager#247]
**Description / Beschreibung**
AddOn consent_manager konnte aus folgendem Grund nicht aktualisiert werden:
SQL error: Error while executing statement "CREATE TABLE `rex_consent_manager_cookie` ( `pid` int(10) unsigned NOT NULL AUTO_INCREMENT , `id` int(10) unsigned NOT NULL , `clang_id` int(10) unsigned NOT NULL , `uid` varchar(255) NOT NULL , `service_name` varchar(255) NOT NULL , `provider` varchar(255) NOT NULL , `provider_link_privacy` varchar(255) NOT NULL , `definition` text NOT NULL , `script` text NOT NULL , `placeholder_text` text NOT NULL , `placeholder_image` varchar(255) NOT NULL , `createuser` varchar(255) NOT NULL , `updateuser` varchar(255) NOT NULL , `createdate` datetime NOT NULL , `updatedate` datetime NOT NULL , PRIMARY KEY (`pid`) ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;" using params []! SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'rex_consent_manager_cookie' already exists

**Affected versions / Verwendete Versionen**
3.0.7 auf 3.0.8

REDAXO: 
PHP:
Database:
Browser: 
AddOns:

**Did it whoops? / Whoops erhalten?**

**Comment by aeberhard** [comment]
Hallo Alex @alxndr-w. Ich kann das leider nicht nachvollziehen.
War das ein Update aus dem Installer?

**Comment by alxndr-w** [comment]
Ja

**Comment by aeberhard** [comment]
@alxndr-w ich habe jetzt etliche Szenarienn durch bei meiner Entwicklung und habe nie einen ähnlichen Fehler bekommen :(

Darum mache ich hier mal zu. Falls das noch mal auftritt wieder aufmachen :)
