### ISSUE TITLE
YAML validieren, bevor es gespeichert / übernommen wird

### ISSUE THREAD

**Issue by alxndr-w** [FriendsOfREDAXO/consent_manager#248]
**Description / Beschreibung**
Der Consent-Manager schießt mit einem Whooops die ganze Seite ab, wenn die YAML-Definition fehlerhaft war. Besser wäre, beim Abspeichern zu prüfen, ob die Eingabe korrekt ist und ggf. das Speichern zu verweigern.

**Affected versions / Verwendete Versionen**

REDAXO: 5.14
PHP: 8.1
Database: *
Browser: *
AddOns: *

**Did it whoops? / Whoops erhalten?**

**Comment by aeberhard** [comment]
@gharlan gibt es eine Möglichkeit YAML zu validieren?
Dann könnte  ich das in einer Custom-Validation einbauen.

**Comment by gharlan** [comment]
So kann man es zum Beispiel validieren:

```php
$valid = true;
try {
    rex_string::yamlDecode($content);
} catch (rex_yaml_parse_exception $exception) {
    $valid = false;
}
```

**Comment by aeberhard** [comment]
Danke @gharlan klappt so!
