### ISSUE TITLE
Javascripte der Dienste werden nicht geladen

### ISSUE THREAD

**Issue by skerbis** [FriendsOfREDAXO/consent_manager#253]
**Description / Beschreibung**

Domain angelegt
Dienst angelegt
Dienst zur Gruppe hinzugefügt
Gruppe Domain hinzugefügt 

Aber von meinem Skript nichts zu sehen. 
Manuelle Abfrage des Cookies per PHP ist erfolgreich. 

ich schätze das Skript sollte hier drin zu finden sein, aber leider nicht: 

/index.php?consent_manager_outputjs=1&amp;lang=1&amp;a=1&amp;i=false&amp;h=false&amp;cid=15&amp;v=3&amp;t=16657459341

**Affected versions / Verwendete Versionen**

Aktuelle Version

**Comment by aeberhard** [comment]
Hast Du einen Link Thomas? Wird das Consentmanager-Script geladen?
Die Dienste-Scripte sind verschlüsselt im Popup-HTML

**Comment by skerbis** [comment]
Scheint an meiner lokalen Installation gelegen zu haben. Live geht's
