### ISSUE TITLE
Button "Alles ablehnen"

### ISSUE THREAD

**Issue by alex0107** [FriendsOfREDAXO/consent_manager#255]
**Feature description / Feature Beschreibung**

Hi zusammen,
Wir wurden von einem Datenschutzexperten darauf hingewiesen, dass ein dritter und zusätzlicher Button "Alles ablehnen" Pflicht sei.

Folgendes habe ich dazu gefunden:
https://datenschutz-hamburg.de/pressemitteilungen/2022/04/2022-04-05-cookiebanner?s=09

Ist bereits möglich so einen Button selbst zu integrieren bzw. dass ihr einen für alle integriert? 
Habe aktuell nichts in den Issues gefunden.

Vielen Dank für eure Rückmeldung und echt super AddOn!!

**Comment by aeberhard** [comment]
Einen dritten Button braucht es nicht. 'Auswahl bestätigen' ist quasi auch der alles ablehnen Button.

Genau genommen müsste der Close-Button rausgenommen werden. Den kann man wenn gewünscht auch per CSS ausblenden.

Es gibt Consent-Banner auf Webseiten wo wirklich alles versteckt ist, solche sind in deiner Webseite gemeint.

Ausser unser **Datenschutzexperte** @novinet-dsteffen sagt hier was anderes :)

**Comment by thorol** [comment]
Den dritten Button bräuchte es, wenn das Consent Banner erneut, z.B. über den Footer aufgerufen wird. Dann sind evtl. Voreinstellungen der checkboxen vorhanden. Der "Auswahl bestätigen" Button ist dann nicht mehr "alles Ablehnen".

**Comment by IngoWinter** [comment]
@thorol frag doch mal den Datenschutzexperten nach der Quelle für die Pflicht zum 3. Button. Und dann gerne wieder aufmachen hier.

**Comment by thorol** [comment]
@IngoWinter Es ging nicht um einen 3. Button, sondern um einen alles ablehnen Button, beim Procedere wie oben beschrieben.

**Comment by novinet-dsteffen** [comment]
Denkt doch mal nicht an das Gesetz, denkt an den User. Was würde der wollen? Und dann macht genau das ;-)
Ich würde empfehlen "Nur technisch notwendige Dienste", "Alle Dienste", "Gewählte Dienste". Es geht am Ende ja nicht nur um Cookies! Denkt dabei bitte auch an Dark Pattern. Das x kann ruhig bleiben, das ist gleichzusetzen mit einer nicht gegebenen Einwilligung, was gleichbedeutend ist mit "Nur technisch notwendige Dienste" beim Default-Laden bzw. "schließen" beim Wiederaufruf.
Gruß, Daniel aka Datenschutz-Junkie

**Comment by IngoWinter** [comment]
> Ich würde empfehlen "Nur technisch notwendige Dienste", "Alle Dienste", "Gewählte Dienste".

Also neues Feature 3. Button "Nur technisch notwendige Dienste" / "Alles ablehnen".
@thorol kannst dich direkt an die Umsetzung machen :)

**Comment by thorol** [comment]
Ich kann mir das gerne einmal anschauen, allerdings bin ich in js nicht so bewandert.

**Comment by IngoWinter** [comment]
@thorol 

Hier Button mit der Klasse consent_manager-accept-all einsetzen: https://github.com/FriendsOfREDAXO/consent_manager/blob/master/fragments/consent_manager_box.php#L69

Hier die Klasse abfragen und die save_consent Funktion mit dem Parameter "none" aufrufen:
https://github.com/FriendsOfREDAXO/consent_manager/blob/master/assets/consent_manager_frontend.js#L76

Hier um die forEach Schleife ein if(toSave !== 'none') drum setzen:
https://github.com/FriendsOfREDAXO/consent_manager/blob/master/assets/consent_manager_frontend.js#L115

Das sollte es eigentlich schon gewesen sein.

**Comment by aeberhard** [comment]
Closed mit #262

Danke @thorol
