### ISSUE TITLE
4.0.0beta1 > Domain kann inkl. https:// eingegeben werden

### ISSUE THREAD

**Issue by anveno** [FriendsOfREDAXO/consent_manager#259]
**Description / Beschreibung**

In der vorherigen Version wurde gewarnt mit dem Hinweis das die Domain in der Form "domain.de" eingegeben werden soll.
Die Warnung kommt nun nicht mehr. Wenn man nun fälschlicherweise eine Domain inkl. https:// eingibt, wird im Frontend eine Conset-Box ohne Texte ausgegeben.

**Affected versions / Verwendete Versionen**

4.0.0beta1

**Comment by aeberhard** [comment]
Danke Stefan! @anveno
