### ISSUE TITLE
REX_IWCC[] erweitern um Cookie-Check

### ISSUE THREAD

**Issue by skerbis** [FriendsOfREDAXO/consent_manager#26]
Um die Ausgabe in Modulen zu steuern könnte das REX-Var hilfreich sein. 
Eingebundener Code könnte erst ausgegeben werden, wenn dem Cookie zugestimmt wurde. 

Beispiel: 
REX_IWCC[id=1 group=google]

**Comment by aeberhard** [comment]
Ich denke das hier kann zu @skerbis 
Ist ja m. E. über die Scripte in den Cookie-Einstellungen gelöst
