### ISSUE TITLE
Branch-Protection aktivieren

### ISSUE THREAD

**Issue by alxndr-w** [FriendsOfREDAXO/consent_manager#260]
**Feature description / Feature Beschreibung**
![image](https://user-images.githubusercontent.com/3855487/200556458-55ff20cb-5ac3-4c4c-9801-96dfff895235.png)

https://github.com/FriendsOfREDAXO/consent_manager/settings/branch_protection_rules/new?branch_name=master 

Ich nutze das seit einiger Zeit in meinen eigenen Addons und kann nur sagen, dass es gut ist, nicht direkt in main zu pushen, sondern immer einen PR erst fertig zu machen, zu testen und dann in main aufzunehmen. 

Ein netter Effekt nebenbei ist, benachrichtigt zu werden, wenn sich etwas tut und man das Repository abonniert hat. 

Ein weiterer netter Nebeneffekt ist, dass GitHub die Zusammenstellung der Änderungen auf Knopfdruck in die Release-Beschreibung packt und somit ein Changelog erstellt. Wenn man dann noch seinen PR treffsicher benannt hat, was sich ändert, hat man einen sehr zuverlässigen Workflow, der es ermöglicht, mit Änderungen Schritt zu halten und zu wissen, was sich ändert, wenn man das Addon updatet.

**Comment by aeberhard** [comment]
@alxndr-w  da hast Du vollkommen Recht! :)

Werde ich nach der finalen 4.0 aktivieren. Die nächste größere Änderung habe ich schon in der Pipeline.

Betrifft ja einige FOR-Addons

**Comment by aeberhard** [comment]
@alxndr-w  hast Du da Tipps!? Habe das gerade bei einem Repo versucht und ich kann immer noch direkt in den main-Branch committen.

**Comment by alxndr-w** [comment]
Da gibt's noch ein 2. Häkchen, dass die Sperre auch nicht von Admins umgangen werden darf.

**Comment by aeberhard** [comment]
Klasse! Das war's. Besten Dank!
