### ISSUE TITLE
JS minifizieren

### ISSUE THREAD

**Issue by eaCe** [FriendsOfREDAXO/consent_manager#275]
**Feature description / Feature Beschreibung**
Man sollte zumindest die FE-Scripts minifizieren. 
Bei Addons, die ich verwalte, werfe ich inzwischen eine  package.json und eine  webpack.mix.js in das Repo, um diese unkompliziert zu minifizieren/bündeln. Dafür wäre nur Node mit npm oder yarn notwendig. Wenn etwas an der JS geändert wird, kann man dann einen Build anschmeißen. 
Ein Beispiel findet man hier: 

https://github.com/FriendsOfREDAXO/vanilla/blob/main/package.json
https://github.com/FriendsOfREDAXO/vanilla/blob/main/webpack.mix.js

Wenn gewünscht, erstelle ich einen PR.

**Comment by aeberhard** [comment]
Wenn das ohne zusätzlichen Aufwand an Installation funktioniert bin ich dafür.
Ansonsten dagegen!

**Comment by aeberhard** [comment]
@eaCe Thorben, es geht ja nur um das **eine** Script das in der Regel wenig geändert wird.
Daher lohnt sich m. E. der Aufwand nicht. Ich kann das ja minimieren :)

**Comment by aeberhard** [comment]
@eaCe jetzt wird die minimierte Version ausgeliefert (falls vorhanden)
https://github.com/FriendsOfREDAXO/consent_manager/commit/212009d094a074b52b532e4a52aea2f019a11563

**Comment by eaCe** [comment]
Naja etwas Aufwand ist immer ;)
Dankeschön
