### ISSUE TITLE
Theme im Frontend umschalten

### ISSUE THREAD

**Issue by aeberhard** [FriendsOfREDAXO/consent_manager#277]
Aus slack

Kann man im frontendaufruf das theme  wählen? Es gibt ja Seiten mit light/dark umschalter…

**Comment by skerbis** [comment]
Man könnte das CSS so aufbohren dass es auf dark und light preferences reagiert. 
Tatsächlich würde ich dann aber nicht mehr mit scss arbeiten sondern mit CSS/Custom properties. 
Diese können leicht und live umgeschaltet werden und auch den Code übersichtlicher halten.

**Comment by aeberhard** [comment]
Ich mache hier mal zu.
Mit der Version 4.1 hat man mehr Möglichkeiten gezielt selbst zu steuern was ausgegeben wird.
@olien
