### ISSUE TITLE
Consent_Manager wird von ghostery-Browser-Plugin geblockt

### ISSUE THREAD

**Issue by aeberhard** [FriendsOfREDAXO/consent_manager#283]
via Slack gemeldet von @novinet-dsteffen

**Comment by IngoWinter** [comment]
Tja nu, ist ein Feature: [https://www.ghostery.com/blog/never-consent-by-ghostery](https://www.ghostery.com/blog/never-consent-by-ghostery#:~:text=The%20'Never%2DConsent'%20feature,the%20website's%20consent%20pop%2Dups.)
