### ISSUE TITLE
Consent Manager 4 läuft Amok und geht bei jeder Seite erneut auf

### ISSUE THREAD

**Issue by alxndr-w** [FriendsOfREDAXO/consent_manager#284]
**Description / Beschreibung**
Mit jedem neuen Seitenaufruf geht der Consent Manager erneut auf.

**Affected versions / Verwendete Versionen**

REDAXO: 5.14.2
PHP: 8.1
Database: *
Browser: Edge

**Did it whoops? / Whoops erhalten?**
Das wäre mir um ehrlich zu sein lieber gewesen.

**Comment by aeberhard** [comment]
@alxndr-w kann man das irgendwo sehen?

**Comment by alxndr-w** [comment]
Nein. Zum Glück jetzt nicht mehr, weil das auf einer Live-Seite eingetreten ist.

Ich habe alles überprüft, auch die Domain-Einstellungen und bin dann schnell zurück zur Version 3.

**Comment by IngoWinter** [comment]
Installier dir einfach Ghostery https://github.com/FriendsOfREDAXO/consent_manager/issues/283

**Comment by alxndr-w** [comment]
@IngoWinter ja okay, schreibe ich einfach jedem Besucher der Website direkt als overlay über den Consent Manager!

**Comment by aeberhard** [comment]
@alxndr-w da scheint beim Cookie schreiben was nicht zu klappen.
Irgendeine Besonderheit bei der Seite? Evtl. anderer Port, http/https?

**Comment by alxndr-w** [comment]
Ich werde es in Ruhe testen / nachstellen aber nicht auf dem Live-Server...

**Comment by alxndr-w** [comment]
Nein.

**Comment by aeberhard** [comment]
@alxndr-w 
hast Du evtl. irgendwo  REX_CONSENT_MANAGER[forceCache=true/1] im Template.
Das hat auch Auswirkungen wenn es innerhalb eines HTML-Kommentars steckt.

```
<!-- 
REX_CONSENT_MANAGER[forceCache=true forceReload=true forceHidden=false]
-->
```

Das forceCache sollte eigentlich gar nicht notwendig sein. Ich werde das mal entfernen.

**Comment by alxndr-w** [comment]
Das müsste ich prüfen. Ich gebe Bescheid.

**Comment by MC-PMOE** [comment]
Kann das Verhalten für lokale Instanzen bestätigen.
Es scheint alles wie gewünscht zu laufen wenn ich folgende Änderung von 3.0.8 zu 4.0.0 rausnehme:
https://github.com/FriendsOfREDAXO/consent_manager/compare/3.0.8...4.0.0#diff-367ea37e9f05adbf3cc857a1a664bf7393a6141c568549e88fc2f51270588d19L124
(Wenn ich den "domain" Parameter nicht setze)
In meinem Fall ist die Domain so aufgebaut:
http://localhost:8080

**Comment by aeberhard** [comment]
@alxndr-w @MC-PMOE 
Stimmt, ich habe auch verschiedene PHP-Versionen mit unterschiedlichen Ports 8000,8003,8100,8103 ...
In der nächsten 4.1-Version ist das gefixed. Der Port fliegt da raus. Der hat da nichts zu suchen.

**Comment by alxndr-w** [comment]
Nur war das bei mir nicht lokal und auch nicht mit irgendwelchen Ports...

**Comment by alxndr-w** [comment]
Könnte aber sein, dass das was mit den Protokollen zu tun hatte, weil da im Laufe der Liveschaltung von `non-www` auf `www` als Subdomain geswitcht wurde. Also ich müsste mal gezielt dies hier testen:

Website unter non-www aufrufen, Consent aktivieren, dann Website weiter unter `www.` betreiben lassen, Consent versuchen zu aktivieren.

Oder so etwas ähnliches.

**Comment by aeberhard** [comment]
@alxndr-w evtl. hilf es wenn man in der assets/addons/consent_manager/consent_manager_frontend.js (_consent_manager_frontend.min.js löschen!_)

die folgenden zwei Zeilen in der function `deleteCookies()` noch dazu packt
```
            Cookies.remove(encodeURIComponent(key), { 'domain': ('www.' + domain) });
            Cookies.remove(encodeURIComponent(key), { 'domain': ('www.' + domain), 'path': '/' });
```

**Comment by alxndr-w** [comment]
Bevor ich es vergesse: ich möchte prüfen, was passiert, wenn man den Banner zu schnell / zu früh wegklickt, falls das JS noch nicht vollständig ausgeführt wurde. Hatte jetzt das Phänomen, dass der Banner 3-4 Mal offen blieb, danach nicht mehr.

**Comment by alxndr-w** [comment]
Ich werde das nicht mehr weiter prüfen, ich habe jetzt ein eigenes Addon für Drittanbieter-Dienste und Einwilligungen.
