### ISSUE TITLE
Bei neu angelegter Sprache werden die Domains aus der Gruppe nicht übernommen

### ISSUE THREAD

**Issue by clausbde** [FriendsOfREDAXO/consent_manager#289]
**Description / Beschreibung**
Wenn eine neue Sprache hinzugefügt wird, so werden für diese die in den Gruppen zugeordneten Domains nicht übernommen.
Erst wenn in der Standardsprache erneut gespeichert wird tauchen diese in der neuen Sprache auf.

**Affected versions / Verwendete Versionen**
v4.0.0

**Comment by aeberhard** [comment]
@clausbde Hi, kannst Du mal die github-Version 4.0.3 testen. Da sollte das Problem gelöst sein.

Die Sprachen wurden übernommen aber nicht ausgewählt angezeigt. Beim Speichern in der zusätzlichen Sprache wurden die Domains gelöscht.

**Comment by clausbde** [comment]
Hi!
Gerade getestet (4.0.0 -> 4.0.3) - klappt.
Danke!

**Comment by aeberhard** [comment]
Super, danke für's testen! @clausbde
