### ISSUE TITLE
Cookie Banner wird bei Seitenwechsel immer wieder angezeigt

### ISSUE THREAD

**Issue by jeje-993** [FriendsOfREDAXO/consent_manager#291]
**Trotz Bestätigung der Cookies wird der Cookiebanner beim Seitenwechsel immer wieder angezeigt und die Auswahl ist leer, im Consent Log wird auch nichts eingetragen**

**consent_manager 4.0.3**

REDAXO: 5.15.1
PHP: 8.1
Database: MariaDB 10.6.10
Browser:  Firefox
AddOns: consent_manager

**Kein Whoops erhalten?**

**Comment by IngoWinter** [comment]
https://github.com/FriendsOfREDAXO/consent_manager/issues/284

**Comment by jeje-993** [comment]
Hat leider auch nichts genutzt

**Comment by aeberhard** [comment]
@jeje-993 kann man das irgendwo online sehen? Wäre gut wenn man das fixen kann!

**Comment by jeje-993** [comment]
Ja klar https://jaeger-plomer.mein-office.com

**Comment by aeberhard** [comment]
Ich kann das hier in keinem Browser nachvollziehen. Klappt alles.
Gibt es in der JavaScript-Konsole einen Fehler?

**Comment by aeberhard** [comment]
Oder im REDAXO-Log?

**Comment by jeje-993** [comment]
Nein die Log ist leer, in der Konsole steht"Das Cookie "consent_manager" wurde wegen ungültiger Domain abgelehnt." kann das an der Subdomaine liegen?

**Comment by jeje-993** [comment]
Nein, soll ich Dir mal einen Admin Zugang einrichten?

**Comment by aeberhard** [comment]
Ja, aber schreib per Slack eine Private Message an mich :)

**Comment by jeje-993** [comment]
Ist raus

**Comment by aeberhard** [comment]
Ich mache hier mal zu.
Es liegt an einem Browser-Addon bzw. im privaten Modus klappt alles!

@jeje-993 Du informierst mich über deine Erkenntnisse wg. Browser-Addon :)
Evtl. kann man da ja im CM gegensteuern.
