### ISSUE TITLE
Auswahlfenster des CM 4.1.0 erscheint immer wieder

### ISSUE THREAD

**Issue by iceman-fx** [FriendsOfREDAXO/consent_manager#293]
Nach Update auf die 4.1.0 erscheint immer wieder das Auswahlfenster des CM innerhalb der Homepage.
Egal was man anklickt, es scheint nichts gespeichert zu werden.

Es gibt keine JS-Fehler in der Konsole.
CSP sind keine aktiv.
Im Log steht auch nichts drin.

Mit der Version 4.0.3 klappt es korrekt.

REDAXO: 5.15.1
PHP: 8.1.10

**Comment by dpf-dd** [comment]
Kann ich bestätigen. Gleiches Spiel bei mir am Update-Montag...

**Comment by IngoWinter** [comment]
Es wäre gut, wenn ihr Browser / Betriebssystem angeben würdet. Und direkt gucken, obs im Inkognito Modus des verwendeten Browsers auch nicht funktioniert.

**Comment by dpf-dd** [comment]
MacOS BigSur / Chrome Version 111.0.5563.146 (Offizieller Build) (x86_64) / keine Extensions installiert
Im Inkognito-Modus tritt das Problem im Chrome nicht auf...

**Comment by iceman-fx** [comment]
Windows mit Google Chrome 112.0.5615.139 / keine Extensions installiert
Im Inkognito-Modus tritt das Problem im Chrome nicht auf.

**Comment by bitshiftersgmbh** [comment]
Hier auch: Win 10, aktueller Chrome, kein Inkongnito.
Hinweis: Bei mir fing der Spaß erst an, nachdem ich einen neuen Datenschutzartikel angelegt und den alten (der im CM noch verlinkt war) offline genommen habe. Vielleicht hat das was ausgelöst? Oder es war nur Zufall und der Bug liegt woanders ...

**Comment by IngoWinter** [comment]
Das werden die aktuellen Anpassungen in der frontend.js sein: https://github.com/FriendsOfREDAXO/consent_manager/commit/9a75c1e22d734330a7a1458bf963ef340ab14dd0
Ist halt Teufelswerk dieser ganze Cookie Kram...

**Comment by aeberhard** [comment]
Habt ihr da mal Urls um das untersuchen zu können!?
Und kommen da wirklich keine Meldungen im ScriptLog? Also keine Fehler sondern Hinweise !

**Comment by devin-landwehr** [comment]
Hallo, gleiches Problem hier. Es erscheint ein Hinweis im "Probleme" Tab. 

"Synchrone Anfragen von der XMLHttpRequest API im Hauptthread wurden eingestellt, da sie sich nachteilig auf die Endnutzererfahrung auswirken. Weitere Informationen findest du unter https://xhr.spec.whatwg.org/ ."

Keine Meldungen in Log-Files oder der Browser-Konsole.
Hoffe das hilft weiter.

Redaxo 5.15.1 - PHP 8.1.17 - consent_manager 4.1.0 - Chrome 113.0.5672.63 - MacOS 13.3.1

**Comment by dpf-dd** [comment]
OK, hab ne Lösung gefunden... Manuell Cookies löschen hat es gebracht.
<img width="350" alt="Bildschirmfoto 2023-05-08 um 14 49 20" src="https://user-images.githubusercontent.com/10958385/236829003-787153d8-f2a7-4a3a-a97f-437491f36b9e.png">

**Comment by bitshiftersgmbh** [comment]
Ein möglicher Hinweis, woran es liegen könnte: Scheinbar ist sein 4.1.0 die Domain nicht mehr vollständig; sowohl im Cookie als auch im Log.
![image](https://user-images.githubusercontent.com/7023022/237026229-26c05ad7-d1f1-4c72-bbb9-9ae125071b97.png)

**Comment by aeberhard** [comment]
@bitshiftersgmbh  Hi Peter, das soll eigentlich so.
Fehler ist evtl. schon in der Github-Version behoben. Gerne testen :)

**Comment by bitshiftersgmbh** [comment]
Bei mir läuft der Fix gut. Sollte passen. 👍

**Comment by dpf-dd** [comment]
Bei mir ebenfalls :)

**Comment by aeberhard** [comment]
Wurde mit Version 4.1.1 behoben. Daher close
