### ISSUE TITLE
TLD wurde bei .localhost nicht erkannt. 

### ISSUE THREAD

**Issue by dergel** [FriendsOfREDAXO/consent_manager#295]
Deswegen konnte ich lokal den Consent-Manager nicht testen.
Ist das so gewollt, dass die TLD auf 2 bis 6 Zeichen beschränkt sein müssen?
Kann, darf und sollte das nicht toleranter sein?

https://github.com/FriendsOfREDAXO/consent_manager/blob/main/lib/consent_manager_util.php#L61

**Affected versions / Verwendete Versionen**

consent_manager | 4.1.2

**Comment by skerbis** [comment]
@aeberhard siehe meinen PR ... ich habe die TLD auf 24 Zeichen angehoben. Das ist wohl so das längste aktuell verfügbare.
