### ISSUE TITLE
Redaxo Mindestversion auf 5.12 hochsetzen

### ISSUE THREAD

**Issue by IngoWinter** [FriendsOfREDAXO/consent_manager#301]
Die in Methode wurde erst in Redaxo 12 zu rex_sql hinzugefügt: https://github.com/redaxo/redaxo/releases/tag/5.12.0

![cleanshot_2023-07-04_at_14 49 35](https://github.com/FriendsOfREDAXO/consent_manager/assets/7223820/bef58ac5-baf5-48d4-b253-fdd7724dfc0f)

**Comment by aeberhard** [comment]
PR ist schon da :) https://github.com/FriendsOfREDAXO/consent_manager/pull/300

**Comment by aeberhard** [comment]
Closed mit #300
