### ISSUE TITLE
Mobile Device Bug

### ISSUE THREAD

**Issue by my-steffen** [FriendsOfREDAXO/consent_manager#303]
Bei Mobilen Geräten: Wenn man "Statistiken" als erste checkbox setzt. Kann man nichts mehr anklicken (von der hierarchie). Kein Button oder Checkbox. Desktop geht das Problemlos. 

<img width="472" alt="Bildschirmfoto 2023-08-16 um 15 30 36" src="https://github.com/FriendsOfREDAXO/consent_manager/assets/103409908/8852703b-908e-4cd2-8639-09cf54fa0ea9">

**Comment by IngoWinter** [comment]
Kann nur irgendein Frontend Kram sein, ein Link zur Website wäre hilfreich.

**Comment by aeberhard** [comment]
@Shopjektiv-Steffen 
Hast Du da einen Link zur Webseite?
Ist **Notwendig** dann an Position 2 oder 3?
Warum macht man das überhaupt?

**Comment by alxndr-w** [comment]
Kam kein Link mehr.
