### ISSUE TITLE
$_COOKIE['consent_manager'] leer nach Consent und Aufruf von externer Seite

### ISSUE THREAD

**Issue by paddle07** [FriendsOfREDAXO/consent_manager#307]
Folgendes Problem: Ich frage in einem Modul via PHP ab, ob der Consent z.B. für Youtube gesetzt wurde oder nicht und lade die Videos entsprechend. Was wie gewünscht funktioniert.
Wenn ich nun aber die Webseite (wo ich soeben den Cookies zugestimmt habe) nochmals via Google Aufrufe (oder Link auf irgendeiner externen Seite), werden die Videos nicht mehr angezeigt (Output $_COOKIE['consent_manager‘] = NULL) ... erst wenn ich die Seite erneut manuell Aufrufe oder via Navi auf eine andere Seite navigiere, sind die Einträge in $_COOKIE['consent_manager‘] wieder drin.

Das Problem ist bei unterschiedlichen Seiten auf unterschiedlichen Servern aufgetreten. Javascript Cookies werden richtig gesetzt. Betrifft nur die PHP Variable $_COOKIE.

REDAXO: 5.15.1
PHP: 8.1.22
Database: MySQL 5.7.41
Browser: Safari, Chrome, Firefox
AddOns: Consent Manager V 4.1.3

**Comment by IngoWinter** [comment]
Ein Link zu einer der Seiten wäre hilfreich.

**Comment by aeberhard** [comment]
Evtl. Problem mit / ohne www?
$_COOKIE wird ja von PHP gesetzt und nicht vom AddOn.

**Comment by paddle07** [comment]
Nein mit / ohne www ist nicht das Problem. Bin die Ausgabe auf 2 unterschiedlichen Seiten am Testen ... bis Addon Version 4.0.3 funktioniert die Abfrage mit PHP bei beiden Seiten, egal woher der User auf die Seite gelangt. Ab Version 4.1.x nur noch auf einer Seite. Ich mache noch ein paar Test und wenn ich nichts finde, schick ich euch die Links.

**Comment by aeberhard** [comment]
@paddle07 mach mal an der Stelle einen 
`<?php var_dump($_COOKIE); ?>`

Was gibt folgendes aus?
`<?php var_dump(consent_manager_util::has_consent('youtube')); ?>`

Wenn möglich kannst mir auch gerne einen Backend-Zugang einrichten.
Am besten im Slack per PM mitteilen.

**Comment by paddle07** [comment]
consent_manager_util::has_consent('youtube') hatte ich auch schon ausprobiert ... ebenfalls false, wenn array leer

schicke dir die Zugangsdaten für die Testinstallation per Slack

**Comment by brandes-webdesign** [comment]
Ich kann den Fehler ebenfalls bestätigen.
Ist einem Kunden auch aufgefallen.

Ich habe auch etwas getestet, um den Fehler einzugrenzen.

Wenn ich mir das Cookie per JavaScript ausgeben lasse, dann steht da auch was drinnen.
Wenn ich allerdings mit PHP dump($_COOKIE); aufrufe, dann kommt.

^ array:2 [▼
    "PHPSESSID" => "c465...6180"
    "rex_htaccess_check" => "1"
]

erst wenn ich dann z.B. über Menü der Webseite nochmal zu der Seite gehen, dann kommt

^ array:3 [▼
    "consent_manager" => "{"consents":["consent_manager","centralplanner"],"version":4,"consentid":"6520...41881","cachelogid":"69"}"
    "PHPSESSID" => "c465...6180"
    "rex_htaccess_check" => "1"
]

**Comment by brandes-webdesign** [comment]
Noch einer Ergänzung:

Wenn die Webseite allerdings vorher noch nie aufgerufen wurde, bzw. der Cache geleert wurde, dann kommt zumindest der Cookie Banner und wenn ich dort was auswähle, dann klappt das auch.

Es ist wirklich nur der Fall, wenn man auf der Webseite schon einmal war und in dem Cookie Banner was ausgewählt hat.
Kommt man dann von einer anderen Seite oder z.B. einem Newsletter und einem Link dort zur Webseite, dann ist per PHP im $_COOKIE nix drinnen vom consent_manager.

Ne Idee warum das so ist habe ich leider nicht, helfe aber natürlich gerne weiter bei der Lösungssuche.

**Comment by aeberhard** [comment]
Fix kommt demnächst!
Dank @paddle07 Patricia ist der Fehler gefunden.

**Comment by brandes-webdesign** [comment]
Super :-)
Vielen Dank an Euch !!!!!!
