### ISSUE TITLE
Einwilligungshistory wird nicht gespeichert

### ISSUE THREAD

**Issue by neve-we** [FriendsOfREDAXO/consent_manager#308]
**Description / Beschreibung**
Das Erlauben/Verbieten von Cookies funktioniert mit dem AddOn wunderbar. Allerdings wird die **Einwilligung nicht in der Datenbank gespeichert**. 

REX_COOKIEDB[] zeigt nur leere Ausgaben an:
Ihre aktuelle Einwilligung
Einwilligungsdatum: -
Einwilligungs-ID: -
Einwilligungen:

Was kann ich tun, um die Einwilligungen zu dokumentieren? Im AddOn ist es ja eigentlich so bereits vorgesehen aber funktioniert eben nicht.

**Affected versions / Verwendete Versionen**

REDAXO: 5.14.3
PHP: 7.4.33
Database: MySQL
Browser: verschiedene
AddOns: consent_manager 4.2.0

**Comment by aeberhard** [comment]
Hi @neve-we,
wird denn was in der Tabelle gespeichert!?
Wie bzw. wo verwendest Du REX_COOKIEDB[] ?

**Comment by neve-we** [comment]
Hey auch @aeberhard ,
in der Tabelle meinredaxo_consent_manager_consent_log kommt überhaupt nichts an. In meinredaxo_consent_manager_cache_log allerdings schon und der Consent Banner funktioniert auch ansonsten fehlerfrei, eben nur die Einwilligungshistory nicht.
Ich arbeite nicht mit der Standard rex_ Installation sondern mit eigenem Präfix.

REX_COOKIEDB[] habe ich im Template nur zum Testen mal ausgegeben. Alle Werte sind logischerweise leer, da ja nichts in der Datenbanktabelle steht.

Im redaxo system.log steht keine Fehlermeldung dazu.

**Comment by aeberhard** [comment]
Gib mal irgendwo 
`<?php dump(rex::getTable('consent_manager_consent_log')); ?>`
aus, ob da auch dein angepasster Prefix beim Tabellennamen verwendet wird.

Sonst mal im Browser das Cookie löschen und den Consent bestätigen und im 
Netzwerk-Inspector (Dev-Tool im Browser) schauen ob der API-Aufruf einen Fehler bekommt.

Das Log wird in `lib/rex_api_consent_manager.php` ausgegeben.
Zur Not kannst Du hier auch mal eine Meldung ins REDAXO-Log schreiben
`rex_logger::factory()->info('meldung');`

**Comment by neve-we** [comment]
Also der Tabellenname bzw. Präfix passt.

**Comment by aeberhard** [comment]
@neve-we dann musst Du mal in der JavaScript-Console und beim Netzwerk checken ob es da einen Fehler gibt.

**Comment by neve-we** [comment]
@aeberhard ich habe das Problem gefunden. Da das Projekt noch nicht online geschalten ist, liegt als Startseite unter www.domain.de/ eine statische Vorschaltseite. Wenn ich diese lösche, funktioniert die Speicherung in der log Tabelle. Aber komisch, da alles andere ja funktioniert hat.

Danke auf jeden Fall für die super schnelle Hilfeleistung!
