### ISSUE TITLE
Consent-Log zeigt falsche Domain an

### ISSUE THREAD

**Issue by iceman-fx** [FriendsOfREDAXO/consent_manager#309]
Wenn die Webseite als SubDomain läuft (z.B. xxx.domain.de), dann wird im Log nur domain.de als Domain hinterlegt.
Dies wäre aber falsch, da domain.de != xxx.domain.de ist.

Es können z.B. mehrere WEbseiten als SubDomains existieren.

REDAXO: 5.15.1
Consent;anager: 4.2.0

**Comment by aeberhard** [comment]
@iceman-fx hast Du mehrere Subdomains in einer Instanz? Zeigen die dann alle die gleiche Domain?

**Comment by iceman-fx** [comment]
Ja, ich habe mehrere SubDomains in dieser MultiSite-Umgebung drin.
Und ja, alle zeigen nur die Hauptdomain "domain.de" an.

**Comment by aeberhard** [comment]
@iceman-fx Falko kannst Du mal bei Gelegenheit testen ob das korrekt funktioniert bei Dir!?
https://github.com/FriendsOfREDAXO/consent_manager/pull/311/files

**Comment by iceman-fx** [comment]
Damit geht es bei mir gar nicht mehr.
`Uncaught SyntaxError: Unexpected token '<' (at index.php?consent_manager_outputjs=1&lang=1&a=34&i=false&h=true&cid=34&v=4.2.0&r=0&t=17002041371:34:1)`


Element.prototype,CharacterData.prototype,DocumentType.prototype].forEach(function(e){e.hasOwnProperty("remove")||Object.defineProperty(e,"remove",{configurable:!0,enumerable:!0,writable:!0,value:function(){null!==this.parentNode&&this.parentNode.removeChild(this)}})});
// custom event polyfill https://developer.mozilla.org/en-US/docs/Web/API/CustomEvent/CustomEvent#Polyfill
!function(){if("function"==typeof window.CustomEvent)return!1;window.CustomEvent=function(n,t){t=t||{bubbles:!1,cancelable:!1,detail:null};var e=document.createEvent("CustomEvent");return e.initCustomEvent(n,t.bubbles,t.cancelable,t.detail),e}}();

/* --- /assets/addons/consent_manager/consent_manager_frontend.min.js --- */


<!DOCTYPE html>
<html lang="en" data-color-mode="auto" data-light-theme="light" data-dark-theme="dark"  data-a11y-animated-images="system" data-a11y-link-underlines="true">



  <head>
    <meta charset="utf-8">
  <link rel="dns-prefetch"

**Comment by aeberhard** [comment]
Hi Falko,
da ist beim editieren ein Umbruch reingerutscht der da nicht hingehört. Magst Du nochmal probieren!?

**Comment by iceman-fx** [comment]
Da ist kein Unterschied zu vorher.

![1](https://github.com/FriendsOfREDAXO/consent_manager/assets/4291047/bbb2b954-ca22-499b-81e5-e775e05f4015)

**Comment by iceman-fx** [comment]
Es scheint zu klappen.
Die Subdomain wird nun im Log angezeigt, auch wenn im CS selbst immer noch die Meldung "Es wurde noch keine Domain oder keine Dienste zugeordnet! Im Frontent wird evtl. keine Consent-Box angezeigt." angezeigt wird.

![1](https://github.com/FriendsOfREDAXO/consent_manager/assets/4291047/cd9981e1-5c4e-4017-9251-eaf139ee883a)

**Comment by aeberhard** [comment]
Du müsstest mit einer der Subdomains oder rzk....de im Backend angemeldet sein. Wenn nicht dann kommt der Fehler.

**Comment by oioix** [comment]
Siehe #317
