### ISSUE TITLE
Details anzeigen/ausblenden lädt Startseite neu

### ISSUE THREAD

**Issue by iceman-fx** [FriendsOfREDAXO/consent_manager#312]
Der Link im Banner:
<a href="#" id="consent_manager-toggle-details" class="icon-info-circled" tabindex="0">Details anzeigen/ausblenden</a>

lädt aufgrund des /# die Startseite der Webseite neu.
Dies sollte abgefangen werden bzw. kein # genutzt werden.

Probleme dabei:
- man verlässt die Seite auf welcher man war
- das Detailfenster öffnet sich nicht, da die Seite neu geladen wird, wenn man nicht bereits auf der Startseite ist.

Consent-Manager: 4.2.0
REDAXO: 5.15.1
PHP: 8.2.6
Browser: Chrome

**Comment by aeberhard** [comment]
Hi Falko,
hast Du hier einen Link zur Seite!? Ich denke das liegt an einem anderen Script auf deiner Seite.

https://github.com/FriendsOfREDAXO/consent_manager/blob/60f20214d342ec750c526f1e91c7c96658adb868/assets/consent_manager_frontend.js#L103C30-L103C30

Da ist ein `return false;` drin

**Comment by iceman-fx** [comment]
Ja, hierüber z.B.: https://www.provitus.de/leistungen/

Evtl. macht es aber Sinn, wenn kein "href" in diesem Link drin wäre.

**Comment by IngoWinter** [comment]
Irgendwas namens "plyr" funkt dazwischen, kein CM Fehler

![Bildschirmfoto 2024-01-03 um 12 34 39](https://github.com/FriendsOfREDAXO/consent_manager/assets/7223820/e9e02c31-a998-4358-9287-4118fe0ae9ba)

**Comment by aeberhard** [comment]
Ja Du hast da ja reichlich JS drin, und CM arbeitet richtig. Nimm mal plyr raus

**Comment by iceman-fx** [comment]
PLYR ist das PLYR-Addon für die Videoausgabe.

**Comment by IngoWinter** [comment]
Mach ein Issue bei plyr auf. Das reagiert auf einen Klick, auf den es nicht zu reagieren hat.

**Comment by iceman-fx** [comment]
Man könnte aber auch im CM den Link ändern auf:
<a id="consent_manager-toggle-details" class="icon-info-circled" tabindex="0">Details anzeigen/ausblenden</a>

Dann klappt es auch ;-)

**Comment by IngoWinter** [comment]
Gegenvorschlag: du lernst mit den Dev Tools umzugehen und machst das nächste Issue direkt im passenden Repo auf - dann klappt es auch ;-)

**Comment by aeberhard** [comment]
# Wurde soweit ich mich erinnern kann extra aufgenommen da ein Link ohne href von irgendeinem Google-Tool oder so  angemeckert wurde. # im href ist ja auch nicht das Problem.

@iceman-fx  Du kannst natürlich das fragment ändern und z.B, im Projekt-Addon ablegen.

Der Fehler liegt aber am plyr-Addon und nicht am CM.

**Comment by olien** [comment]
Warum nicht so?

`<a href="javascript:void(0)" id="consent_manager-toggle-details">Detaila</a>`

**Comment by iceman-fx** [comment]
@olien Auch ein Möglichkeit. Wird aber sicher nicht kommen ;-)

**Comment by olien** [comment]
Kannst du ja im eigenen Fragment nutzen…

**Comment by IngoWinter** [comment]
Kinders, hier ist das entsprechende Issue: https://github.com/FriendsOfREDAXO/consent_manager/issues/313
Das plyr Addon verursacht den Fehler - gebt doch dort gute Ratschläge ;)
