### ISSUE TITLE
Consent-Log in eigene Datei anlegen

### ISSUE THREAD

**Issue by Sreyness** [FriendsOfREDAXO/consent_manager#316]
**Feature description / Feature Beschreibung**
Könnte man das Consent-Log in einer eigenen Log-Datei auslagern, weil meine Datenbank ist nach gerade mal 5 Stunden von schlanken 3 MB auf über 16 MB angewachsen.

Edit: habe gerade gemerkt, es liegt an dem rex_consent_manager_cache_log, denn der hat mittlerweile 163 Zeilen bei mir. Könnte man da bis auf die letzte Zeile einfach alle anderen rauslöschen? 
Weil ich hab nur mal die Tabelle exportiert und es sind gewaltige 11,1 MB

**Comment by oioix** [comment]
Hab gerade bei mir nachgesehen. Bei 3500 Einträgen hat das exportierte sql-file nur 531 kb. 

Dass du bei nur 163 Zeilen (Einträgen) 11,1 MB hast, kann demnach eigentlich nicht sein.

**Comment by Sreyness** [comment]
Hast du das rex_consent_manager_cache_log oder das rex_consent_manager_consent_log exportiert?
Weil das consent_log ist ganz klein, nur das cache_log ist mit 163 Einträgen eben sehr groß.

**Comment by oioix** [comment]
rex_consent_manager_consent_log

**Comment by oioix** [comment]
Das rex_consent_manager_cache_log hat bei mir 64 Einträge und ist nach Export ca. 1,5 MB

**Comment by Sreyness** [comment]
> Wenn ich es richtig vestehe speichert das rex_consent_manager_cache_log die Backend-Einstellungen des Consent managers. Vermutlich für Beweis-Zwecke, wann was wie veröffentlicht war.

Das Glaube ich auch, deshalb müsste ich ja ohne Probleme die Zeilen dazwischen löschen können. (Hab ja eh ein Backup)
Weil bei einem meiner Kunden ist die Seite 8-sprachig und deshalb wird sich das so aufblasen.

**Comment by oioix** [comment]
Es ist auf jeden Fall so, dass immer ein Eintrag hinzukommt, sobald man im Backend etwas an der Cookie-Konfiguration ändert.
Daher ... einfach machen. Du könntest ja vorsorglich nur die eine Tabelle vorher exportieren. Dann brauchst du im Zweifel nicht alles wieder einzuspielen. 

Noch ein Tipp: Wenn du es künftig automatisiert löschen möchtest, kannst du dafür im Backend einen Cronjob anlegen.

**Comment by Sreyness** [comment]
Danke, eine automatisierte Löschung wird nicht nötig sein, ich hab von der Seite ein Backup zum Testen/Basteln, da werde ich die Datenbank reinladen und schauen.
Der Kunde hat eine Seite in 8 Sprachen, deshalb wird sich da die Speichermenge so dramatisch erhöhen.

**Comment by bitshiftersgmbh** [comment]
Finde das nicht wirklich nötig. 11 MByte ist ja nun auch keine Größe heutzutage. Andere Log-Tables, Page Stats, History-Tables etc. blähen sich naturgemäß auch schnell auf aber wen stört das denn bei dem Webspace den man heutzutage hat?

Den Export in ein File und ein etwaiges Clearen von DB-Tables sollte man dann selbst übernehmen, denke ich, da das eher kein Standard-Szenario ist. Die DB speichert diese Dinge ja nicht ohne Grund (Vorgaben DSGVO und damit einhergehend Nachvollziehbarkeit, wer wann in welche Version von welchem Dienst eingewilligt hat usw.).

Ich würde das Ticket daher schließen.
