### ISSUE TITLE
Änderung an Cookie-Script werden nicht in andere Sprachversion übernommen

### ISSUE THREAD

**Issue by anveno** [FriendsOfREDAXO/consent_manager#97]
z.B. google-analytics; 
1. Änderung des gaProperty-Wertes bei "Skripte, die nach Einverständnis geladen werden" in deutsch
2. Wechsel auf englische Sprache -> im augegrauten Skript-Bereich steht noch der alte Eintrag.

Konnte es nur via direktes Bearbeiten in der iwcc-Datenbank-Tabelle + Löschen der config.json hinbekommen.

REDAXO 5.11.0
iwcc 2.0.0-beta8

Evtl. projektspezifisch, ist mir vorher noch nicht aufgefallen.

**Comment by DanielWeitenauer** [comment]
Das Problem besteht auch im Consent Manager 2.0.1

**Comment by TobiasKrais** [comment]
Ist vermutlich der gleiche Issue wie hier: https://github.com/FriendsOfREDAXO/consent_manager/issues/162

Eine mögliche Lösung wäre das hier: https://github.com/FriendsOfREDAXO/consent_manager/pull/164.
